### ISSUE TITLE
How to compare/see differences between modules in different conditions

### ISSUE THREAD

**Issue by yamihn** [smorabit/scWGCNA#101]
Hi again, Im trying to find modules in my scrna Seq dataset First using only Ko cells, and then repeat again using Wt cells. Then I would to statistically compare the differences between modules in ko and wt. So, which are the steps that I Need to do? Thank you

**Comment by smorabit** [comment]
You should try [differential module eigengene analysis](https://smorabit.github.io/hdWGCNA/articles/differential_MEs.html).

**Comment by yamihn** [comment]
ok, I'll try! another question, the number of modules is just casual or there is a specific reason they are ordered in this way? I saw that in first module genes have the highest kmes score compared with other modules

**Comment by smorabit** [comment]
Sorry I am not sure that I understand your question. Can you please rephrase/clarify? Also it's best to open a new question as its own issue so it's easier to keep track of. Thanks!
