### ISSUE TITLE
Order of modules 

### ISSUE THREAD

**Issue by yamihn** [smorabit/scWGCNA#102]
Hi, my question Is Just how do you ordered the modules. For example, module1 could be also module 3 and module 3 could be module 1? Or there Is a specific reason for this modules rank? I noticed that in the First modules there are genes highly espressed everywhere with High eigengenes score. Is It correct?

**Comment by smorabit** [comment]
By default each module is assigned a color like blue, turquoise, green, etc. Not a number. Are you talking about the function [`ResetModuleNames`](https://smorabit.github.io/hdWGCNA/reference/ResetModuleNames.html)?

> I noticed that in the First modules there are genes highly espressed everywhere with High eigengenes score. Is It correct?

I am not sure what data you're referring to so it's hard for me to understand your question.
