### ISSUE TITLE
Error: package or namespace load failed for 'hdWGCNA'

### ISSUE THREAD

**Issue by ameekbhalla** [smorabit/scWGCNA#107]
Hi,

I get the following error while trying to install hdWGCNA:

```
Error: package or namespace load failed for 'hdWGCNA' in namespaceExport(ns, exports):
 undefined exports: ROCCurves
```

**Comment by smorabit** [comment]
Hi, can you please try to install it again? I accidently left documentation for a function that did not exist so it failed to install. Should be fixed now.

**Comment by ameekbhalla** [comment]
It got installed now. Thank you!

**Comment by smorabit** [comment]
Glad it worked!
