### ISSUE TITLE
assign cells to module

### ISSUE THREAD

**Issue by ruiye88** [smorabit/scWGCNA#108]
Hi,

Thank you for this great package. I'm wondering if there is a function/method to assign single cells to the identified hdWGCNA co-expression modules? Thanks!

Best,
Rui

**Comment by smorabit** [comment]
Hi,

I am confused when you are asking about assigning cells to co-expression modules. These co-expression modules are derived from the gene-gene co-expression network, so they are essentially clusters of **genes**. For that reason, there is not a way to assign cells to the modules.

Are you trying to figure out which cells are expressing the modules? You can [check out in the tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html#module-feature-plots) how to plot the expression of each module (module eigengene) in the single cell data.

**Comment by ruiye88** [comment]
Thank you for the quick response. Yes I was asking about whether there is a common quantitative way to identify cell sub-populations based on the module eigengene. For example, Is there like a cutoff that I could use to say a subpopulation of cells have the green module gene-gene co-expression patterns while they don't have the yellow module gene-gene co-expression patterns? Thanks.

Best,
Rui

**Comment by smorabit** [comment]
> I was asking about whether there is a common quantitative way to identify cell sub-populations based on the module eigengene.

In scRNA-seq analysis, cell sub-populations are typically identified through clustering analysis with community detection algorithms like leiden or louvain. I have not tested the use of module eigengenes for identifying cell sub-populations so I don't really have advice.

> Is there like a cutoff that I could use to say a subpopulation of cells have the green module gene-gene co-expression patterns while they don't have the yellow module gene-gene co-expression patterns

You can just make a scatter plot of the ME for green module versus the ME for yellow module. We don't have any suggestions for defining cutoffs like you are talking about so you would have to come up with a way to define the cutoff.

**Comment by Li-ZhiD** [comment]
Can we assign mudole to cells based on the maximum MEs or hMEs?
