### ISSUE TITLE
Question about setting up the expression matrix

### ISSUE THREAD

**Issue by ningzhy5** [smorabit/scWGCNA#109]
Hello! I'm confused when I select one or more groups before constructing the network. For example, when I choose 'INH' as the given group of cells that will be used for downstream network analysis, there will be results for other cell types as well. I don't know how to explain the results of other cell types. Looking forward to your reply and thanks for designing this well-done software!

**Comment by smorabit** [comment]
Good question. When you run `SetDatExpr` to set up the expression matrix, that is the matrix that will be used to construct the co-expression network. However, after we construct the network we do other things like quantify the gene expression signature of the co-expression modules (aka module eigengenes). 

In the tutorial, the network is constructed only using the inhibitory neurons but the module eigengene calculation is done with the whole dataset. If you are only interested in one of your cell types, I would recommend subsetting your dataset before running any of the hdWGCNA code. For example, this is essentially what was done in [Figure 5 of the hdWGCNA paper.](https://www.biorxiv.org/content/10.1101/2022.09.22.509094v1)

**Comment by ningzhy5** [comment]
I get it！ Thanks for your advise！
