### ISSUE TITLE
Analyse preservation of a module in other network(s)

### ISSUE THREAD

**Issue by saguilarfer** [smorabit/scWGCNA#11]
Dear scWGCNA developer,

Thank you very much for this wonderful single cell implementation of the WGCNA package. 

I am wondering if there is any function to compare modules from two different networks. I worked previously on the WGCNA and I was use to compare two networks using 
          (a) Module Preservation function and analysing the Zsummary and Median rank score 
          (b) Contingency table to analyse the overlapping between modules. 

I am really interested in knowing if a given module is preserved in other networks, so I would really appreciate if you could kindly help me to analyse the preservation of a module in other (or even better in more than one) network.  

Kind regards,
Sergio

**Comment by smorabit** [comment]
Hi,

To answer (a):
You can follow the [Module Preservation tutorial](https://smorabit.github.io/hdWGCNA/articles/module_preservation.html)

For (b) I don't currently have a plan to implement something like this but if you have a function to do this we could figure out how to incorporate it into the package.
