### ISSUE TITLE
Criteria for setting the percentage of cells in which a gene should be expressed 

### ISSUE THREAD

**Issue by kimjh0107** [smorabit/scWGCNA#110]
Hello, Thanks for developing such a great package. I'm currently using it well. 

I was wondering if there is a reference point in the tutorial where you set the ratio of fractions to 0.05 in the SetupForWGCNA function? 

I also checked the fraction of my scRNA-seq data genes expressed in total cells, and the fraction that is not expressed at all or looks like noise was about 1%. So I was wondering the fraction to 0.05 in hgWGCNA tutorial, is that a threshold based on any biological basis? I have a limited knowledge of biology, so I would really appreciate it if you could explain the fraction ratio that is widely used in this field and why. 

Thank you,

**Comment by smorabit** [comment]
Hi, let me try to answer your questions. 

For co-expression network analysis, we could potentially use all of the genes in the dataset. However, some of the genes are expressed at a very low level or are only expressed in specific cell populations. Genes like this may just add unwanted noise into our network analysis, so it makes sense for us to try to do some feature selection.

> I was wondering if there is a reference point in the tutorial where you set the ratio of fractions to 0.05 in the SetupForWGCNA function?

We reference this in the ["Set up Seurat object for WGCNA"](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html#set-up-seurat-object-for-wgcna) section of the tutorial. We actually give multiple options for feature selection, either selecting highly variable genes, genes expressed in a certain fraction of cells, or a custom gene list.

> I was wondering the fraction to 0.05 in hgWGCNA tutorial, is that a threshold based on any biological basis?

This is an arbitrary threshold and ideally it should be tuned to your own dataset.

>  if you could explain the fraction ratio that is widely used in this field and why.

In general this type of data analysis is relatively new in scRNA-seq, and to my knowledge there hasn't been a full study of feature selection for co-expression network analysis in single-cell data, so I don't believe that there is a "fraction ratio that is widely used in this field". It's up to you what features you decide to choose to perform network analysis on.
