### ISSUE TITLE
Input custom gene list for enrichment of modules?

### ISSUE THREAD

**Issue by cnk113** [smorabit/scWGCNA#113]
Hello,

I was wondering if it was possible to look at gene overlap/enrichment (with directionality) from a custom list of genes such as GWAS hits etc. with the modules constructed?

Best,
Chang

**Comment by smorabit** [comment]
I am not sure what you mean by directionality, but yes you can overlap a set of genes with the modules. I don't have a tutorial to do this on the hdWGCNA website but I will add one when I get the chance. For now you can see how I did this for a figure in the [hdWGCNA paper figure 4](https://www.biorxiv.org/content/10.1101/2022.09.22.509094v1). 

Check the code [here](https://github.com/smorabit/hdWGCNA_paper/blob/main/Figure5/Figure5.Rmd) starting at line 332. I basically have a list of GWAS genes for autism, and then I looped through each module and used the R package [GeneOverlap](https://bioconductor.org/packages/release/bioc/html/GeneOverlap.html) to compute the overlap statistics.
