### ISSUE TITLE
Change Module Colors

### ISSUE THREAD

**Issue by RcuIT** [smorabit/scWGCNA#115]
Hi,
Is it possible to change module colors using user-defined colors when performing [PlotDendrogram](https://smorabit.github.io/hdWGCNA/reference/PlotDendrogram.html) () function?  If so, could you please provide how to do it?
Thanks

**Comment by smorabit** [comment]
Hi,

Have you tried the[ tutorial for resetting the module colors](https://smorabit.github.io/hdWGCNA/articles/customization.html#re-coloring-hdwgcna-modules)?

**Comment by RcuIT** [comment]
Hi Smorabit/Hdwgcna,
Thanks for the reply. I missed this part in the tutorial. Thanks for
pointing it out.
Best,
Roshan
*________________________________________*
*Roshan Priyarangana Perera, Ph.D (he/him/his)*
Postdoctoral Research Scientist

Department of Cell and Developmental Biology

Biomedical Research Building II/III

University of Pennsylvania

Philadelphia, PA 19104, USA


*Primary Contact*
*Email :* ***@***.***
***@***.***>*
*Research lab :* *https://www.rajlab-neuro.com/
<https://www.rajlab-neuro.com/>*

*Social Media*
*linkedin : *
*https://www.linkedin.com/in/roshan-priyarangana-perera-448ba340/*
<https://www.linkedin.com/in/roshan-priyarangana-perera-448ba340/>
*ResearchGate :* *https://www.researchgate.net/profile/Roshan-Perera-3
<https://www.researchgate.net/profile/Roshan-Perera-3>*
