### ISSUE TITLE
igraph functions in plotting.R cannot be called properly

### ISSUE THREAD

**Issue by jerviedog** [smorabit/scWGCNA#118]
The invocation of **igraph** functions **E()**, **V()** and **get.edgelist()** in **plotting.R** file throws errors because the invocation of these functions lacks the package prefix. 

If I add **igraph::**, the errors are corrected.

By the way, **qgraph** package is also required when plotting networks. Maybe this can be added to the installation instruction in the installation page.

**Comment by smorabit** [comment]
Can you please be more specific and provide more details?

**Comment by jerviedog** [comment]
> Can you please be more specific and provide more details?

Hi, errors occurred when I tried to plot the networks. Attached is the diff file of plotting.R in the repo and the one I had modified.
[plotting.R.txt](https://github.com/smorabit/hdWGCNA/files/11621485/plotting.R.txt)

**Comment by smorabit** [comment]
Fixed in the latest version. Thank you for identifying this issue.
