### ISSUE TITLE
Projecting modules to new Spatial dataset

### ISSUE THREAD

**Issue by LiangMingxuan00** [smorabit/scWGCNA#119]
Hi,

Thanks for your fantastic analysis tools! I have a question about how to projecting the modules to new Spatial dataset. I'm working in two condition spatial sample and I would like to use hdWGCNA in control and project the mutant sample to control to see the module patterns change. I wonder how to do it, could you help me solve this question? Thanks in advance.

Best,
Mingxuan

**Comment by smorabit** [comment]
Hi Mingxuan,

I think you should start with the [spatial transcriptomics tutorial](https://smorabit.github.io/hdWGCNA/articles/ST_basics.html), and then take a look at the [tutorial for projecting modules into a new dataset](https://smorabit.github.io/hdWGCNA/articles/projecting_modules.html).

**Comment by LiangMingxuan00** [comment]
Hi,

Thanks for your kindly reply. I have already run the code based on the tutorial for projecting modules but I not very sure query object processed is right. Is it ok to input the original Seurat spatial object as query in analysis? or may be it need to find the metaspot or something processed?

Best,
Mingxuan

**Comment by smorabit** [comment]
I think that I would better understand your issue in order to help you if you could please show the code that you are using.

**Comment by smorabit** [comment]
Closing this issue as completed but feel free to re-open if there is any new information.
