### ISSUE TITLE
New tag and/or new release

### ISSUE THREAD

**Issue by jowodo** [smorabit/scWGCNA#124]
**Is your feature request related to a problem? Please describe.**
I want to create a conda environment for hdWGCNA, but the version is not directly visible via tags/releases. 

**Describe the solution you'd like**
Tag and/or release the latest versions

**Comment by smorabit** [comment]
Hi,

You can see the instructions to create a conda environment for hdWGCNA [here](https://smorabit.github.io/hdWGCNA/).

**Comment by jowodo** [comment]
Thanks for the swift reply. 
I would like to be able to do something like this:
```
conda create -n hdwgcna -c conda-forge r-base r-essentials
conda activate hdwgcna
echo "install.packages('BiocManager') " | R --no-save
echo "BiocManager::install()" | R --no-save
echo "install.packages(c('Seurat', 'WGCNA', 'igraph', 'devtools', 'tester'))" | R --no-save
echo 'library("BiocManager"); BiocManager::install(c("impute", "preprocessCore", "GO.db", "AnnotationDbi"))' | R --no-save
echo "install.packages(c('Seurat', 'WGCNA', 'igraph', 'devtools', 'tester'))" | R --no-save # WGCNA needs BiocManager dependencies 
echo "devtools::install_github('smorabit/hdWGCNA', ref='v0.1.1')" | R --no-save
```
This works, but version 0.1.1 is the highest version, for which this works. The only alternative is to install directly from the dev branch. Tagging commits with version numbers would make it possible to install specific versions of hdWGCNA. This is turn would make versioning more transparent and the software more reproducible. 

Thanks for your time and consideration.

**Comment by smorabit** [comment]
Thanks for the explanation, I will start adding tags with future updates.

**Comment by jowodo** [comment]
Hi, 

I came across this way to tag previous commits: 
```
git clone https://github.com/smorabit/hdWGCNA
cd hdWGCNA
git log --graph --oneline # choose commit to tag
git checkout 4e61437 # 4e61437 is the chosen commit 
git tag v0.2.0
git push origin --tags
```
It would be greatly appreciated if you could tag previous versions or the latest version. See [this stackoverflow answer](https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository/18223354#18223354) for more info. 

Thanks
