### ISSUE TITLE
Network analysis on genotypes

### ISSUE THREAD

**Issue by yamihn** [smorabit/scWGCNA#135]
Hi, I have a question, or if can call it just a curiosity. I analysed my dataset consisting on 5 clusters, running hdWGCNA on each cluster. My question is if make it sense if I separate each cluster by genotype (for example, cluster 1 Ko and cluster 1 wt) and I run hdWGCNA on each of them, comparing the modules and the hub genes for each module.
Thank you, have a nice day

**Comment by smorabit** [comment]
Yes I think that does make sense. Let me know if you have any other questions regarding this analysis.
