### ISSUE TITLE
force module assignment for all genes

### ISSUE THREAD

**Issue by Brawni** [smorabit/scWGCNA#137]
Hello!
I often time find genes of interest being assigned to no modules (ie grey module) and so i have to run multiple iterations tuning parameters at each step to try to get them to a more meaningful module. What would be the parameters that can help the most in being less strict with module assignment ? 
I wonder if it's legit to just assign each gene to the eigenvector to which they are most correlated? If it is, I think that would be a nice optional feature to add. Assigning genes to module would be very quick using the modules table but I'm wondering if forcing assignments make sense or not?  

Thanks so much and great package!!

**Comment by smorabit** [comment]
Forcing all of the grey module genes into other modules is not recommended. There are many parameters that you can try to change in `ConstructNetwork` that will affect the downstream modules, like `mergeCutHeight` or `detectCutHeight` for example.
