### ISSUE TITLE
DEGs marker gene overlap analysis

### ISSUE THREAD

**Issue by madhubioinformatics** [smorabit/scWGCNA#139]
Hello,
I just wanted to run the overlap gene analysis for differentially expressed genes(DEGs) in two different condition groups instead of marker gene overlap analysis. Is it possible to do this analysis in the hdWGCNA algorithm? If it's possible can get simple code for that?

**Comment by smorabit** [comment]
I recommend looking at [this R package](https://bioconductor.org/packages/release/bioc/html/GeneOverlap.html) which is specialized in gene set overlap analysis.
