### ISSUE TITLE
Question about compare across conditions using consensus network analysis

### ISSUE THREAD

**Issue by hoholee** [smorabit/scWGCNA#140]
Hi, first of all, thank you for building this amazing package!

I have a question about comparing the modules / MEs between conditions. It seems to me that one can either use the standard hdWGCNA workflow to construct the co-expression network using all cells of one cell type from all the conditions, followed by the Differential module eigengene (DME) analysis; or use the consensus network analysis to build the consensus modules across all conditions, then perform DME analysis using these consensus modules.

I'm wondering what the differences between these two options are and which option you would recommend.

Any input on this would be appreciated!

**Comment by smorabit** [comment]
Hi, 

Thanks for your interest in hdWGCNA. First of all this is a great question. I think that these are both valid approaches, but it is hard for me to recommend one over the other without seeing the results from both analyses. In principle, the consensus network analysis will identify conserved networks between the different groups that you specify. For example, if you did this with biological sex, you might find networks / modules conserved between male & female but not those that are specific. This is just hypothetical of course, not sure how it would actually look like when you run the analysis. That being said, in my [previous paper with bulk RNA-seq](https://academic.oup.com/hmg/article/29/17/2899/5892988?login=true) we did consensus networks across different brain regions, but each of those brain regions contained both controls and disease cases, so we were able to identify disease-associated gene modules. For the standard approach you will likely find modules that are specific to each of your conditions. So ultimately it really is a nuanced problem of properly formulating your co-expression network analysis.

**Comment by hoholee** [comment]
Thanks! I was getting the same idea after I read through your manuscript and the tutorial. I think I'm going to use the standard workflow so that I can get the condition-specific modules.

Another concern would be the differences in the number of cells (and hence the number of metacells) that are used in constructing the network in the two approaches. The individual network built per condition in the consensus method will by definition take fewer cells/metacells as input, which may be noisier than the standard workflow. I assume this may cause some troubles, especially when some of the cell types are not balanced in cell counts across conditions.

I understand this will also depend on the dataset and it's better to test this with the particular dataset in hand. But in general, do you think this will make a big difference in the results?

**Comment by smorabit** [comment]
I am honestly not sure how much of a difference it would make in the results and I am not sure how useful speculating about it would be, you can certainly try to run the analysis in the different ways as you have proposed and try to compare the results.
