### ISSUE TITLE
TestSoftPowers function

### ISSUE THREAD

**Issue by Rahul1711arora** [smorabit/scWGCNA#143]
Hi @smorabit , 

I have been running hdWGCNA on a number of datasets from past couple of days. They were seem to be running perfectly fine and then these two things happened. 

1. When I'm processing the Seurat object initially to perform SCT transformation, I was using a parameter called `method = glmgampoi`, which if I do use, the processing stops and the error message appears: `
Error: (converted from warning) useNames = NA is deprecated. Instead, specify either useNames = TRUE or useNames = TRUE.
`. I have sorted this out by removing the method argument but if there's a way to add this back, it would be great. 

2. Upon running the `TestSoftPower` function, I'm getting this error: `Error in { : 
  task 1 failed - "(converted from warning) bicor: zero MAD in variable 'x'. Pearson correlation was used for individual columns with zero (or missing) MAD."`. This use to appear as warning as you can see but has now abruptly converted into an error. Not sure how to resolve this as googling suggested very outdated options which didn't work for this, such as using a solution mentioned [here](https://support.bioconductor.org/p/75956/). It would be helpful if we can find the work around this? 

Thanks in advance!

**Comment by smorabit** [comment]
Hi let me try to answer your questions. In the future, please keep one GitHub issue to a single question.

> When I'm processing the Seurat object initially to perform SCT transformation, I was using a parameter called method = glmgampoi, which if I do use, the processing stops and the error message appears: Error: (converted from warning) useNames = NA is deprecated. Instead, specify either useNames = TRUE or useNames = TRUE.. I have sorted this out by removing the method argument but if there's a way to add this back, it would be great.

This sounds like an issue with SCTransform rather than hdWGCNA so I would suggest opening an issue on their GitHub. 

> Upon running the TestSoftPower function, I'm getting this error: Error in { :    task 1 failed - "(converted from warning) bicor: zero MAD in variable 'x'. Pearson correlation was used for individual columns with zero (or missing) MAD.". This use to appear as warning as you can see but has now abruptly converted into an error. Not sure how to resolve this as googling suggested very outdated options which didn't work for this, such as using a solution mentioned [here](https://support.bioconductor.org/p/75956/). It would be helpful if we can find the work around this?

Are you able to provide a reproducible example? It is difficult for me to figure out what is the source of your error unless I can reproduce it.
