### ISSUE TITLE
Question about comparing healthy vs diseased conditions across groups of cells (instead of exploring each cell type individually)

### ISSUE THREAD

**Issue by maithermbarros** [smorabit/scWGCNA#144]
Hi! I am studying cancer and I am having a hard time choosing the best design within hdWGCNA to get biological insights from my dataset. I ran the normal hdWGCNA pipeline + enrichment analysis using the whole dataset and then started enquiring cell types separately like you do in the tutorial, but this approach was not giving us biological insights. 

Ultimately, I want to understand what happens in "healthy cells/healthy patients" by exploring modules etc and then exploring "unhealhy cells/diseased patients" so see if healthy modules are conserved in the diseased state. 

This is what I am trying to do, but I am not sure this is a good approach: **_Choose "healthy cell types" + "healthy patients" and run the co- expression pipeline and then project healthy modules into diseased cell types + diseased patients._**
(I also tried running differential module eingene analysis comparing Healthy and Diseased groups within each "Healthy" module, but I have a feeling that this is not correct since not all cell types were included in the hdWGCNA analysis....)

### I have a big Seurat dataset including cells from the gastrointestinal tract (esophagus, gut and intestine). Samples come from different patients (healthy vs diseased), and after running the whole Seurat pipeline we ended up with a bunch of cell types (26 in total):
```
> unique(coexp_hdWGCNA@meta.data$Patient_type)
[1] Healthy  Diseased


> unique(coexp_hdWGCNA@meta.data$Celltypes_global)
 [1] Superficial                 Intermediate                Suprabasal                 
 [4] Basal                       T-Cells                     Macrophages                
 [7] Mast                        Endothelial                 Enteroendocrine_GHRL       
[10] Foveolar_Intermediate       Erythrocyte                 Enterocytes_Intermediate   
[13] Chief                       Foveolar_Differentiated     Enteroendocrine_CHGA       
[16] Parietal                    Plasma-Cells                Neck-Cells                 
[19] Fibroblasts                 B-Cells                     SMG                        
[22] Intestinal_Undifferentiated Goblet                      Enterocytes                
[25] Enteroendocrine_GAST  
```

### This is what I have done so far:

```
# keep only a few celltypes that we consider being "healthy"
hdWGCNA_healthy <- subset(coexp_hdWGCNA, subset = Celltypes_global %in% c("Neck-Cells", "Intestinal_Undifferentiated", "Intermediate", "Foveolar_Differentiated", "Foveolar_Intermediate", "Enterocytes", "Enterocytes_Intermediate"))
unique(hdWGCNA_healthy@meta.data$Celltypes_global)

# Set up for WGCNA:
hdWGCNA_healthy <- SetupForWGCNA(
      hdWGCNA_healthy,
      gene_select = "fraction",
      fraction = 0.05,
      wgcna_name = "Healthycells",
      group.by = "Celltypes_global") # use genes that are expressed in at least 5% of the cells in each group of cells 


# Construct metacells:
hdWGCNA_healthy <- MetacellsByGroups(
      seurat_obj = hdWGCNA_healthy,
      group.by = c("Patient_type", "Sample", "Celltypes_global"),
      k = 30,
      max_shared = 15,
      min_cells = 70,
      reduction = 'harmony',
      ident.group = "Patient_type")

# process everything
hdWGCNA_healthy <- NormalizeMetacells(hdWGCNA_healthy)
hdWGCNA_healthy <- ScaleMetacells(hdWGCNA_healthy, features = VariableFeatures(hdWGCNA_healthy), wgcna_name = "Healthycells")
hdWGCNA_healthy <- RunPCAMetacells(hdWGCNA_healthy, features = VariableFeatures(hdWGCNA_healthy), wgcna_name = "Healthycells")
hdWGCNA_healthy <- RunHarmonyMetacells(hdWGCNA_healthy, group.by.vars='Sample')
hdWGCNA_healthy <- RunUMAPMetacells(hdWGCNA_healthy, reduction = "harmony", dims = 1:25)

# set up expression matrix for "healthy" patients only
hdWGCNA_healthy<- SetDatExpr(
    hdWGCNA_healthy,
    group_name = "Healthy", 
    group.by = "Patient_type",
    use_metacells = TRUE,
    slot = 'data',
    assay = "RNA")

# tested soft powers and got "10" as a result
hdWGCNA_healthy <- TestSoftPowers(
  hdWGCNA_healthy,
  setDatExpr = FALSE)

# construct network 
hdWGCNA_healthy <- ConstructNetwork(
  hdWGCNA_healthy,
  soft_power = 10,
  tom_name = "Healthy", # prefix name given to the TOM output file
  overwrite_tom = TRUE)
```

### I tried running Module eingenes without harmonizing and it kept giving me an later on the pipeline. Here I am harmonizing by "healthy" vs "diseased", but I am not sure if this is a good approach?
```
# compute MEs
hdWGCNA_healthy <- ScaleData(hdWGCNA_healthy, features=VariableFeatures(hdWGCNA_healthy))
hdWGCNA_healthy <- ModuleEigengenes(
 hdWGCNA_healthy,
 group.by.vars = "Patient_type",# harmonization to reduce batch effects, I chose to harmonize healthy 
 verbose = TRUE,
 exclude_grey = TRUE)

# hub genes for healthy patients
hdWGCNA_healthy <- ModuleConnectivity(hdWGCNA_healthy,
                                       group.by = "Patient_type",
                                       group_name = "Healthy")

# reset moduleNames
hdWGCNA_healthy <- ResetModuleNames(hdWGCNA_healthy, new_name = "Healthy-M")

# compute hug gene signature scores
hdWGCNA_healthy <- ModuleExprScore(hdWGCNA_healthy, n_genes = 25, method = "Seurat")

#individual module plots
ModuleNetworkPlot(hdWGCNA_healthy)

#applying umap to co-expression networks
hdWGCNA_healthy <- RunModuleUMAP(
  hdWGCNA_healthy,
  n_hubs = 10,
  n_neighbors = 15) #  min_dist = 0.1

##### tried this as mentioned above, but I am not sure about it
# Differential module eigengene DME analysis comparing Healthy and Diseased groups within each "Healthy" module
group1 <- hdWGCNA_healthy@meta.data %>% subset(Patient_type == 'Healthy') %>% rownames
group2 <- hdWGCNA_healthy@meta.data %>% subset(Patient_type == 'Diseased') %>% rownames

# run FindDMEs function
DMEs <- FindDMEs(
  hdWGCNA_healthy,
  barcodes1 = group1,
  barcodes2 = group2,
  test.use='wilcox',
  wgcna_name='Healthycells')

DMEs

```

### Then I am selecting all the remaining cell types in the dataset and choosing only "diseased" patients, so I can project healthy modules and see if they are preserved in the dataset:

```
# Module Projection with "Unhealthy" Cells and "Diseased" Patient types
coexp_hdWGCNA <- readRDS("Seurat_Analysis-BEIM_GIM-hdWGCNA_Final.rds")
unique <- as.character(unique(coexp_hdWGCNA@meta.data$Celltypes_global))
healthy <- c("Neck-Cells", "Intestinal_Undifferentiated", "Intermediate", "Foveolar_Differentiated", "Foveolar_Intermediate", "Enterocytes", "Enterocytes_Intermediate")
not_healthy <- setdiff(unique, healthy)

#selecting remaining cells
hdWGCNA_nothealthy <- subset(coexp_hdWGCNA, subset = Celltypes_global %in% not_healthy)
#selecting diseased patients
hdWGCNA_nothealthycells_diseased <- subset(hdWGCNA_nothealthy, subset = Patient_type == "Diseased")

hdWGCNA_nothealthycells_diseased <- ProjectModules(
  seurat_obj = hdWGCNA_nothealthycells_diseased,
  seurat_ref = hdWGCNA_healthy,
  wgcna_name_proj="Nothealthy_diseased_projected", # name of the new hdWGCNA experiment in the query dataset
  wgcna_name = "Healthycells" # name of the hdWGCNA experiment in the ref dataset
)

```

Any insights would be greatly appreciated! Thanks a lot!

**Comment by smorabit** [comment]
Hi! Based on your post, it seems like your question is essentially how should you design your network analysis to make the most sense given your particular setup/dataset.

> Ultimately, I want to understand what happens in "healthy cells/healthy patients" by exploring modules etc and then exploring "unhealhy cells/diseased patients" so see if healthy modules are conserved in the diseased state.

Okay based on this, it seems like you want to build the co-expression network and identify gene modules in the healthy group and then project the modules into the disease group. I am not exactly sure what the difference between healthy cells and healthy patients are in your description. 

> This is what I am trying to do, but I am not sure this is a good approach: Choose "healthy cell types" + "healthy patients" and run the co- expression pipeline and then project healthy modules into diseased cell types + diseased patients.
(I also tried running differential module eingene analysis comparing Healthy and Diseased groups within each "Healthy" module, but I have a feeling that this is not correct since not all cell types were included in the hdWGCNA analysis....)

To clarify, module eigengenes (MEs) are based on PCA, so it is essentially a representation of the gene expression of a particular module but it is a relative value that is being calculated, so if you do it this way where you are calculating MEs for one group (healthy) and then another group (disease) separately, you are not able to do differential module eigengene analysis with this setup. You would have to calculate the MEs for healthy + disease together. However, you could alternatively run the module preservation analysis in the disease group after you projected the modules from the healthy group and you could end up with a similar interpretation.

> I tried running Module eingenes without harmonizing and it kept giving me an later on the pipeline. Here I am harmonizing by "healthy" vs "diseased", but I am not sure if this is a good approach?

I would not advise you to harmonize the MEs based on healthy vs disease. Harmony is meant to reduce technical variation for example which may come from different sequencing experiments etc. If you provide Harmony with disease vs healthy, you are telling it to remove the variation that comes from the disease component essentially. I would imagine this would lead you to have very little differences when you are looking at differential MEs downstream.

Let me know if this helped or if you have any more specific questions! Happy to answer them.

**Comment by maithermbarros** [comment]
Hi Sam. Thanks for getting back to me, this was super helpful. 

> Hi! Based on your post, it seems like your question is essentially how should you design your network analysis to make the most sense given your particular setup/dataset.

Exaclty!

> I am not exactly sure what the difference between healthy cells and healthy patients are in your description.

Basically, biopsy samples were collected throughout the gastrointestinal tract from patients with pre-cancerous lesions. This includes different types of lesions depending on where the biopsies were collected from (esophagus, gut, intestine).  
Then, reference/control samples were collected from the same anatomical areas as in the diseased group but from donors that were totally healthy (no signs of pre-cancerous lesions) and these are our healthy samples. I hope that makes sense. 

In terms of healthy cells, these are just a category that we created when trying to analyze the data. This does not have anything to do with biopsy classification, we just thought it could be a better design for the analysis itself. We considered 'healthy' cells the ones that are found in the normal GI tract and excluded immune/inflammatory cells and cells linked to precancerous states even if they originated from healthy patients. I am not too sure whether adding this extra layer of sample separation is a good approach though. Any thoughts?

> You would have to calculate the MEs for healthy + disease together. However, you could alternatively run the module preservation analysis in the disease group after you projected the modules from the healthy group and you could end up with a similar interpretation.

Agreed! I came to this conclusion on my own, before posting this question, and decided to follow the second option you mentioned: analyzing healthy cells followed by running module projeciton+preservation analysis in the diseased group.  But I wonder if the first option is better. Do you have a personal preference?

> Okay based on this, it seems like you want to build the co-expression network and identify gene modules in the healthy group and then project the modules into the disease group

This is what I have done, followed by module preservation. I have the analysis in a .html file if you'd like to have a look. I can't post it here but could send it to you by email. No worries if not. 

However I am not confident that I can trust the results. It feels like there's a lot of data wrangling/manipulation before I get to enrichment analysis and module projection/preservation. I am going to subset my data and run the pipeline changing a few parameters and see if the results are consistent, I am just worried it will take too much of my time and distract me from the real analysis. For example, I still haven't found the best value for 'k' when creating metacells. I went from 75k cells to almost 20k metacells when using k=30 (min_cells 70 and max_shared 15), but this feels like too many metacells still. (Maybe I will make another post just about this since it feels like a different question!).  

> I would not advise you to harmonize the MEs based on healthy vs disease. Harmony is meant to reduce technical variation for example which may come from different sequencing experiments etc. If you provide Harmony with disease vs healthy, you are telling it to remove the variation that comes from the disease component essentially. I would imagine this would lead you to have very little differences when you are looking at differential MEs downstream.

Right, this makes a lot of sense. I suspected something was off. 
Before harmonizing based on healthy vs diseased, I tried skipping the harmonization step but later on the pipeline I had an error when working with the modules (I don't remember what error I got since I went back and did the harmonization and it "worked"). Then I tried harmonizing by 'Patients' (all the different Samples) but the function kept throwing me an error. That's when I tried with healthy vs diseased.

**Comment by smorabit** [comment]
>  I am not too sure whether adding this extra layer of sample separation is a good approach though. Any thoughts?

Seems reasonable for your experimental setup, but I am not super confident since I haven't worked with data like that before.

> Agreed! I came to this conclusion on my own, before posting this question, and decided to follow the second option you mentioned: analyzing healthy cells followed by running module projeciton+preservation analysis in the diseased group. But I wonder if the first option is better. Do you have a personal preference?

I don't really have a preference, I think you could arrive at the same conclusion or interpretation using different approaches.

> However I am not confident that I can trust the results. It feels like there's a lot of data wrangling/manipulation before I get to enrichment analysis and module projection/preservation.

To be fair, there's a lot of data wrangling involved in single-cell analysis in general. Even just to get your clusters + DEGs, there's so many different steps and transformations each with their own set of parameters. I understand where you are coming from, but unfortunately don't have much advice for you if this is something you are worried about for co-expression network analysis you could be worrying about this for every step of your pipeline as well.

> Before harmonizing based on healthy vs diseased, I tried skipping the harmonization step but later on the pipeline I had an error when working with the modules (I don't remember what error I got since I went back and did the harmonization and it "worked"). Then I tried harmonizing by 'Patients' (all the different Samples) but the function kept throwing me an error. That's when I tried with healthy vs diseased.

If you open a new issue with the error info I would be happy to help resolve it.
