### ISSUE TITLE
Getting gene list and enrichment after DME

### ISSUE THREAD

**Issue by Rahul1711arora** [smorabit/scWGCNA#146]
Hi Sam, 

Thanks for all the help with fixing the errors and answering previous questions. I was wondering that when we perform differential module expression, we get a nice table with all the values and the modules with their colours. Would it be possible to add two columns to the table? 

1. That defines the state of the module, such as up or down-regulated? 
2. The list of genes in that module? 

This way, we can run the enrichment for the up/down regulated gene lists coming out of each comparison. 

If it's straight forward, then it would be helpful to get some pointers and I can do it on my dataset. If you would like to consider it to be added as a feature for later releases of the tool, that would be great as well. 

Thanks!

**Comment by smorabit** [comment]
Hi Rahul,

Assuming that you have run the DME test as in the tutorial:

```

DMEs <- FindDMEs(
  seurat_obj,
  barcodes1 = group1,
  barcodes2 = group2,
  test.use='wilcox',
  wgcna_name='INH'
)

```

You can check if the module is up or downregulated based on the fold-change. Positive fold-change means that module is upregulated, negative means the module is downregulated.

```
DMEs$status <- ifelse(DMEs$avg_log2FC > 0, 'Upregulated', 'Downregulated')
```

You can check the lists of genes for each module in the modules table.

```
modules <- GetModules(seurat_obj)
```

Hope this helps!
