### ISSUE TITLE
Divide the module again for the module

### ISSUE THREAD

**Issue by maqingyue** [smorabit/scWGCNA#147]
Hi Sam,
Thank you very much for developing this package, this is very useful to me.

Now I have divided the module, but the kME value of my target gene in the module is very low, so I plan to conduct hdwgcna analysis again for a specific module until I find a cluster of genes with a high correlation with my target gene. May I ask how I can extract this module and make it a separate seurat object? Do you think this idea of re-dividing is feasible?

Thanks a lot!

**Comment by smorabit** [comment]
Hi I am happy to help but I do not fully understand your question. It sounds like you have a gene of interest but it is not assigned to a co-expression module in your analysis?

> Do you think this idea of re-dividing is feasible?

It depends, I have actually done this before in one of my (unpublished, in preparation) data analyses. I think it is reasonable if the module has enough genes. Not sure what the minimum would be, but for example if your module has only 50 genes, running hdWGCNA again on this module is likely not going to give meaningful results. When I did this I think the module had over 3,000 genes and it did give meaningful modules by running hdWGCNA in this case.

> May I ask how I can extract this module and make it a separate seurat object? 

You can get the module table by running `GetModules(seurat_obj)`. You can then subset this table to get your gene list of interest, then I would suggest starting the hdWGCNA pipeline again and specify this list of genes for the analysis.

```
my_module <- 'blue'
modules <- GetModules(seurat_obj)
my_genes <- subset(modules, module == my_module) %>% .$gene_name

seurat_obj <- SetupForWGCNA(
  seurat_obj,
  features = my_genes,
  wgcna_name = 'submodules'
)
```
