### ISSUE TITLE
Question about Module trait correlation

### ISSUE THREAD

**Issue by suanzaoren** [smorabit/scWGCNA#148]
Hello Sam,

Thank you  so much for developing this R package, this help me a lot.

Now, I have already completed hdWGCNA in single-cell data,but when I do Module trait correlation step next, I find that the some p-value of correlation between  gene modules and traits is 0.
 
I am puzzled by this phenomenon. I wish you could help me explain this situation or  is there a solution.

My sincere thanks again.

**Comment by smorabit** [comment]
Hi,

A p-value of zero means that it's the minimum value that R can handle. Correlations with a lot of data points tend to have very low p-values, which is often the case in single-cell.

**Comment by suanzaoren** [comment]
Thanks for your reply, I think I've understood the question with your help
