### ISSUE TITLE
The parameter networkType of TestSoftPowers is invalid

### ISSUE THREAD

**Issue by xiesiqiu** [smorabit/scWGCNA#150]
**Describe the bug**
Provide a clear and concise description of what the bug/error is. If there is an error message, please copy it here. **If you have more than one bug/error, please open separate GitHub issues.**

The parameter networkType of TestSoftPowers is invalid

**Steps to reproduce**
Describe the steps included to reproduce the error, including all of the hdWGCNA code used prior reaching the error. Describe the dataset that you are using, and whether or not the error could be reproduced on one of our provided tutorial datasets, or on another publicly available dataset.

```
# Put code in this box
```
WGCNA_obj <- TestSoftPowers(
    WGCNA_obj,
    use_metacells = TRUE,
    setDatExpr = FALSE,
    powers = c(seq(1, 10, by = 1), seq(12, 30, by = 2)),
    group.by = "seurat_clusters",
    networkType="signed"
    )

Error in TestSoftPowers(WGCNA_obj, use_metacells = TRUE, setDatExpr = FALSE,  :
  unused argument (networkType = "signed")

**R session info**
Please run `sessionInfo()` and report the output.

**Screenshots**

**More than one problem?** 
If you have more than one problem with hdWGCNA, create separate issues for your individual problems.

**Comment by smorabit** [comment]
Unfortunately I am not able to reproduce your error message. If you can provide me with some more relevant information I might be able to help.

**Comment by xiesiqiu** [comment]
Dear Author,

First and foremost, I want to express my sincere gratitude for your quick response to my feedback.

Regarding the problem I described, I understand that you haven't encountered it in your environment, which has left me a bit puzzled. I have run most of the processes using hdWGCNA developed by your team. I understand that this software offers three options for the networkType parameter when determining the soft threshold: "unsigned," "signed hybrid," and "signed," with "signed" being the default choice. I wanted to test if "signed hybrid" would yield any improvements in my results. However, I encountered an error when trying to input the networkType parameter.

The screenshots in the attachment are the results generated using your developed workflow and the error I encountered when using the networkType parameter.I believe that if I can smoothly run the entire workflow with default parameters, it shouldn't be an issue with my R environment.

result by hdWGCNA:
[截屏2023-09-10 20.20.11.png]

Error:
[截屏2023-09-10 20.23.19.png]

Best regards,
Nianxia

2023年9月9日 11:33，Sam Morabito ***@***.***> 写道：

外部邮件/External Mail




Unfortunately I am not able to reproduce your error message. If you can provide me with some more relevant information I might be able to help.
