### ISSUE TITLE
hDWGCNA with harmonized Seurat object

### ISSUE THREAD

**Issue by iichelhadi** [smorabit/scWGCNA#155]
Hello,

I am trying to run your pipeline using a harmonized seurat object and the cells can have considerable difference in sequencing depth.
Following your pipeline for figure 6 I found that some batches don't reach the minimum fit cutoff of 80%. Should those datasets be removed or should I increase the range of softpower over 30 or change network type?

Regards,

**Comment by smorabit** [comment]
Hi, 

I am happy to help but a little confused, could you please clarify some things.

> harmonized seurat object 

Is this a special type of seurat object or something? I am not sure what a "harmonized seurat object" is.

> Following your pipeline for figure 6 I found that some batches don't reach the minimum fit cutoff of 80%

I don't know what you are referring to here, can you please clarify.

**Comment by iichelhadi** [comment]
> Hi,
> 
> I am happy to help but a little confused, could you please clarify some things.
> 
> > harmonized seurat object
> 
> Is this a special type of seurat object or something? I am not sure what a "harmonized seurat object" is.
> 
> > Following your pipeline for figure 6 I found that some batches don't reach the minimum fit cutoff of 80%
> 
> I don't know what you are referring to here, can you please clarify.

Apologies for the confusing. I am integrating multiple datasets using Harmony (harmonized seurat object) and when trying to run `TestSoftPowersConsensus` some datasets don't reach the softpower threshold of 0.8.
My goal is to use the detected modules to correlate to clinical traits using `ModuleTraitCorrelation`.
I hope this makes things clearer.
Regards

**Comment by iichelhadi** [comment]
I tried to follow your script for Figure 6 where you also generated harmony integrated data from 4 different scRNA-seq
