### ISSUE TITLE
New release/tag

### ISSUE THREAD

**Issue by jowodo** [smorabit/scWGCNA#159]
**Is your feature request related to a problem? Please describe.**
The last release is over one year ago, so it the last tag. The last change in the repo is 2 weeks ago, though. 

**Describe the solution you'd like**
A new tag/release would resolve issues mentioned in #124

Thanks for your time, attention and consideration.

**Comment by smorabit** [comment]
I am planning to make a new release when there is a major update to hdWGCNA, which should be in the next few months to add some new functionality. I don't recommend trying to use old versions of the package.

**Comment by jowodo** [comment]
maybe the current version could be tagged?
