### ISSUE TITLE
Warning: Cannot find a parent environment called Seurat

### ISSUE THREAD

**Issue by B-WingBreaker** [smorabit/scWGCNA#16]
Dear hdWGCNA developers,

First, thank you for providing such a wonderful series of packages!

I am meeting a problem after the release of the hdWGCNA. When I tried to normalize my meta-cell expression matrix, the following warning jumped out and then the normalization began to occupy hundreds of GBs of the memory. 

I started with my own Seurat Object, which was about 4.9 GB only. I tried on the supercomputer, and it said that the maximal memory usage during the normalization exceeded 596.2G, and it was over my requested memory amount so the job was crushed.

The following was done on my PC. I think maybe it was caused by the error "Cannot find a parent environment called Seurat".

> # Construct metacells in each group
> neuron <- MetacellsByGroups(
+   seurat_obj = neuron,
+   group.by = c("subclass", "orig.ident"),
+   k = 25,
+   ident.group = "subclass"
+ )

> # Normalize the metacell expression matrix
> neuron <- NormalizeMetacells(neuron)
Warning: Cannot find a parent environment called Seurat
Error: MultisessionFuture (future_lapply-5) failed to call gassign() on cluster RichSOCKnode #5 (PID 3524 on localhost ‘localhost’). The reason reported was ‘error writing to connection’. Post-mortem diagnostic: No process exists with this PID, i.e. the localhost worker is no longer alive. The total size of the 20 globals exported is 2.01 GiB. The three largest globals are ‘object’ (2.01 GiB of class ‘S4’), ‘as’ (228.67 KiB of class ‘function’) and ‘.asCoerceMethod’ (80.58 KiB of class ‘function’)

I will appreciate your reply!

**Comment by smorabit** [comment]
Hi,

I have no idea how it would use so much memory during normalization, I have never seen that before. Are you able to run `NormalizeData` on your seurat object or does that also use too much memory? The `NormalizeMetacells` function is literally just calling Seurat's `NormalizeData` function on the metacell expression matrix.

I don't really understand your warning about a parent environment, I would suggest starting from a vanilla R environment and just loading what you need rather than trying to use a parent environment. The error looks like it is coming from [future](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html), so it's an issue with parallel processing where some of the worker processes are have been killed. Sorry but I am not sure how to resolve this as I don't use any parallelization in this step.

**Comment by B-WingBreaker** [comment]
Hi Smorabit,

Thanks for your reply. 

I tried it several times later both on my PC and on the supercomputer. The `NormalizeData` from the original Seurat works fine for both in a minute, but the `NormalizeMetacells` function in hdWGCNA kept telling me the warning of  "Cannot find a parent environment called Seurat", and the memory requirement for the calculation went wild then. Also, thanks for your answer about the `future`. I think the workers were killed due to the massive assigned workload.

The "parent environment" issue could be related to [this page](https://rdrr.io/github/satijalab/seurat/src/R/utilities.R). The satijalab mentioned the parenting parameters. I don't know if there was a warning because I was using a child function modified from the parent Seurat environment.

**Comment by B-WingBreaker** [comment]
> Hi Smorabit,
> 
> Thanks for your reply.
> 
> I tried it several times later both on my PC and on the supercomputer. The `NormalizeData` from the original Seurat works fine for both in a minute, but the `NormalizeMetacells` function in hdWGCNA kept telling me the warning of "Cannot find a parent environment called Seurat", and the memory requirement for the calculation went wild then. Also, thanks for your answer about the `future`. I think the workers were killed due to the massive assigned workload.
> 
> The "parent environment" issue could be related to [this page](https://rdrr.io/github/satijalab/seurat/src/R/utilities.R). The satijalab mentioned the parenting parameters. I don't know if there was a warning because I was using a child function modified from the parent Seurat environment.

Here is the update. I killed the `future` paralleling process and the `NormalizeMetaCells` function started to work normally.

So, I guess the problem is with the parallelization. It is **not recommended to use parallelization** when doing the WGCNA analysis. 

Sorry for all the trouble. And thanks for fixing the "ScaleData()" issue for the harmonization. Good luck!
