### ISSUE TITLE
An error when running ModuleEigengenes().

### ISSUE THREAD

**Issue by GuanKX99** [smorabit/scWGCNA#161]
I encountered an error while running the ModuleEigengenes() using the tutorial data.
`# compute all MEs in the full single-cell dataset
seurat_obj <- ModuleEigengenes(
 seurat_obj,
 group.by.vars="Sample"
)`

And return errors.

`Error in RunHarmony.Seurat(seurat_obj, group.by.vars = group.by.vars, : argument 3 matches multiple formal arguments
Traceback:

1. ModuleEigengenes(seurat_obj, group.by.vars = "Sample")
2. ComputeModuleEigengene(seurat_obj = seurat_obj, cur_mod = cur_mod, 
 .     modules = modules, group.by.vars = group.by.vars, vars.to.regress = vars.to.regress, 
 .     scale.model.use = scale.model.use, verbose = verbose, pc_dim = pc_dim, 
 .     assay = assay, wgcna_name = wgcna_name, ...)
3. harmony::RunHarmony(seurat_obj, group.by.vars = group.by.vars, 
 .     reduction = "ME", verbose = verbose, assay.use = assay, ...)`

I noticed that both arguments start with "reduction" in source code of harmony:
`RunHarmony.Seurat <- function(
  object,
  group.by.vars,
  reduction.use = 'pca',
  dims.use = NULL,
  verbose = TRUE,
  reduction.save = "harmony",
  project.dim = TRUE,
  ...
)` 

But ModuleEigengenes() only transport `reduction = "ME"`.
Is this the source that caused the error?

This is my first time submitting a question, and I apologize for my poor English. Looking forward to your reply.

**Comment by xleizi** [comment]
The Harmony package was updated just six days ago, during which the parameter 'reduction' was changed to 'reduction.use'. From this experience, I've learned a valuable lesson: it is wise not to upgrade R packages indiscriminately!!!
It's advisable to use Harmony version 0.1.1 until the author fixes the existing bug. You can install it using the following command:
```
devtools::install_version("harmony", version = "0.1.1", repos = "http://cran.us.r-project.org")
```

**Comment by GuanKX99** [comment]
> The Harmony package was updated just six days ago, during which the parameter 'reduction' was changed to 'reduction.use'. From this experience, I've learned a valuable lesson: it is wise not to upgrade R packages indiscriminately!!! It's advisable to use Harmony version 0.1.1 until the author fixes the existing bug. You can install it using the following command:
> 
> ```
> devtools::install_version("harmony", version = "0.1.1", repos = "http://cran.us.r-project.org")
> ```

Thank you for your reply! 
I edited the code of `harmony::RunHarmony` temporarily instead. Hope the author fixes it.

**Comment by smorabit** [comment]
Hi,

Thanks for identifying this issue and thank you @xleizi for pointing out exactly what changed with the new version of Harmony! I updated hdWGCNA to now use `reduction.use` in the call to Harmony, and to require the new version of Harmony, so it should work if you update to the newest version of hdWGCNA.
