### ISSUE TITLE
how to interpret distance and inter / intra connectivity in HubGeneNetworkPlot

### ISSUE THREAD

**Issue by behyag** [smorabit/scWGCNA#162]
hi Sam, 
I have 3 related questions about how to interpret distance between nodes and inter / intra connectivity in HubGeneNetworkPlot?
Given that it uses force-directed graph algorithms, 
1. is it reasonable to say that closer modules in the network are more positively correlated and vice versa? 
2. also the interconnectivity of each module is dependent on its average kME values of its hub genes, right? 
for example in the network below, is it reasonable to say the turquoise, yellow and black modules are more correlated than e.g., blue and yellow are? also the red and green modules don't form close-knit hubs, meaning that the average kMEs are low, so they look more spread out, which is actually the case for my data. 
3. the ModuleCorrelogram in my data show that the blue and turquoise modules are negatively correlated, and in the network example below, they are plotted far from each other on opposite sides of the network. is it a reasonable interpretation? 
I'd really appreciate your thoughts on that. thank you so much! sorry about asking more than one Q per issue but they are related! 
![networkplot_20_10](https://github.com/smorabit/hdWGCNA/assets/58177477/ce8b9ce7-0c5e-44eb-8d77-73c22ba3f5b3)

**Comment by smorabit** [comment]
Hi,

It sounds like you are trying to qualitatively infer correlations between different modules by visually inspecting the hub gene network plot. I would advise against this, and alternatively you can compute pairwise correlations of the module eigengenes, like the module correlogram plot.

**Comment by behyag** [comment]
hi Sam, 
thank you for the reply! Actually I already calculated the pairwise correlations of the module eigengenes and plotted the correlogram. As you see in the Q3, I mentioned that the two modules (blue & turquoise) in the network are actually negatively correlated in the correlogram. I'm trying to somehow connect the two analyses (visualizations) logically. I understand that the in network, this could be complicated, meaning the two distant modules don't have to be negatively correlated but how about the the opposite, i.e., if the two modules are in fact negatively correlated, and also happen to be far apart in the network, then can we say the network plot confirms the correlogram (for the two modules)? 
thank you for your advice!

**Comment by smorabit** [comment]
> can we say the network plot confirms the correlogram

I do not advise interpreting distances in the hub gene network plot as correlations. It might be that correlated modules are next to each other in this particular graph but I do not think this is generalizable, and I don't see a point in making that conclusion anyways.

**Comment by behyag** [comment]
thanks a lot for your reply and clarification! but the shape of the modules, i.e, whether it is well-knit and condensed like the blue module or it's spread out like the green module is an indication of the average kME values, right?
