### ISSUE TITLE
Further visualization

### ISSUE THREAD

**Issue by awesomedeer** [smorabit/scWGCNA#166]
Dear Sam, @smorabit 
It's great that you developed this useful tool! It works well with my data although I am wondering whether I can plot customized figures without using default commands like `HubGeneNetworkPlot` and `ModuleUMAPPlot` or updated commands with more parameters to adjust.
In my case, I am interested in **1)** a specific module and **2)** several genes (some of them are not hub genes) in this module. I want to plot this module and highlight some of the genes.
Any suggestion? Or maybe I can extract the information from the network and plot using other softwares?

Best regards
Song

**Comment by awesomedeer** [comment]
Like Figure 5C in the manuscript which looks really good (their color combination seems a bit different with the default one).

**Comment by smorabit** [comment]
Hi Song, 

Glad that you are finding hdWGCNA useful in your work! You can definitely use other plottihng packages for customized plots. There can be a lot of problems when trying to plot networks, like showing too many edges or nodes can make the plot too busy to be easily interpretable. I would recommend trying out igraph or ggraph for plotting within R.
