### ISSUE TITLE
TestSoftPowers  get: Error in if (nGenes < 3) { : Argument is of length zero

### ISSUE THREAD

**Issue by TangentDeng** [smorabit/scWGCNA#170]
```
library(hdWGCNA)
library(WGCNA)
enableWGCNAThreads(nThreads = 0.75*parallel::detectCores()) 
Idents(sce) <- 'cluster'
DefaultAssay(sce) <- 'RNA'
sce <- SCTransform(sce,assay = 'RNA')
sce <- RunPCA(sce,assay = 'SCT')

seurat_obj <- SetupForWGCNA(
  sce,
  gene_select = "fraction"
  wgcna_name = "tutorial"
)

DefaultAssay(seurat_obj) <- 'RNA'
Idents(seurat_obj) <- 'cluster'
seurat_obj <- MetacellsByGroups(
  seurat_obj = sce,
wgcna_name = "tutorial",
  group.by = c("cluster",'batch')
  ident.group = "cluster",
  assay = 'RNA' 
  )

seurat_obj <- NormalizeMetacells(seurat_obj = seurat_obj,wgcna_name = "tutorial")

##Test different soft powers:-----------------
bicor <- WGCNA::bicor
networkType <- "signed hybrid"
corFnc <-  "bicor"
seurat_obj <- TestSoftPowers(
  seurat_obj, corFnc = corFnc,
  networkType = networkType # you can also use "unsigned" or "signed hybrid"
)
Error in if (nGenes < 3) { : Argument is of length zero
```
I run this in R 4.2 is OK but update to R 4.3.1 get error. Some package must be conflicted. 
Do any one know why?
Best!

**Comment by TangentDeng** [comment]
<html>
<body>


> session_info() ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────  setting  value  version  R version 4.3.1 (2023-06-16)  os       Ubuntu 22.04.1 LTS  system   x86_64, linux-gnu  ui       RStudio  language (EN)  collate  zh_CN.UTF-8  ctype    zh_CN.UTF-8  tz       Asia/Shanghai  date     2023-11-05  rstudio  2023.09.1+494 Desert Sunflower (server)  pandoc   3.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)  ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  package              * version   date (UTC) lib source  abind                  1.4-5     2016-07-21 [2] CRAN (R 4.2.1)  annotate               1.78.0    2023-04-25 [1] Bioconductor  AnnotationDbi        * 1.62.2    2023-07-02 [1] Bioconductor  ape                    5.7-1     2023-03-13 [1] CRAN (R 4.3.1)  aplot                  0.2.2     2023-10-06 [1] CRAN (R 4.3.1)  arrow                  13.0.0.1  2023-09-22 [1] CRAN (R 4.3.1)  assertthat             0.2.1     2019-03-21 [2] CRAN (R 4.2.1)  AUCell                 1.22.0    2023-04-25 [1] Bioconductor  backports              1.4.1     2021-12-13 [3] CRAN (R 4.1.2)  base64enc              0.1-3     2015-07-28 [2] CRAN (R 4.2.1)  beeswarm               0.4.0     2021-06-01 [1] CRAN (R 4.3.1)  Biobase              * 2.60.0    2023-04-25 [1] Bioconductor  BiocGenerics         * 0.46.0    2023-04-25 [1] Bioconductor  BiocManager            1.30.22   2023-08-08 [1] CRAN (R 4.3.1)  BiocNeighbors          1.18.0    2023-04-25 [1] Bioconductor  BiocParallel           1.34.2    2023-05-22 [1] Bioconductor  Biostrings             2.68.1    2023-05-16 [1] Bioconductor  bit                    4.0.5     2022-11-15 [1] CRAN (R 4.3.1)  bit64                  4.0.5     2020-08-30 [2] CRAN (R 4.2.1)  bitops                 1.0-7     2021-04-24 [2] CRAN (R 4.2.1)  blob                   1.2.4     2023-03-17 [1] CRAN (R 4.3.1)  broom                  1.0.5     2023-06-09 [1] CRAN (R 4.3.1)  cachem                 1.0.8     2023-05-01 [1] CRAN (R 4.3.1)  Cairo                  1.6-1     2023-08-18 [1] CRAN (R 4.3.1)  callr                  3.7.3     2022-11-02 [1] CRAN (R 4.3.1)  car                    3.1-2     2023-03-30 [1] CRAN (R 4.3.1)  carData                3.0-5     2022-01-06 [1] CRAN (R 4.3.1)  caTools                1.18.2    2021-03-28 [2] CRAN (R 4.2.1)  cellranger             1.1.0     2016-07-27 [1] CRAN (R 4.3.1)  checkmate              2.2.0     2023-04-27 [1] CRAN (R 4.3.1)  circlize               0.4.15    2022-05-10 [1] CRAN (R 4.3.1)  cli                    3.6.1     2023-03-23 [1] CRAN (R 4.3.1)  clue                   0.3-65    2023-09-23 [1] CRAN (R 4.3.1)  cluster                2.1.4     2022-08-22 [4] CRAN (R 4.2.1)  clusterProfiler      * 4.8.3     2023-08-31 [1] Bioconductor  codetools              0.2-19    2023-02-01 [1] CRAN (R 4.3.1)  colorspace           * 2.1-0     2023-01-23 [1] CRAN (R 4.3.1)  ComplexHeatmap         2.16.0    2023-04-25 [1] Bioconductor  COSG                 * 0.9.0     2023-10-31 [1] Github (genecell/COSGR@c8f3f53)  cowplot                1.1.1     2020-12-30 [2] CRAN (R 4.2.1)  crayon                 1.5.2     2022-09-29 [1] CRAN (R 4.3.1)  data.table           * 1.14.8    2023-02-17 [1] CRAN (R 4.3.1)  DBI                    1.1.3     2022-06-18 [1] CRAN (R 4.3.1)  DelayedArray           0.26.7    2023-07-28 [1] Bioconductor  DelayedMatrixStats     1.22.6    2023-08-28 [1] Bioconductor  deldir                 1.0-9     2023-05-17 [1] CRAN (R 4.3.1)  devtools             * 2.4.5     2022-10-11 [1] CRAN (R 4.3.1)  digest                 0.6.33    2023-07-07 [1] CRAN (R 4.3.1)  doParallel             1.0.17    2022-02-07 [1] CRAN (R 4.3.1)  DOSE                   3.26.2    2023-10-09 [1] Bioconductor  downloader             0.4       2015-07-09 [2] CRAN (R 4.2.1)  dplyr                * 1.1.3     2023-09-03 [1] CRAN (R 4.3.1)  DT                     0.30      2023-10-05 [1] CRAN (R 4.3.1)  dynamicTreeCut       * 1.63-1    2016-03-11 [1] CRAN (R 4.3.1)  ellipsis               0.3.2     2021-04-29 [2] CRAN (R 4.2.1)  enrichplot             1.20.3    2023-09-15 [1] Bioconductor  evaluate               0.22      2023-09-29 [1] CRAN (R 4.3.1)  fansi                  1.0.5     2023-10-08 [1] CRAN (R 4.3.1)  farver                 2.1.1     2022-07-06 [1] CRAN (R 4.3.1)  fastcluster          * 1.2.3     2021-05-24 [1] CRAN (R 4.3.1)  fastmap                1.1.1     2023-02-24 [1] CRAN (R 4.3.1)  fastmatch              1.1-4     2023-08-18 [1] CRAN (R 4.3.1)  fgsea                  1.26.0    2023-04-25 [1] Bioconductor  fitdistrplus           1.1-11    2023-04-25 [1] CRAN (R 4.3.1)  FNN                    1.1.3.2   2023-03-20 [1] CRAN (R 4.3.1)  forcats              * 1.0.0     2023-01-29 [1] CRAN (R 4.3.1)  foreach                1.5.2     2022-02-02 [3] CRAN (R 4.1.2)  foreign                0.8-85    2023-09-09 [1] CRAN (R 4.3.1)  Formula                1.2-5     2023-02-24 [1] CRAN (R 4.3.1)  fs                     1.6.3     2023-07-20 [1] CRAN (R 4.3.1)  future               * 1.33.0    2023-07-01 [1] CRAN (R 4.3.1)  future.apply           1.11.0    2023-05-21 [1] CRAN (R 4.3.1)  generics               0.1.3     2022-07-05 [1] CRAN (R 4.3.1)  GenomeInfoDb           1.36.4    2023-10-02 [1] Bioconductor  GenomeInfoDbData       1.2.10    2023-10-18 [1] Bioconductor  GenomicRanges          1.52.1    2023-10-08 [1] Bioconductor  GetoptLong             1.0.5     2020-12-15 [1] CRAN (R 4.3.1)  ggbeeswarm             0.7.2     2023-04-29 [1] CRAN (R 4.3.1)  ggdendro               0.1.23    2022-02-16 [1] CRAN (R 4.3.1)  ggforce                0.4.1     2022-10-04 [1] CRAN (R 4.3.1)  ggfun                  0.1.3     2023-09-15 [1] CRAN (R 4.3.1)  ggplot2              * 3.4.4     2023-10-12 [1] CRAN (R 4.3.1)  ggplotify              0.1.2     2023-08-09 [1] CRAN (R 4.3.1)  ggprism                1.0.4     2022-11-04 [1] CRAN (R 4.3.1)  ggpubr                 0.6.0     2023-02-10 [1] CRAN (R 4.3.1)  ggraph                 2.1.0     2022-10-09 [1] CRAN (R 4.3.1)  ggrastr                1.0.2     2023-06-01 [1] CRAN (R 4.3.1)  ggrepel                0.9.4     2023-10-13 [1] CRAN (R 4.3.1)  ggridges               0.5.4     2022-09-26 [2] CRAN (R 4.2.1)  ggsci                  3.0.0     2023-03-08 [1] CRAN (R 4.3.1)  ggsignif               0.6.4     2022-10-13 [1] CRAN (R 4.3.1)  ggtree                 3.8.2     2023-07-24 [1] Bioconductor  ggvenn               * 0.1.10    2023-03-31 [1] CRAN (R 4.3.1)  ggVennDiagram        * 1.2.3     2023-08-14 [1] CRAN (R 4.3.1)  GlobalOptions          0.1.2     2020-06-10 [1] CRAN (R 4.3.1)  globals                0.16.2    2022-11-21 [1] CRAN (R 4.3.1)  glue                   1.6.2     2022-02-24 [1] CRAN (R 4.3.1)  GO.db                  3.17.0    2023-10-18 [1] Bioconductor  goftest                1.2-3     2021-10-07 [2] CRAN (R 4.2.1)  GOSemSim               2.26.1    2023-07-10 [1] Bioconductor  gplots                 3.1.3     2022-04-25 [1] CRAN (R 4.3.1)  graph                  1.78.0    2023-04-25 [1] Bioconductor  graphlayouts           1.0.1     2023-09-19 [1] CRAN (R 4.3.1)  gridBase               0.4-7     2014-02-24 [1] CRAN (R 4.3.1)  gridExtra              2.3       2017-09-09 [2] CRAN (R 4.2.1)  gridGraphics           0.5-1     2020-12-13 [2] CRAN (R 4.2.1)  GSEABase               1.62.0    2023-04-25 [1] Bioconductor  gson                   0.1.0     2023-03-07 [1] CRAN (R 4.3.1)  gtable                 0.3.4     2023-08-21 [1] CRAN (R 4.3.1)  gtools                 3.9.4     2022-11-27 [1] CRAN (R 4.3.1)  harmony              * 1.0.3     2023-09-30 [1] CRAN (R 4.3.1)  hdf5r                  1.3.8     2023-01-21 [1] CRAN (R 4.3.1)  HDO.db                 0.99.1    2023-10-18 [1] Bioconductor  hdWGCNA              * 0.2.24    2023-10-22 [1] local (/home/dengzhen/Downloads/package/hdWGCNA-dev.zip)  Hmisc                  5.1-1     2023-09-12 [1] CRAN (R 4.3.1)  hms                    1.1.3     2023-03-21 [1] CRAN (R 4.3.1)  htmlTable              2.4.1     2022-07-07 [1] CRAN (R 4.3.1)  htmltools              0.5.6.1   2023-10-06 [1] CRAN (R 4.3.1)  htmlwidgets            1.6.2     2023-03-17 [1] CRAN (R 4.3.1)  httpuv                 1.6.11    2023-05-11 [1] CRAN (R 4.3.1)  httr                   1.4.7     2023-08-15 [1] CRAN (R 4.3.1)  ica                    1.0-3     2022-07-08 [2] CRAN (R 4.2.1)  igraph                 1.5.1     2023-08-10 [1] CRAN (R 4.3.1)  impute                 1.74.1    2023-05-02 [1] Bioconductor  IRanges              * 2.34.1    2023-06-22 [1] Bioconductor  irlba                  2.3.5.1   2022-10-03 [2] CRAN (R 4.2.1)  iterators              1.0.14    2022-02-05 [3] CRAN (R 4.1.2)  janitor                2.2.0     2023-02-02 [1] CRAN (R 4.3.1)  jsonlite               1.8.7     2023-06-29 [1] CRAN (R 4.3.1)  KEGGREST               1.40.1    2023-09-29 [1] Bioconductor  KernSmooth             2.23-22   2023-07-10 [1] CRAN (R 4.3.1)  knitr                  1.44      2023-09-11 [1] CRAN (R 4.3.1)  ks                     1.14.1    2023-08-10 [1] CRAN (R 4.3.1)  labeling               0.4.3     2023-08-29 [1] CRAN (R 4.3.1)  later                  1.3.1     2023-05-02 [1] CRAN (R 4.3.1)  lattice                0.21-9    2023-10-01 [1] CRAN (R 4.3.1)  lazyeval               0.2.2     2019-03-15 [2] CRAN (R 4.2.1)  leiden                 0.4.3     2022-09-10 [2] CRAN (R 4.2.1)  lifecycle              1.0.3     2022-10-07 [1] CRAN (R 4.3.1)  limma                  3.56.2    2023-06-04 [1] Bioconductor  listenv                0.9.0     2022-12-16 [1] CRAN (R 4.3.1)  lmtest                 0.9-40    2022-03-21 [2] CRAN (R 4.2.1)  lubridate            * 1.9.3     2023-09-27 [1] CRAN (R 4.3.1)  magick                 2.8.1     2023-10-22 [1] CRAN (R 4.3.1)  magrittr               2.0.3     2022-03-30 [1] CRAN (R 4.3.1)  MASS                   7.3-60    2023-05-04 [1] CRAN (R 4.3.1)  Matrix                 1.6-1.1   2023-09-18 [1] CRAN (R 4.3.1)  MatrixGenerics         1.12.3    2023-07-30 [1] Bioconductor  matrixStats            1.0.0     2023-06-02 [1] CRAN (R 4.3.1)  mclust                 6.0.0     2022-10-31 [1] CRAN (R 4.3.1)  memoise                2.0.1     2021-11-26 [2] CRAN (R 4.2.1)  mime                   0.12      2021-09-28 [2] CRAN (R 4.2.1)  miniUI                 0.1.1.1   2018-05-18 [2] CRAN (R 4.2.1)  munsell                0.5.0     2018-06-12 [2] CRAN (R 4.2.1)  mvtnorm                1.2-3     2023-08-25 [1] CRAN (R 4.3.1)  Nebulosa               1.10.0    2023-04-25 [1] Bioconductor  nlme                   3.1-163   2023-08-09 [1] CRAN (R 4.3.1)  NMF                    0.26      2023-03-20 [1] CRAN (R 4.3.1)  nnet                   7.3-19    2023-05-03 [1] CRAN (R 4.3.1)  org.Mm.eg.db         * 3.17.0    2023-10-28 [1] Bioconductor  paletteer              1.5.0     2022-10-19 [1] CRAN (R 4.3.1)  parallelly             1.36.0    2023-05-26 [1] CRAN (R 4.3.1)  patchwork            * 1.1.3     2023-08-14 [1] CRAN (R 4.3.1)  pbapply                1.7-2     2023-06-27 [1] CRAN (R 4.3.1)  pheatmap             * 1.0.12    2019-01-04 [1] CRAN (R 4.3.1)  pillar                 1.9.0     2023-03-22 [1] CRAN (R 4.3.1)  pkgbuild               1.4.2     2023-06-26 [1] CRAN (R 4.3.1)  pkgconfig              2.0.3     2019-09-22 [2] CRAN (R 4.2.1)  pkgload                1.3.3     2023-09-22 [1] CRAN (R 4.3.1)  plotly                 4.10.2    2023-06-03 [1] CRAN (R 4.3.1)  plyr                   1.8.9     2023-10-02 [1] CRAN (R 4.3.1)  png                    0.1-8     2022-11-29 [1] CRAN (R 4.3.1)  polyclip               1.10-6    2023-09-27 [1] CRAN (R 4.3.1)  pracma                 2.4.2     2022-09-22 [1] CRAN (R 4.3.1)  preprocessCore         1.62.1    2023-05-02 [1] Bioconductor  prettyunits            1.2.0     2023-09-24 [1] CRAN (R 4.3.1)  processx               3.8.2     2023-06-30 [1] CRAN (R 4.3.1)  profvis                0.3.8     2023-05-02 [1] CRAN (R 4.3.1)  progressr              0.14.0    2023-08-10 [1] CRAN (R 4.3.1)  promises               1.2.1     2023-08-10 [1] CRAN (R 4.3.1)  proxyC                 0.3.4     2023-10-25 [1] CRAN (R 4.3.1)  ps                     1.7.5     2023-04-18 [1] CRAN (R 4.3.1)  purrr                * 1.0.2     2023-08-10 [1] CRAN (R 4.3.1)  qvalue                 2.32.0    2023-04-25 [1] Bioconductor  R.methodsS3            1.8.2     2022-06-13 [2] CRAN (R 4.2.1)  R.oo                   1.25.0    2022-06-12 [2] CRAN (R 4.2.1)  R.utils                2.12.2    2022-11-11 [1] CRAN (R 4.3.1)  R6                     2.5.1     2021-08-19 [2] CRAN (R 4.2.1)  RANN                   2.6.1     2019-01-08 [2] CRAN (R 4.2.1)  RcisTarget           * 1.20.0    2023-04-25 [1] Bioconductor  RColorBrewer           1.1-3     2022-04-03 [1] CRAN (R 4.3.1)  Rcpp                 * 1.0.11    2023-07-06 [1] CRAN (R 4.3.1)  RcppAnnoy              0.0.21    2023-07-02 [1] CRAN (R 4.3.1)  RcppParallel           5.1.7     2023-02-27 [1] CRAN (R 4.3.1)  RCurl                  1.98-1.12 2023-03-27 [1] CRAN (R 4.3.1)  readr                * 2.1.4     2023-02-10 [1] CRAN (R 4.3.1)  readxl                 1.4.3     2023-07-06 [1] CRAN (R 4.3.1)  registry               0.5-1     2019-03-05 [1] CRAN (R 4.3.1)  rematch2               2.1.2     2020-05-01 [3] CRAN (R 4.0.1)  remotes                2.4.2.1   2023-07-18 [1] CRAN (R 4.3.1)  reshape2               1.4.4     2020-04-09 [2] CRAN (R 4.2.1)  reticulate             1.34.0    2023-10-12 [1] CRAN (R 4.3.1)  rjson                  0.2.21    2022-01-09 [1] CRAN (R 4.3.1)  rlang                  1.1.1     2023-04-28 [1] CRAN (R 4.3.1)  rmarkdown              2.25      2023-09-18 [1] CRAN (R 4.3.1)  rngtools               1.5.2     2021-09-20 [1] CRAN (R 4.3.1)  ROCR                   1.0-11    2020-05-02 [2] CRAN (R 4.2.1)  rpart                  4.1.21    2023-10-09 [1] CRAN (R 4.3.1)  RSQLite                2.3.1     2023-04-03 [1] CRAN (R 4.3.1)  rstatix                0.7.2     2023-02-01 [1] CRAN (R 4.3.1)  rstudioapi             0.15.0    2023-07-07 [1] CRAN (R 4.3.1)  Rtsne                  0.16      2022-04-17 [2] CRAN (R 4.2.1)  RVenn                  1.1.0     2019-07-18 [1] CRAN (R 4.3.1)  S4Arrays               1.0.6     2023-08-30 [1] Bioconductor  S4Vectors            * 0.38.2    2023-09-22 [1] Bioconductor  scales                 1.2.1     2022-08-20 [1] CRAN (R 4.3.1)  scattermore            1.2       2023-06-12 [1] CRAN (R 4.3.1)  scatterpie             0.2.1     2023-06-07 [1] CRAN (R 4.3.1)  scCustomize          * 1.1.3     2023-07-19 [1] CRAN (R 4.3.1)  SCENIC               * 1.3.1     2023-10-19 [1] local (/home/dengzhen/Downloads/package/SCENIC-master)  SCopeLoomR           * 0.13.0    2023-10-18 [1] Github (aertslab/SCopeLoomR@20f4e0a)  scRNAtoolVis         * 0.0.7     2023-11-01 [1] Github (junjunlab/scRNAtoolVis@54e7a9c)  sctransform          * 0.4.0     2023-09-19 [1] CRAN (R 4.3.1)  sessioninfo            1.2.2     2021-12-06 [1] CRAN (R 4.3.1)  Seurat               * 4.4.0     2023-09-28 [1] CRAN (R 4.3.1)  SeuratObject         * 4.1.4     2023-09-26 [1] CRAN (R 4.3.1)  shadowtext             0.1.2     2022-04-22 [2] CRAN (R 4.2.1)  shape                  1.4.6     2021-05-19 [1] CRAN (R 4.3.1)  shiny                  1.7.5.1   2023-10-14 [1] CRAN (R 4.3.1)  SingleCellExperiment   1.22.0    2023-04-25 [1] Bioconductor  snakecase              0.11.1    2023-08-27 [1] CRAN (R 4.3.1)  sp                     2.1-1     2023-10-16 [1] CRAN (R 4.3.1)  sparseMatrixStats      1.12.2    2023-07-02 [1] Bioconductor  spatstat.data          3.0-1     2023-03-12 [1] CRAN (R 4.3.1)  spatstat.explore       3.2-3     2023-09-07 [1] CRAN (R 4.3.1)  spatstat.geom          3.2-5     2023-09-05 [1] CRAN (R 4.3.1)  spatstat.random        3.1-6     2023-09-09 [1] CRAN (R 4.3.1)  spatstat.sparse        3.0-2     2023-06-25 [1] CRAN (R 4.3.1)  spatstat.utils         3.0-3     2023-05-09 [1] CRAN (R 4.3.1)  stringi                1.7.12    2023-01-11 [1] CRAN (R 4.3.1)  stringr              * 1.5.0     2022-12-02 [1] CRAN (R 4.3.1)  SummarizedExperiment   1.30.2    2023-06-06 [1] Bioconductor  survival               3.5-7     2023-08-14 [1] CRAN (R 4.3.1)  tensor                 1.5       2012-05-05 [2] CRAN (R 4.2.1)  tester                 0.1.7     2013-11-14 [1] CRAN (R 4.3.1)  tibble               * 3.2.1     2023-03-20 [1] CRAN (R 4.3.1)  tidygraph              1.2.3     2023-02-01 [1] CRAN (R 4.3.1)  tidyr                * 1.3.0     2023-01-24 [1] CRAN (R 4.3.1)  tidyselect             1.2.0     2022-10-10 [1] CRAN (R 4.3.1)  tidytree               0.4.5     2023-08-10 [1] CRAN (R 4.3.1)  tidyverse            * 2.0.0     2023-02-22 [1] CRAN (R 4.3.1)  timechange             0.2.0     2023-01-11 [1] CRAN (R 4.3.1)  treeio                 1.24.3    2023-07-24 [1] Bioconductor  tweenr                 2.0.2     2022-09-06 [2] CRAN (R 4.2.1)  tzdb                   0.4.0     2023-05-12 [1] CRAN (R 4.3.1)  UCell                * 2.4.0     2023-04-25 [1] Bioconductor  urlchecker             1.0.1     2021-11-30 [1] CRAN (R 4.3.1)  usethis              * 2.2.2     2023-07-06 [1] CRAN (R 4.3.1)  utf8                   1.2.3     2023-01-31 [1] CRAN (R 4.3.1)  uwot                   0.1.16    2023-06-29 [1] CRAN (R 4.3.1)  vctrs                  0.6.4     2023-10-12 [1] CRAN (R 4.3.1)  vipor                  0.4.5     2017-03-22 [1] CRAN (R 4.3.1)  viridis              * 0.6.4     2023-07-22 [1] CRAN (R 4.3.1)  viridisLite          * 0.4.2     2023-05-02 [1] CRAN (R 4.3.1)  WGCNA                * 1.72-1    2023-01-18 [1] CRAN (R 4.3.1)  withr                  2.5.1     2023-09-26 [1] CRAN (R 4.3.1)  xfun                   0.40      2023-08-09 [1] CRAN (R 4.3.1)  XML                    3.99-0.14 2023-03-19 [1] CRAN (R 4.3.1)  xtable                 1.8-4     2019-04-21 [2] CRAN (R 4.2.1)  XVector                0.40.0    2023-04-25 [1] Bioconductor  yulab.utils            0.1.0     2023-09-20 [1] CRAN (R 4.3.1)  zlibbioc               1.46.0    2023-04-25 [1] Bioconductor  zoo                    1.8-12    2023-04-13 [1] CRAN (R 4.3.1)   [1] /home/dengzhen/R/x86_64-pc-linux-gnu-library/4.3  [2] /usr/local/lib/R/site-library  [3] /usr/lib/R/site-library  [4] /usr/lib/R/library  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
--
 
> | >
>


</body>
</html>

**Comment by smorabit** [comment]
Hi, it looks like you have forgotten to run the SetDatExpr function. Please consult [this tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html#co-expression-network-analysis) to see the suggested steps for running hdWGCNA.
