### ISSUE TITLE
How to control fusion of similar modules? 

### ISSUE THREAD

**Issue by Dimmiso** [smorabit/scWGCNA#171]
Hi,

thanks for keeping developing & supporting a great package hdWGCNA. 

Can you, please, help setting up parameters to keep similar modules from fusing together? Plot below shows identified modules. It looks great: even small branches of dendrogram detected as modules (green curly parentheses). But some groups of identified modules were most probably fused together (red curly parentheses: pink, red and dark-red modules). I would like to split these three modules into their "sub-modules", corresponded to different branches of dendrogram. I played a bit with parameters. The plot shows eight parameters variants which I used. As you see, I keep deepSplit on maximum, 4. DetectCutHeight I keep 0.995. I also useed higher values (up to 0.999) but the outcome was exactly the same (not shown).

I am not sure what is interplay between and parameters effect on blockwiseConsensusModules
, mergeCloseModules and cutreeDynamic (or may be other commands), but I reasoned that mergeCloseModules fuses modules after they were identified and I would like to control this fusion. So, I played with parameters cutHeight and consesnsusQuantile of mergeCloseModules, but this, as one can see, had no difference (parameters are written above each color bar representing modules). Do you have any tip how I can try split red, pink and dark-red modules?

Thanks a lot, Sam!
Best, 
Dmitry

![bild](https://github.com/smorabit/hdWGCNA/assets/45941025/5c0e034f-ad8b-4fe3-9741-33b8945656d6)

**Comment by smorabit** [comment]
This is a good question, but I am not sure if I can suggest parameters off the top of my head that will help you split these modules. I have encountered similar situations in the past where I have to run a nested for loop to perform a parameter space exploration and then select a set of modules out of those results. However, unfortunately this process can be tedious and time consuming. The parameters that you mentioned were the ones that I would have suggested playing with so I don't have much advice to give if you still are unable to split the modules. Maybe the modules are too small and are not meeting the minimum size?

**Comment by Dimmiso** [comment]
Thanks a lot, Sam, for detailed comments! I at least know now that have not missed some simple and easy solution! Thanks for supporting hdWGCNA! Best!
