### ISSUE TITLE
How to fix "Error in getClassDef(x@superClass, package = packageSlot(x))@virtual :    no applicable method for `@` applied to an object of class "NULL" "

### ISSUE THREAD

**Issue by danL9018** [smorabit/scWGCNA#172]
when Construct metacells
Run the code and showed the Error in getClassDef(x@superClass, package = packageSlot(x))@virtual : 
  no applicable method for `@` applied to an object of class "NULL"

**Steps to reproduce**
the code I used "WratVF1 <- MetacellsByGroups(WratVF1, group.by =c("celltype"), reduction = "pca", k = 25, max_shared = 10, min_cells = 30, ident.group = "celltype", cells.use = NULL ) " to generate the error. The code to setup for WGCNA "WratVF1  <- SetupForWGCNA(WratVF1, gene_select = "fraction", fraction = 0.05, wgcna_name = "ratVF hdWGCNA", group.by = "celltype")". The data set I used is a scRNA-seq data set of SD rat larynx.

```
p <- DimPlot(WratVF1 , group.by='celltype', label=TRUE) +
  umap_theme() + ggtitle('rat VF') + NoLegend()

p

WratVF1  <- SetupForWGCNA(WratVF1, gene_select = "fraction", fraction = 0.05, wgcna_name = "ratVF hdWGCNA", group.by = "celltype")
WratVF1 <- MetacellsByGroups(WratVF1, group.by =c("celltype"), reduction = "pca", k = 25, max_shared = 10, min_cells = 30, ident.group = "celltype", cells.use = NULL ) 
```

**R session info**
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

**Screenshots**
![微信图片_20231112214654](https://github.com/smorabit/hdWGCNA/assets/150597519/4b19915b-8bc7-49ba-a304-b7682b92f895)

**More than one problem?** 
If you have more than one problem with hdWGCNA, create separate issues for your individual problems.

**Comment by smorabit** [comment]
Hi, 

Thank you for using hdWGCNA and for sharing your issue. I have not personally come across this issue before. Are you able to reproduce this error on the tutorial dataset or does this only happen on your dataset?

**Comment by Ldec12** [comment]
Hi
I met the same error as well, I changed the version of the Matrix package to 1.6.1.1, and re-installed SeuratObject.
it works well now.

**Comment by danL9018** [comment]
Thanks a lot! I have renewed the version of Matrix, Seurat and SeuratObject.
















在 2023-11-16 11:55:52，"Ldec12" ***@***.***> 写道：

Hi
I met the same error as well, I changed the version of the Matrix package to 1.6.1.1, and re-installed SeuratObject.
it works well now.
