### ISSUE TITLE
How to specify species as rat in EnrichR analysis

### ISSUE THREAD

**Issue by Ldec12** [smorabit/scWGCNA#175]
Hi
 Your R package is excellent. I have a question. I'm using rat single-cell sequencing data. How can I specify the species as rat in the EnrichR analysis?
 I appreciate your help.

**Comment by smorabit** [comment]
Hi, I do not personally have fly data to test this with but I believe that you can run this code:

```
library(enrichR)

# change the enrichR database
setEnrichrSite("FlyEnrichr")
```

Then you can run the hdWGCNA function `RunEnrichr`.  Keep in mind that the databases that you include must be part of  FlyEnrichr, you can [check the list of valid databases here](https://maayanlab.cloud/FlyEnrichr/#stats).

**Comment by smorabit** [comment]
Sorry I just realized that you were talking about rat, not fly. It looks like EnrichR does not have a database for Rat. In that case, you will have to convert your gene names to their human orthologs before running EnrichR. You can get the ortholog information from [BioMart](https://www.ensembl.org/info/data/biomart/index.html).
