### ISSUE TITLE
SetDataExpr Error

### ISSUE THREAD

**Issue by vasikara17** [smorabit/scWGCNA#178]
Hello, 
I have a question regarding SetDataExpr function.
I run :
**###Set up the expression matrix
seurat_obj <- SetDatExpr(
  seurat_obj,
  group_name = "Adipocytes_2", # the name of the group of interest in the group.by column
  group.by='seurat_clusters', # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups
  assay = 'RNA', # using RNA assay
  slot = 'data' # using normalized data
)**

**Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Run `rlang::last_trace()` to see where the error occurred.**

Does this have to do with the Seurat version I am using?
Best wishes,
Vasiliki

**Comment by smorabit** [comment]
Yes this is a Seurat v5 related issue. We have not yet updated hdWGCNA to work with Seurat 5 so please use Seurat 4 for now.
