### ISSUE TITLE
Question about network construction strategies 

### ISSUE THREAD

**Issue by YenTrangHoang** [smorabit/scWGCNA#180]
Hello, 

I have a large Seurat object which includes 1x control, 2x genotype A and 1x genotype B datasets. I'm specifically interested in differences between my control and the different genotypes. 

My question is:
Does it make a difference in network construction and module identification when I subset my Seurat object (e.g. smaller object containing 1x control and 1x genotype A) before running hdWGCNA or start the hdWGCNA pipeline with the entire dataset and then specificy my dataset and population of interest at the SetDatExpr() step like here: SetDatExpr(seurat_obj, 
                                      group_name = "INH",
                                       group.by = "cell_type",
                                      multi.group.by = "genotype",
                                      multi_group_name = c("control", "genotype A")) 

Can I still perform Differential Module Eigengene Analysis with both strategies? 

Thank you very much!

**Comment by smorabit** [comment]
Hi, thanks for your question.

> Does it make a difference in network construction and module identification when I subset my Seurat object

No, it would not make a difference in the network construction or the module identification. However, it would make a difference when you run the `ModuleEigengenes` function, which computes gene expression signatures for all the cells in the whole Seurat object. 

> Can I still perform Differential Module Eigengene Analysis with both strategies?

Yes you can.
