### ISSUE TITLE
could not find function "ConstructPseudobulk"

### ISSUE THREAD

**Issue by venkan** [smorabit/scWGCNA#181]
I'm trying to use `hdWGCNA` on Psuedobulk for Co-expression network analysis.

When I tried to use this, I got an ERROR:

<img width="1054" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/11817153/eb3ea5a8-106c-49ca-b732-470427f871f9">

I loaded `hdWCNA`, but why do I have this error? What could be the issue?

**Comment by smorabit** [comment]
Hi, are you using the latest version of hdWGCNA?

**Comment by venkan** [comment]
Hi @smorabit Thank you for your reply. I'm using `hdWGCNA_0.2.19`

**Comment by smorabit** [comment]
The `ConstructPseudobulk` function was not included in that version so please update to the newest version.

**Comment by venkan** [comment]
Sure. Is `v0.1.1` the new version?

I installed the new version from here https://github.com/smorabit/hdWGCNA/releases 

`hdWGCNA_0.1.1.9006`

But I still have the same Error:

<img width="1139" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/11817153/d529b609-5ecc-4636-81c5-38ddad293830">

**Comment by smorabit** [comment]
Please install the newest version of hdWGCNA using the [installation instructions on the package homepage](https://smorabit.github.io/hdWGCNA/index.html#installation).

**Comment by venkan** [comment]
But if I use this for `hdWGCNA`

`devtools::[install_github](https://devtools.r-lib.org/reference/remote-reexports.html)('smorabit/hdWGCNA', ref='dev')`

I get  `hdWGCNA_0.2.19`. Is this the new version?

**Comment by venkan** [comment]
I installed the new version from here `https://github.com/smorabit/hdWGCNA/releases`

This is the `sessionInfo()`

<img width="611" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/11817153/ba783aaf-f03f-4c09-8a9f-b73ad66fddde">

**Comment by smorabit** [comment]
The latest version should be `0.2.25`. I just tried on my machine to install it with the recommended instructions:

`devtools::install_github('smorabit/hdWGCNA', ref='dev')`

And then when I load it in and check the package version:

```
library(hdWGCNA)
packageVersion('hdWGCNA')
[1] ‘0.2.25’
```

I don't understand how you are getting `0.2.19`?

**Comment by venkan** [comment]
Okay As you said I installed the new version `0.2.25`. It is working now. Thank you !!
