### ISSUE TITLE
Requirements ggforestplot and ggrepel not specified

### ISSUE THREAD

**Issue by DelongZHOU** [smorabit/scWGCNA#183]
Hello,

When running "Differential module eigengene" I realized that two required packages are not imply

[PlotDMEsLollipop](https://smorabit.github.io/hdWGCNA/reference/PlotDMEsLollipop.html) requires ggforestplot, while [PlotDMEsVolcano](https://smorabit.github.io/hdWGCNA/reference/PlotDMEsVolcano.html) requires ggrepel.

BTW I found in the source code a section to install and load ggforestplot (although didn't work for me bc I was using a setup without internet connection), but ggrepel has to be manually loaded.

I think you might want to include these two in the install page.
Best,

**Comment by smorabit** [comment]
Thank you for the suggestion, I have added this into the installation instructions.
