### ISSUE TITLE
EnrichrBarPlot bar / text color

### ISSUE THREAD

**Issue by DelongZHOU** [smorabit/scWGCNA#184]
Hello,

I see in the code that EnrichrBarPlot automatically fetch the color of the module and use that to plot the enriched terms, and if the module is black then the text should be grey. Except it's not working for me:
![enriched terms](https://github.com/smorabit/hdWGCNA/assets/56367172/ace9dd3b-050f-446a-8674-4461310abffb)

Would it be possible to turn off the color matching and use uniformed color?

Thank you!

**Comment by smorabit** [comment]
Hi,

I updated this function to have two new options, `plot_bar_color` and `plot_text_color` so you can make all of the plots have a uniform color as you suggested.
