### ISSUE TITLE
How to get the adjacency matrix using hdWGCNA?

### ISSUE THREAD

**Issue by venkan** [smorabit/scWGCNA#187]
Usually in `WGCNA` we can get the adjacency matrix like the below:

`adj= adjacency(datExpr,type = "unsigned", power = softPower);`

How adjacency matrix can be created from scRNA using hdWGCNA?

**Comment by smorabit** [comment]
Have you tried something like this:

```
datExpr <- GetDatExpr(seurat_obj)
softPower <- 6 # change this to whatever is appropriate for your dataset!
adj <-  WGCNA::adjacency(datExpr,type = "unsigned", power = softPower);
```

**Comment by venkan** [comment]
yes, this worked. Thank you !!
