### ISSUE TITLE
Question about [SetDatExpr() error]

### ISSUE THREAD

**Issue by lisp-0326** [smorabit/scWGCNA#188]
**SetDatExpr() error** 
Hi, When I run hdWGNA, using the sample data（Zhou_2020.rds）, I always get an error when reaching this SetDatExpr() function. 
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.

I want to know how to solve

seurat_obj <- SetDatExpr(

  seurat_obj,

  group_name = "INH", # the name of the group of interest in the group.by column

  group.by='cell_type', # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups

  assay = 'RNA', # using RNA assay

  slot = 'data' # using normalized data
)

**Comment by venkan** [comment]
Hello, 

Looks like you working with `Seurat v5`. Better use Seurat v4.3.0 you won't be having this error.
