### ISSUE TITLE
Load a previously generated TOM into a seurat object via the TOM.rda file?

### ISSUE THREAD

**Issue by rdalbanus** [smorabit/scWGCNA#189]
I've been very excited about using this package since Dr. Swarup mentioned your work-in-progress in a talk a while back. Thank you for putting it out!

The question title says everything - I had a session that crashed on me, and I'm wondering if there's a way to load an existing TOM file into a Seurat object (i.e., skip the `ConstructNetwork` step). If not, I'm curious about why the TOM is saved to disk besides saving memory. 

I hope I didn't miss anything obvious in the documentation.

Cheers

**Comment by smorabit** [comment]
Hi,

If your session crashed before you could save it, I would suggest simply running it again. 

> I'm curious about why the TOM is saved to disk besides saving memory.

The reason is just to save memory. The TOM is loaded back into memory for certain functions when it is needed.

**Comment by rdalbanus** [comment]
Thanks for the quick reply and clarification! You might consider adding this functionality for situations where one calculates a TOM on a subset of the data (e.g. controls) and applies it to the rest (e.g. cases). I don't think there's a way to do this right now without manually populating the `@misc` slot with the data of interest.

**Comment by smorabit** [comment]
> You might consider adding this functionality for situations where one calculates a TOM on a subset of the data (e.g. controls) and applies it to the rest (e.g. cases). 

This is already possible with hdWGCNA if you tell `SetDatExpr` to only use the controls. In the future, please only discuss a single issue (or closely related topics) in a GitHub issue so the information is better organized for other users! Happy to elaborate if you want to open a new issue about it.
