### ISSUE TITLE
Cannot find the `PlotKMEs()` function

### ISSUE THREAD

**Issue by B-WingBreaker** [smorabit/scWGCNA#19]
Hi,

Sorry, it is just a simple problem, that I cannot find the `PlotKMEs()` function. 

The error looks like this:

> Error in PlotKMEs(neuron, ncol = 5) : could not find function "PlotKMEs"

I saw this function in the tutorial, but I could not call it in R. Can you please answer this?

Thank you.

**Comment by smorabit** [comment]
Hi,

Could you try updating to the most recent version of  hdWGCNA, and then try to run `PlotKMEs`?

```
devtools::install_github('smorabit/hdWGCNA', ref='dev')
library(hdWGCNA)

```

**Comment by B-WingBreaker** [comment]
Yes, I did. But still it seemed that `PlotKMEs` function was not found in the hdWGCNA package. 
No warning or error occurred during the installation.
I tried on two different terminals, and neither could find the function.
Could you please fix this problem?

**Comment by smorabit** [comment]
When I install the latest version of hdWGCNA, the PlotKMEs function is there, so I am not sure why it would be missing in your case. You can see it's included in the docs on the website [here](https://smorabit.github.io/hdWGCNA/reference/PlotKMEs.html).

Does `PlotKMEs` show up when you run this: `lsf.str("package:hdWGCNA")`

**Comment by B-WingBreaker** [comment]
The problem was solved after I reinstalled all the additional packages required in the hdWGCNA.

Thank you very much for your help!
