### ISSUE TITLE
Drawing problem about hdWGCNA

### ISSUE THREAD

**Issue by rraky** [smorabit/scWGCNA#190]
Hello, I would like to obtain an image depicting a co-expression network for a specific group of cells.
<img width="211" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/137071048/9762f664-0c48-4eb8-b00b-59782a4c8ad1">

However, I can only obtain a different type of image.
<img width="500" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/137071048/06a0349f-44f3-4683-a1f2-0d523b215125">

How can I achieve the first type of image?

The first image is from the article titled "Cardiac fibroblasts regulate the development of heart failure via Htra3-TGF-β-IGFBP7 axis."

**Comment by smorabit** [comment]
Hi, I checked the article that you referred to. It does not look like they used hdWGCNA in their paper. From the methods section:

> To visualize the weighted co-expression networks, Cytoscape (version 3.7.2) with “edge-weighted force-directed” was used.

If you want to make this visualization I recommend reading the methods section of that paper to reproduce their result since it was not made with hdWGCNA.
