### ISSUE TITLE
No Tags 

### ISSUE THREAD

**Issue by jowodo** [smorabit/scWGCNA#191]
**Is your feature request related to a problem? Please describe.**
Even though it is discouraged to use an older version. It might be needed to reproduce results.

**Describe the solution you'd like**
github tags provide an easy tool for exactly this case. 

**Describe alternatives you've considered**
Checking the R badge from the README.md, but when looking at the raw markdown it just shows a link

**Additional context**
See #159 #124.

**Comment by smorabit** [comment]
I am planning to make a new release when there is a major update to hdWGCNA.

**Comment by jowodo** [comment]
I don't understand why you don't tag since there is a version number displayed in the `README.md`. Anyway, this is how I extract the latest version number for now: 
```
wget -q -O- https://img.shields.io/github/r-package/v/smorabit/hdWGCNA | tr ">" "\n" | grep title | tail -n1 | cut -d" " -f2 | cut -d"<" -f1 | sed "s/v//"
```
