### ISSUE TITLE
Question about the best pipeline of hdWGCNA for single-cell data analysis

### ISSUE THREAD

**Issue by yizhang-zoey** [smorabit/scWGCNA#196]
I have a single cell data containing 10 cell types.
All 10 cell types share the same per-processing (wgcna genes selection and define metacells on each cell type): `SetupForWGCNA`, `MetacellsByGroups`.
But the following step about co-expression analysis (`SetDatExpr`, `ConstructNetwork`) only for on cell type such as "INH":
```
seurat_obj <- ConstructNetwork(
    seurat_obj, 
    tom_name = 'INH',  # name of the topoligical overlap matrix written to disk
   ...
)
```
I want to save the co-expression result of 10 cell types respectively in `seurat_obj@misc` with the respective cell type name.
What is the best work pipeline?

**Comment by smorabit** [comment]
Hi,

I will link you to a previous issue asking a similar question. You are either going to want to write a loop or run a separate script for each cell type.

Previous issue: #82
