### ISSUE TITLE
Seurat data format

### ISSUE THREAD

**Issue by joe-jhou2** [smorabit/scWGCNA#20]
What if the data were processed by SCTransform? Is that possible implement one dataformatcheck function to walk users through their own data? 

I ran into this error:
 seurat_obj <- SetupForWGCNA(
+   Lesion.combined.SCT,
+   gene_select = "fraction", # the gene selection approach
+   fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
+   wgcna_name = "Lesion" # the name of the hdWGCNA experiment
+ )

Error in cut.default(1:nrow(expr_mat), n_chunks) : 
  invalid number of intervals

Totally lost about this error info. Should I add cell type into meta? I just run RenameIdents() assign cell type

**Comment by smorabit** [comment]
Hi,

I do not recommend using SCTransform for **any** gene level analyses, including differential gene expression or co-expression network analysis. You can check this paper on [scRNA-seq normalization](https://www.biorxiv.org/content/10.1101/2022.05.06.490859v1) for arguments on the subject. You should switch to the RNA assay using `DefaultAssay` and try running the code again with log normalized data.

**Comment by joe-jhou2** [comment]
Well, SCTransform vs standard normalization, it’s arguable on their performance. I’m not a statistician but it seems SCTransform is trending to me and more and more tutorials are using it. I don’t know if SCTransform particularly not working well on your package due to algorithm or just your personal preference. Anyway, I believe it would be a good idea of granting the flexibility that allow users select which normalization they prefer. Just my two cents. Thanks anyway
