### ISSUE TITLE
ModuleEigengenes exclude_grey not working

### ISSUE THREAD

**Issue by iichelhadi** [smorabit/scWGCNA#204]
When running 
```
data <- ModuleEigengenes(
  data,  exclude_grey = TRUE,
  group.by.vars = "study", max.iter.harmony = 50)
```
grey module still gets computed

**Comment by smorabit** [comment]
Hi, 

Please ignore this parameter. I have removed it from the latest version because a lot of the other code in the hdWGCNA package started to throw errors if the grey module was missing.
