### ISSUE TITLE
Zhou dataset not available

### ISSUE THREAD

**Issue by dimitrisokolowskei** [smorabit/scWGCNA#205]
Hi Sam,

Thanks for the great package. I was trying to download the ```Zhou_2020.rds``` dataset for the hdWGCNA tutorial. However, I couldn't download it using ```wget``` nor from google drive link (not available in the google drive). 

Is there a way I could get this dataset to reproduce the tutorial? Thanks once again.

Best

**Comment by DelongZHOU** [comment]
Hi Dimitri,

I downloaded the rds without problem using wget - did you receive an message indicating you may use --no-check-certificate to by pass the verification?

The following code worked for me:
` wget https://swaruplab.bio.uci.edu/public_data/Zhou_2020.rds --no-check-certificate`

**Comment by dimitrisokolowskei** [comment]
Hi @DelongZHOU,

Thank you for your assistance. I managed to download it successfully. 

Best
