### ISSUE TITLE
Error with PlotModuleTrajectory function 

### ISSUE THREAD

**Issue by kasumaz** [smorabit/scWGCNA#211]
Hi there, 
Thanks for the nice library and the way its organised. 

I am trying to run PlotModuleTrajectory on a subset of cells where pseudotime has been run already..

p <- PlotModuleTrajectory(seurat_obj, pseudotime_col = 'COPs_pseudotime') 

I get an output which I pasted below. It keeps saying I have duplicate column names and ive double checked this and done other checks to make sure. 

In a previous step I defined 'COPs_pseudotime' as: 
# separate pseudotime trajectories by the different mature cells
seurat_obj$COPs_pseudotime <- ifelse(seurat_obj$integration_col7 %in% c("aNSC4", "OLTAPs", 'cycOPCs', 'OPCs', 'COPs', 'NFOL1','NFOL2','MOLs'), seurat_obj$pseudotime, NA)

I am not sure if the NA values are problematic. I even put in a dummy number to test it out but I cant seem to move away from the error. Any hints would be great. 

Thanks a lot. 

> p <- PlotModuleTrajectory(seurat_obj, pseudotime_col = 'COPs_pseudotime')
                                   orig.ident  Dataset kaz_cond5b kaz_cond5a integration_col7 kaz_cond5c
obj_kp11_scex_AAACCCAGTATGAGAT-1_1        K11 in-house       <NA>         11             OPCs       OPCs
obj_kp11_scex_AAACGCTAGTCAATCC-1_1        K11 in-house       <NA>         11       Astrocytes Astrocytes
                                   nCount_RNA nFeature_RNA percent.mt seurat_clusters nCount_Protein
obj_kp11_scex_AAACCCAGTATGAGAT-1_1       9487         3942        100              11             NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1       6778         2481        100              25             NA
                                   nFeature_Protein nCount_SCT MULTI_Seq  Sex S.Score G2M.Score Phase Lane
obj_kp11_scex_AAACCCAGTATGAGAT-1_1               NA       9984      <NA> <NA>      NA        NA  <NA> <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1               NA       9871      <NA> <NA>      NA        NA  <NA> <NA>
                                   Cell_Type velocity_pseudotime Predicted_Region_Bcells Ventral_Score_Bcells
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>                  NA                    <NA>                   NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>                  NA                    <NA>                   NA
                                   Dorsal_Score_Bcells mito.auc mito.init.auc synapse.auc neuro.mig.auc
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                  NA       NA            NA          NA            NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                  NA       NA            NA          NA            NA
                                   dorsoventral.auc cortex.reg.auc Predicted_Region_Acells Ventral_Score_Acells
obj_kp11_scex_AAACCCAGTATGAGAT-1_1               NA             NA                    <NA>                   NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1               NA             NA                    <NA>                   NA
                                   Dorsal_Score_Acells Dorsal_Lineage_AUC Ventral_Lineage_AUC Lineage
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                  NA                 NA                  NA    <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                  NA                 NA                  NA    <NA>
                                   nCount_integrated nFeature_integrated RNA_snn_res.1 cellID sampleID
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                 0                   0          <NA>   <NA>     <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                 0                   0          <NA>   <NA>     <NA>
                                   TREATMENT_NAME exonic_umis_total exonic_genes_detected
obj_kp11_scex_AAACCCAGTATGAGAT-1_1           <NA>                NA                    NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1           <NA>                NA                    NA
                                   log10_exonic_umis_total genotype PctMitoUMI sampleLabel
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                      NA     <NA>         NA        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                      NA     <NA>         NA        <NA>
                                   oligodendrocyteNoDPACS.seuratCluster OPCandC19NoDPACS.seuratCluster
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                 <NA>                           <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                 <NA>                           <NA>
                                   genotypeGroup biologicalInterest plotClusters selected.oligo.seuratCluster
obj_kp11_scex_AAACCCAGTATGAGAT-1_1          <NA>               <NA>         <NA>                         <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1          <NA>               <NA>         <NA>                         <NA>
                                   treatment TPL2 TauP301S percent_mito_umi passFilter hMAPT_normCount
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA> <NA>     <NA>               NA         NA              NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA> <NA>     <NA>               NA         NA              NA
                                   hMAPT_Log2NormCount passCells.seuratCluster passCells.clusterInterp
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                  NA                    <NA>                    <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                  NA                    <NA>                    <NA>
                                   timepoint batch all20integrated.seuratClusterInterp  age group percent_mito
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>  <NA>                                <NA> <NA>  <NA>           NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>  <NA>                                <NA> <NA>  <NA>           NA
                                   Seuratv3.seuratCluster clusterInterp clusterInterpRevised
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                   <NA>          <NA>                 <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                   <NA>          <NA>                 <NA>
                                   choroid.seuratCluster PVM.seuratCluster integratedOligo.cluster
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                  <NA>              <NA>                    <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                  <NA>              <NA>                    <NA>
                                   endothelial.subClust.seuratCluster opc cop nfol mfol mol1 mol2 mol56
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                               <NA>  NA  NA   NA   NA   NA   NA    NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                               <NA>  NA  NA   NA   NA   NA   NA    NA
                                   mol56_c1 cyc_opc tmol56 interferon mhc1 ieg finalInterps sub.cluster
obj_kp11_scex_AAACCCAGTATGAGAT-1_1       NA      NA     NA         NA   NA  NA         <NA>        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1       NA      NA     NA         NA   NA  NA         <NA>        <NA>
                                   batchinfo mito.percent Library Region CellTypeAnnot tissue gate
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>           NA    <NA>   <NA>          <NA>   <NA> <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>           NA    <NA>   <NA>          <NA>   <NA> <NA>
                                   postnatal_day  set condition Estimated.Number.of.Cells Mean.Reads.per.Cell
obj_kp11_scex_AAACCCAGTATGAGAT-1_1            NA <NA>      <NA>                        NA                  NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1            NA <NA>      <NA>                        NA                  NA
                                   Median.Genes.per.Cell Number.of.Reads Valid.Barcodes Sequencing.Saturation
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                    NA              NA           <NA>                  <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                    NA              NA           <NA>                  <NA>
                                   Q30.Bases.in.Barcode Q30.Bases.in.RNA.Read Q30.Bases.in.Sample.Index
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                 <NA>                  <NA>                      <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                 <NA>                  <NA>                      <NA>
                                   Q30.Bases.in.UMI Reads.Mapped.to.Genome Reads.Mapped.Confidently.to.Genome
obj_kp11_scex_AAACCCAGTATGAGAT-1_1             <NA>                   <NA>                               <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1             <NA>                   <NA>                               <NA>
                                   Reads.Mapped.Confidently.to.Intergenic.Regions
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                           <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                           <NA>
                                   Reads.Mapped.Confidently.to.Intronic.Regions
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                         <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                         <NA>
                                   Reads.Mapped.Confidently.to.Exonic.Regions
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                       <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                       <NA>
                                   Reads.Mapped.Confidently.to.Transcriptome Reads.Mapped.Antisense.to.Gene
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                      <NA>                           <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                      <NA>                           <NA>
                                   Fraction.Reads.in.Cells Total.Genes.Detected Median.UMI.Counts.per.Cell
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                    <NA>                   NA                         NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                    <NA>                   NA                         NA
                                   scrublet_score scrublet_cluster_score bh_pval is_doublet n_genes n_counts
obj_kp11_scex_AAACCCAGTATGAGAT-1_1             NA                     NA      NA         NA      NA       NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1             NA                     NA      NA         NA      NA       NA
                                   annot_leiden_0_59 annot_leiden QC_pass gate_gfp prediction_Class
obj_kp11_scex_AAACCCAGTATGAGAT-1_1              <NA>         <NA>      NA     <NA>             <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1              <NA>         <NA>      NA     <NA>             <NA>
                                   probability_Class prediction_TaxonomyRank1 probability_TaxonomyRank1 cyclone
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                NA                     <NA>                        NA    <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                NA                     <NA>                        NA    <NA>
                                   cyclone_G1 cyclone_S cyclone_G2M annot_leiden_neuronal_glial
obj_kp11_scex_AAACCCAGTATGAGAT-1_1         NA        NA          NA                        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1         NA        NA          NA                        <NA>
                                   UMAP_dim1_neuronal_glial UMAP_dim2_neuronal_glial annot_leiden_OPCs
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                       NA                       NA              <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                       NA                       NA              <NA>
                                   UMAP_dim1_OPCs UMAP_dim2_OPCs annot_leiden_embryonic_RG
obj_kp11_scex_AAACCCAGTATGAGAT-1_1             NA             NA                      <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1             NA             NA                      <NA>
                                   UMAP_dim1_embryonic_RG UMAP_dim2_embryonic_RG annot_leiden_NBs UMAP_dim1_NBs
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                     NA                     NA             <NA>            NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                     NA                     NA             <NA>            NA
                                   UMAP_dim2_NBs CC.Difference cell_type_tsne Condition Simplified_clusters
obj_kp11_scex_AAACCCAGTATGAGAT-1_1            NA            NA           <NA>      <NA>                <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1            NA            NA           <NA>      <NA>                <NA>
                                   Full_clusters lineage_alra Full_detailed_clusters new_clusters
obj_kp11_scex_AAACCCAGTATGAGAT-1_1          <NA>         <NA>                   <NA>         <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1          <NA>         <NA>                   <NA>         <NA>
                                   clusters_to_use complete_simplified_clusters complete_full_clusters
obj_kp11_scex_AAACCCAGTATGAGAT-1_1            <NA>                         <NA>                   <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1            <NA>                         <NA>                   <NA>
                                   percent.ribo percent.y dim30_res1 miQC.probability miQC.keep lineage
obj_kp11_scex_AAACCCAGTATGAGAT-1_1           NA        NA       <NA>               NA      <NA>    <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1           NA        NA       <NA>               NA      <NA>    <NA>
                                   full_clusters simplified_clusters predicted.simplifiedcelltype.score
obj_kp11_scex_AAACCCAGTATGAGAT-1_1          <NA>                <NA>                                 NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1          <NA>                <NA>                                 NA
                                   predicted.simplifiedcelltype predicted.fullcelltype.score
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                         <NA>                         <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                         <NA>                         <NA>
                                   predicted.fullcelltype nCount_prediction.score.simplifiedcelltype
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                   <NA>                                          0
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                   <NA>                                          0
                                   nFeature_prediction.score.simplifiedcelltype
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                            0
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                            0
                                   nCount_prediction.score.fullcelltype nFeature_prediction.score.fullcelltype
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                    0                                      0
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                    0                                      0
                                   n_numbers Kages_timepoint3 Kcelltype cells_to_show COPs_AUC COPs_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>             <NA>      <NA>            NA     <NA>              NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>             <NA>      <NA>            NA     <NA>              NA
                                   ModifiedKcelltype NewIDs1 MajorID OPCs_AUC OPCs_AUC_scores NFOL1.2_AUC
obj_kp11_scex_AAACCCAGTATGAGAT-1_1              <NA>    <NA>    <NA>     <NA>              NA        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1              <NA>    <NA>    <NA>     <NA>              NA        <NA>
                                   NFOL1.2_AUC_scores MFOL1_2_AUC MFOL1_2_AUC_scores MOL1to6_AUC
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                 NA        <NA>                 NA        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                 NA        <NA>                 NA        <NA>
                                   MOL1to6_AUC_scores NFOL1_AUC NFOL1_AUC_scores NFOL2_AUC NFOL2_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                 NA      <NA>               NA      <NA>               NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                 NA      <NA>               NA      <NA>               NA
                                   MFOL1_AUC MFOL1_AUC_scores MFOL2_AUC MFOL2_AUC_scores MOL1to4_AUC
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>               NA      <NA>               NA        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>               NA      <NA>               NA        <NA>
                                   MOL1to4_AUC_scores MOL5_6_AUC MOL5_6_AUC_scores MOL2_3_AUC MOL2_3_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                 NA       <NA>                NA       <NA>                NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                 NA       <NA>                NA       <NA>                NA
                                   MOL5_AUC MOL5_AUC_scores MOL6_AUC MOL6_AUC_scores MOL1_AUC MOL1_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1     <NA>              NA     <NA>              NA     <NA>              NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1     <NA>              NA     <NA>              NA     <NA>              NA
                                   MOL4_AUC MOL4_AUC_scores MOL2_AUC MOL2_AUC_scores MOL3_AUC MOL3_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1     <NA>              NA     <NA>              NA     <NA>              NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1     <NA>              NA     <NA>              NA     <NA>              NA
                                   OL_Lineage_AUCdefined COP_AUC COP_AUC_scores qNSC1_AUC qNSC1_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                  <NA>    <NA>             NA      <NA>               NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                  <NA>    <NA>             NA      <NA>               NA
                                   aNSC1_AUC aNSC1_AUC_scores qNSC2_AUC qNSC2_AUC_scores qNSC3_AUC
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>               NA      <NA>               NA      <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>               NA      <NA>               NA      <NA>
                                   qNSC3_AUC_scores aNSC4_AUC aNSC4_AUC_scores aNSC3_AUC aNSC3_AUC_scores
obj_kp11_scex_AAACCCAGTATGAGAT-1_1               NA      <NA>               NA      <NA>               NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1               NA      <NA>               NA      <NA>               NA
                                   aNSC2_AUC aNSC2_AUC_scores Earlier_stages1_AUCdefined Merged_AUCdefined
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>               NA                       <NA>              <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>               NA                       <NA>              <NA>
                                   complete_simplified_clusters_no_ages                          RowNames
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                                 <NA> scex11k_scex_AAACCCAGTATGAGAT-1_1
obj_kp11_scex_AAACGCTAGTCAATCC-1_1                                 <NA> scex11k_scex_AAACGCTAGTCAATCC-1_1
                                   RowNames.3 MergedIDs2 MergedIDs3 MergedIDs4 MergedIDs5 MergedIDs6 Cluster1
obj_kp11_scex_AAACCCAGTATGAGAT-1_1       <NA>       <NA>       <NA>       <NA>       <NA>       <NA>       NA
obj_kp11_scex_AAACGCTAGTCAATCC-1_1       <NA>       <NA>       <NA>       <NA>       <NA>       <NA>       NA
                                   dorsal_markers1 astrocyte_defined MergedIDs7 MajorIDs3 MergedIDs8 MergedIDs9
obj_kp11_scex_AAACCCAGTATGAGAT-1_1              NA              <NA>       <NA>      <NA>       <NA>       <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1              NA              <NA>       <NA>      <NA>       <NA>       <NA>
                                   MergedIDs10 MergedIDs11 MergedIDs12 MergedIDs13 MergedIDs14 MergedIDs15
obj_kp11_scex_AAACCCAGTATGAGAT-1_1        <NA>        <NA>        <NA>        <NA>        <NA>        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1        <NA>        <NA>        <NA>        <NA>        <NA>        <NA>
                                   MergedIDs16 MergedIDs17 MajorIDs5 MergedIDs18 MergedIDs20 MergedIDs21
obj_kp11_scex_AAACCCAGTATGAGAT-1_1        <NA>        <NA>      <NA>        <NA>        <NA>        <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1        <NA>        <NA>      <NA>        <NA>        <NA>        <NA>
                                   MergedIDs22 integration_col kaz_cond integration_col2 kaz_cond4 kaz_cond5
obj_kp11_scex_AAACCCAGTATGAGAT-1_1        <NA>            <NA>     <NA>          unknown       P11       P11
obj_kp11_scex_AAACGCTAGTCAATCC-1_1        <NA>            <NA>     <NA>          unknown       P11       P11
                                   Brain_Region main_clusters kaz_cond2 kaz_cond3  simp_col integrated_res1
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      dSVZ+CC             .      <NA>    Normal      OPCs              30
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      dSVZ+CC             .      <NA>    Normal Remaining               1
                                   ident integration_col3 kaz_cond6 percent.rb integration_col4
obj_kp11_scex_AAACCCAGTATGAGAT-1_1  <NA>             OPCs      <NA>   4.448192             OPCs
obj_kp11_scex_AAACGCTAGTCAATCC-1_1  <NA>       Astrocytes      <NA>   1.652405       Astrocytes
                                   integration_col5 broader_stages1 integration_col7_df integration_col7_plot
obj_kp11_scex_AAACCCAGTATGAGAT-1_1             OPCs            OPCs                OPCs                  <NA>
obj_kp11_scex_AAACGCTAGTCAATCC-1_1       Astrocytes      Astrocytes          Astrocytes                  <NA>
                                   kaz_cond8 clusters     metacell_grouping integrated.05_1_res.0.5 kaz_cond5d
obj_kp11_scex_AAACCCAGTATGAGAT-1_1      <NA>       13             OPCs#OPCs                       5       OPCs
obj_kp11_scex_AAACGCTAGTCAATCC-1_1      <NA>       11 Astrocytes#Astrocytes                      20 Astrocytes
                                   ntegration_col7_plot ntegration_col8_plot integration_col8_plot OLTAPs_AUC
obj_kp11_scex_AAACCCAGTATGAGAT-1_1                 OPCs                 OPCs                  OPCs      other
obj_kp11_scex_AAACGCTAGTCAATCC-1_1           Astrocytes           Astrocytes            Astrocytes      other
                                   OLTAPs_AUC_scores integrated.075_1_res.0.75 integrated.1_1_res.1
obj_kp11_scex_AAACCCAGTATGAGAT-1_1        0.07490825                         5                   11
obj_kp11_scex_AAACGCTAGTCAATCC-1_1        0.02697701                        25                   25
                                   nFeature_SCT pseudotime      brown    yellow      pink     black     purple
obj_kp11_scex_AAACCCAGTATGAGAT-1_1         3927  33.108879  -3.809962 -6.132482 -1.832806  1.524285 -0.5784735
obj_kp11_scex_AAACGCTAGTCAATCC-1_1         2501   8.146171 -13.791988 -7.637890 -4.775164 -4.476177 -5.5223190
                                    turquoise     salmon   magenta       red      grey        tan      blue
obj_kp11_scex_AAACCCAGTATGAGAT-1_1   2.316369 -0.1156856 -1.965892 -3.760517 -2.636385 -0.7092816  7.942873
obj_kp11_scex_AAACGCTAGTCAATCC-1_1 -13.590762 -5.2901340  5.562703  6.352035 13.970372  0.6591107 -3.044767
                                   greenyellow     green    brown.1  yellow.1    pink.1   black.1   purple.1
obj_kp11_scex_AAACCCAGTATGAGAT-1_1   7.8481404 18.713262  -3.809962 -6.132482 -1.832806  1.524285 -0.5784735
obj_kp11_scex_AAACGCTAGTCAATCC-1_1   0.1632684 -1.400689 -13.791988 -7.637890 -4.775164 -4.476177 -5.5223190
                                   turquoise.1   salmon.1 magenta.1     red.1    grey.1      tan.1    blue.1
obj_kp11_scex_AAACCCAGTATGAGAT-1_1    2.316369 -0.1156856 -1.965892 -3.760517 -2.636385 -0.7092816  7.942873
obj_kp11_scex_AAACGCTAGTCAATCC-1_1  -13.590762 -5.2901340  5.562703  6.352035 13.970372  0.6591107 -3.044767
                                   greenyellow.1   green.1 COPs_pseudotime    UMAP1     UMAP2
obj_kp11_scex_AAACCCAGTATGAGAT-1_1     7.8481404 18.713262        33.10888 3.744274 13.230577
obj_kp11_scex_AAACGCTAGTCAATCC-1_1     0.1632684 -1.400689        99.99000 3.653684 -9.383246
                                   COPs_pseudotime_bins_20      brown    yellow      pink     black     purple
obj_kp11_scex_AAACCCAGTATGAGAT-1_1             [32.9,49.2)  -3.809962 -6.132482 -1.832806  1.524285 -0.5784735
obj_kp11_scex_AAACGCTAGTCAATCC-1_1             [51.0, Inf] -13.791988 -7.637890 -4.775164 -4.476177 -5.5223190
                                    turquoise     salmon   magenta       red      grey        tan      blue
obj_kp11_scex_AAACCCAGTATGAGAT-1_1   2.316369 -0.1156856 -1.965892 -3.760517 -2.636385 -0.7092816  7.942873
obj_kp11_scex_AAACGCTAGTCAATCC-1_1 -13.590762 -5.2901340  5.562703  6.352035 13.970372  0.6591107 -3.044767
                                   greenyellow     green
obj_kp11_scex_AAACCCAGTATGAGAT-1_1   7.8481404 18.713262
obj_kp11_scex_AAACGCTAGTCAATCC-1_1   0.1632684 -1.400689
 [ reached 'max' / getOption("max.print") -- omitted 4 rows ]
Error in `group_by()`:
! Can't transform a data frame with duplicate names.

**Comment by smorabit** [comment]
Hi,

Thank you for taking the time to write this issue. However I am a little confused, I do not see your error message here? I am also not sure what the output is that you are showing here? I am also wondering if you got the same error running this on the dataset that we provided with the pseudotime tutorial? I don't think that the `NA` values are a problem, you can see in the tutorial that there are some `NA` values which we introduce to denote cells that are not assigned to certain trajectories.

Also I kindly suggest you to consult the [markdown style guide](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) and use the preview feature for GitHub issues, it is a lot easier for me to help solve these issues if they are easier to read!

**Comment by kasumaz** [comment]
Hi there, 
Sorry, but for some reason the error message was cut off. Thanks for your reply otherwise. I managed to work around the problem by simply building my own script to show the different modules in pseudotime. I can always share it here in due course if anyone else encounters the same issue. Thanks.
