### ISSUE TITLE
Assigning genes to modules based on Metacells, not cells? 

### ISSUE THREAD

**Issue by Dimmiso** [smorabit/scWGCNA#212]
Hi, thanks a lot for developing and supporting hdWGCNA! 
as I understand hdWGCNA flow, after modules are determined based on metacells, then genes are assigned to modules and this assignment is based on cells, not metacells. If I understand logic correctly, metacells usage on the first step is justified by the facts that calculation is simpler and substantial amount of noise is gone as metacells are technically some "averaged" cells, which makes data much cleaner taking into account burst-based nature of transcription. 
But is there any simple way to use metacell data for assignment genes to modules also? Intuitevly, it may provide cleaner results. 

Thanks a lot!
Dmitry

**Comment by smorabit** [comment]
Hi Dmitry.

I will briefly summarize some key points for you, but I would also kindly suggest for you to read the [hdWGCNA paper](https://www.cell.com/cell-reports-methods/pdf/S2667-2375(23)00127-3.pdf) if you wish to understand this in greater detail. The first section in the Results describes the rationale behind using metacells. The Methods section might also help you understand this further. 

We use the metacell gene expression matrix to construct a gene co-expression network, and then we use this network to identify gene modules. Then we use the original single cell matrix to calculate the cell-level gene expression patterns (module eigengenes) for these modules, which were computed based on the metacells.

**Comment by Dimmiso** [comment]
Hi Sam, thanks a lot for your comments and for supporting hdWGCNA.
