### ISSUE TITLE
Got error message "GetAssayData doesn't work for multiple layers in v5 assay"

### ISSUE THREAD

**Issue by shadowdeng1994** [smorabit/scWGCNA#214]
I got the following message when I tried to run `SetDatExpr` on an integrated Seurat object. How can I solve it? 

Warning message in SetDatExpr(tmp.hdWGCNA, group_name = "0", group.by = "seurat_clusters"):
“assay not specified, trying to use assay SCT”
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Traceback:

1. SetDatExpr(tmp.hdWGCNA, group_name = "0", group.by = "seurat_clusters")
2. as.data.frame(Seurat::GetAssayData(s_obj, assay = assay, slot = slot)[genes_use, 
 .     cells])
3. Seurat::GetAssayData(s_obj, assay = assay, slot = slot)
4. GetAssayData.Seurat(s_obj, assay = assay, slot = slot)
5. GetAssayData(object = object[[assay]], layer = layer)
6. GetAssayData.StdAssay(object = object[[assay]], layer = layer)
7. abort("GetAssayData doesn't work for multiple layers in v5 assay.", 
 .     " You can run 'object <- JoinLayers(object = object, layers = layer)'.")
8. signal_abort(cnd, .file)

**Comment by rootze** [comment]
@shadowdeng1994 This error is due to the Seurat V5 updates. 

#README
Note about Seurat v5: We plan to test the compatibility of hdWGCNA with Seurat version 5, but we have currently not updated hdWGCNA to work with Seurat v5. We strongly suggest using Seurat v4 at this time, or use v5 at your own risk.

**Comment by smorabit** [comment]
hdWGCNA does not work with Seurat v5 at this time. Actively working on an update for v5 support and it will be ready in a few weeks. Please continue to use Seurat v4 as suggested in the tutorial until we release an update for v5 support.
