### ISSUE TITLE
Question about differential connectivity analysis

### ISSUE THREAD

**Issue by DelongZHOU** [smorabit/scWGCNA#224]
Hi Sam,
I believe another way to compare the modules across condition, in addition to the ME values, is to compare the connectivity, i.e. if the correlation between any pair of genes are stronger or weaker. Is there a way to do this in hdWGCNA?
Thank you!

**Comment by smorabit** [comment]
hdWGCNA does not have a way to do this. You could just calculate the two different co-expression networks for each condition and then just compare the values as you see fit.

**Comment by DelongZHOU** [comment]
OK thank you!
