### ISSUE TITLE
Running hdWGCNA on merged dataset and harmonizing on "study"

### ISSUE THREAD

**Issue by mitchTwoTimes** [smorabit/scWGCNA#225]
Hi, 

Do you see any issue running the standard hdWGCNA workflow on a harmony-corrected dataset? My approach is similar to your approach in [Fig 6](https://www.sciencedirect.com/science/article/pii/S2667237523001273#fig6). Instead of the consensus approach (I found it didn't give me enough modules), I used "study" as my `group.by.vars` to harmonize in `ModuleEigengenes`. I did trait correlation and maybe 1-2 out of 17 correlated with study, but that was it.

Thank you

**Comment by smorabit** [comment]
Yes this sounds like a reasonable approach to me!
