### ISSUE TITLE
Question about weird soft power plot

### ISSUE THREAD

**Issue by DelongZHOU** [smorabit/scWGCNA#228]
Hi,
I'm having a wierd soft power plot for one of my cell types:

![image](https://github.com/smorabit/hdWGCNA/assets/56367172/964f0020-0481-4a4e-a028-01e198ed904c)

This also comes with a warning:

> In min(.) : no non-missing arguments to min; returning Inf

What do you recommand to do in this case?

The plot for another cell type in the same data set looks fine:
![image](https://github.com/smorabit/hdWGCNA/assets/56367172/b5785216-c8b1-4a8f-bbee-464c2f772fd1)

Edit: the celltype that poses problem is the one that previously didn't have enough cells when I used group by samples, here I'm grouping by condition. So this may be the underlying cause. Although another cell type with similar cell count (both ~300) ends up with >40 modules.

**Comment by smorabit** [comment]
Hi,

You may get poor results like this when you have very small clusters as you have described. I recommend not running hdWGCNA for very small clusters.

**Comment by DelongZHOU** [comment]
Alright thank you!
Delong
