### ISSUE TITLE
How to extract the modules' hub genes?

### ISSUE THREAD

**Issue by levinhein** [smorabit/scWGCNA#23]
Hello,

May I ask how can I extract the hub genes in each of the modules? I can see them from the tables and visualizations but I wonder if I can get the hub genes per Module and assign these to new vectors? I would like to use these as gene sets for other analyses. Thank you!

Similar:

Module1_hubgenes <- head(MODULE$hub1)
Module2_hubgenes <- head(MODULE$hub2)

Thank you!

**Comment by smorabit** [comment]
Hi,

I just added a new function to hdWGCNA, `GetHubGenes`, which should help you. To use this function please re-install hdWGCNA so you have the newest version:

`devtools::install_github('smorabit/hdWGCNA', ref='dev')`

You can run the function like this:

```
# get hub genes
hub_df <- GetHubGenes(seurat_obj, n_hubs = 10)
```

This would give you the top 10 hub genes by kME for each module. You can also use the `mods` parameter if you wish to get hub genes for only a selected list of modules:

`hub_df <- GetHubGenes(seurat_obj, n_hubs = 10, mods=c("INH-M1", "INH-M2")`

Let me know if this solves your problem.

**Comment by Cedar1111** [comment]
Hello,
When I run the code: 
`hub_df <- GetHubGenes(seurat_obj7, n_hubs = 10)`
I get an error reported:
`GetQuote: Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length getsymbols`
Could you help me with this error? Thank you very much!
