### ISSUE TITLE
Error in ModuleEigengenes

### ISSUE THREAD

**Issue by C1165511708** [smorabit/scWGCNA#231]
> seurat_obj <- ModuleEigengenes(
 seurat_obj,
 group.by.vars='orig.ident'
)
Error in !CheckWGCNAName(seurat_obj, wgcna_name) : invalid argument type

**Comment by smorabit** [comment]
If you want help with your issue you need to provide more information, please write an issue based on templates that we provide.

**Comment by LiXiaoyu1014** [comment]
> If you want help with your issue you need to provide more information, please write an issue based on templates that we provide.


I wonder if there is a grammar error beacuse when I test 
CheckWGCNAName(seurat_obj, "Mouse_DM_Ctrl_epc") No error message
but 

> !CheckWGCNAName(seurat_obj, "Mouse_DM_Ctrl_epc")
Error in !CheckWGCNAName(seurat_obj, "Mouse_DM_Ctrl_epc") : 
  invalid argument type

**Comment by C1165511708** [comment]
I appreciate your response. I have reinstalled the package and successfully resolved the issue.

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/04/2024 13:53 |
| To | smorabit/hdWGCNA ***@***.***> |
| Cc | caifuqiang ***@***.***>,
Author ***@***.***> |
| Subject | Re: [smorabit/hdWGCNA] Error in ModuleEigengenes (Issue #231) |

If you want help with your issue you need to provide more information, please write an issue based on templates that we provide.

I wonder if there is a grammar error beacuse when I test
CheckWGCNAName(seurat_obj, "Mouse_DM_Ctrl_epc") No error message
but

!CheckWGCNAName(seurat_obj, "Mouse_DM_Ctrl_epc")
Error in !CheckWGCNAName(seurat_obj, "Mouse_DM_Ctrl_epc") :
invalid argument type

**Comment by Baozi9** [comment]
hi！I just come with the same porblem! Can u tell me how you solve it finally?

**Comment by LiXiaoyu1014** [comment]
hello,&nbsp;


I just uninstalled the hdWGCNA package and reinstall from github source then it works,hope these contents can help you.






李晓宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smorabit/hdWGCNA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 晚上11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smorabit/hdWGCNA] Error in ModuleEigengenes (Issue #231)





 
hi！I just come with the same porblem! Can u tell me how you solve it finally?
