### ISSUE TITLE
Error duing ModulePreservation "Error in multiColor[[s]] : subscript out of bounds"

### ISSUE THREAD

**Issue by DelongZHOU** [smorabit/scWGCNA#235]
Hi Sam,
I have some new issues related to module preservation:

with code:

> seurat_query <- ModulePreservation(
    seurat_query,
    seurat_ref = seurat_ref,
    name="From_allen",
    verbose=3,
    n_permutations=250,
    permutedStatisticsFile=/path/
  )

And it returns error:

>  ..checking data for excessive amounts of missing data..
     Flagging genes and samples with too many missing values...
      ..step 1
     Flagging genes and samples with too many missing values...
      ..step 1
Error in multiColor[[s]] : subscript out of bounds

It produced the same error on some of my old datasets which completed without error before.

**Comment by ashleshagogate** [comment]
Hi Sam, 
I am facing the same issue (hdWGCNA 0.2.27).

**Comment by smorabit** [comment]
Hi,

I tried to run `ModulePreservation` and was met with the same error. I did find the source of the bug and was able to fix it, so  please update to the latest version and hopefully it will work for you.

**Comment by DelongZHOU** [comment]
Indeed it's fixed. Thank you Sam!

**Comment by ashleshagogate** [comment]
Yes, thank you!

**Comment by wowotou4120** [comment]
[1] "ref:"
[1] 1000 3733
[1] "query:"
[1]  971 3733
[1] 1
  ..checking data for excessive amounts of missing data..
     Flagging genes and samples with too many missing values...
      ..step 1
     Flagging genes and samples with too many missing values...
      ..step 1
Error in multiColor[[s]] : subscript out of bounds
