### ISSUE TITLE
update installation documentation 

### ISSUE THREAD

**Issue by jowodo** [smorabit/scWGCNA#240]
**Is your feature request related to a problem? Please describe.**
installation with `devtools::install_github('smorabit/hdWGCNA', ref='dev')` will always install the latest version. 

**Describe the solution you'd like**
In `README.md` replace 
```
devtools::install_github('smorabit/hdWGCNA', ref='dev')
```
with 
```
devtools::install_github('smorabit/hdWGCNA', ref='v0.3.00')
```

**Additional context**
#159

**Comment by smorabit** [comment]
In the readme we intentionally provide instructions on how to install the latest version of the package not just one specific version.
