### ISSUE TITLE
Removing anti-correlated genes from module

### ISSUE THREAD

**Issue by mitchTwoTimes** [smorabit/scWGCNA#241]
Hi,

I created a signed network and found that some of the genes in my modules aren't moving in the direction I'd like them to. I'm trying to create a "score" using module eigengenes and am worried these anti-correlated genes will skew my results.

1) Is there a way to exclude these anti-correlated genes from downstream analyses?
2) Is trimming a module like this even okay from a methods standpoint?

Thank you!

**Comment by smorabit** [comment]
> some of the genes in my modules aren't moving in the direction I'd like them to

I am not really sure what you mean by this statement, can you please explain?

**Comment by mitchTwoTimes** [comment]
I'd like my co-expression network only include genes that increase with time. In the heatmap below, some ideal genes would be in the middle. Would it be appropriate to trim the module to those that meet this criteria?

<img width="314" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/92815743/677fbe70-256f-41f0-88dc-ee8cb88e95bf">

**Comment by smorabit** [comment]
If you only want to use genes that increase with time, then you should use that list of genes as the input to hdWGCNA. For example:

```
seurat_obj <- SetupForWGCNA(
     seurat_obj,
     features = gene_list,
     wgcna_name = 'test'
)
```

However I will caution you that if your list of genes is really small it could be difficult to get meaningful results out of this.

**Comment by mitchTwoTimes** [comment]
Sorry, those were genes from one of my modules, I was just mapping them to a reference dataset and saw they weren't trending in the direction I wanted. My question basically, "Can I trim my modules to specific genes of interest?"

**Comment by smorabit** [comment]
> "Can I trim my modules to specific genes of interest?"

Ultimately you can do whatever you want because it is your data, but personally I would not do this if it were my project. Instead I would do as I previously suggested and run hdWGCNA only on those genes that you are interested in.
