### ISSUE TITLE
Little issue about the Seurat dot plot

### ISSUE THREAD

**Issue by Tianqi-Ma** [smorabit/scWGCNA#25]
Hi,

I tested hdWGCNA on different cell types in my data and all of them had a 'grey' moudle in the Seurat dot plot.
![CAFs_seurat_dotplot](https://user-images.githubusercontent.com/56350087/173980407-4c056460-3434-4ce0-ba3a-1f627aa5eb53.png)

```
> dim(GetMEs(seurat_obj, harmonized=TRUE))
[1] 97595     7
> colnames(GetMEs(seurat_obj))
[1] "CAFs-M1" "CAFs-M2" "CAFs-M3" "CAFs-M4" "CAFs-M5" "grey"    "CAFs-M6"

```
But the module correlation plot doesn't have this 'grey' module.
![CAFs_Module_Correlations](https://user-images.githubusercontent.com/56350087/173980636-62fc01b7-86de-4eb1-bd84-eecbd05e3c87.png)

And the dendrogram have this grey module
![CAFs_Dendrogram](https://user-images.githubusercontent.com/56350087/174005629-c2f86a30-241f-41df-8bb5-a7036889154b.png)

BTW, I faced an error when dealing with one trait. See here: [https://github.com/smorabit/hdWGCNA/issues/24](url)

**Comment by smorabit** [comment]
I added this clarification to the basics tutorial:

> Importantly, the "grey" module consists of genes that were not grouped into any co-expression module. The grey module should be ignored for all downstream analysis and interpretation.
