### ISSUE TITLE
Question about interpreting kME

### ISSUE THREAD

**Issue by DelongZHOU** [smorabit/scWGCNA#256]
Hi Sam,

I'd like seek your input on my understanding of the kME and how I'd like to use it for condition-wise comparison
As stated in my other postes, I'm currently making the modules accross conditions and want to compare how the modules "change" between conditions.
It seems to me that given a gene G in a module M, its kME measures how well the expression of G correlates with all other genes in M. In my case this is one single value associated to all conditions.
Is it possible to compute this value for each condition, and test if it's higher / lower in one condition compared to another?

Thank you!

**Comment by smorabit** [comment]
> It seems to me that given a gene G in a module M, its kME measures how well the expression of G correlates with all other genes in M.

kME is the correlation of a gene's expression with a module eigengene.

> Is it possible to compute this value for each condition, and test if it's higher / lower in one condition compared to another?

Seems like this is possible but I have not tried it so I don't have any specific recommendations for how to test those differences.

**Comment by DelongZHOU** [comment]
Thank you for your answer!
For the second point, I think the main challenge is to reproduce the network from the merged object in each condition. Is there way to somehow "manually" define the modules using the gene membership from the parent object?

**Comment by smorabit** [comment]
I think you can write some custom code to define the modules in this way but there is not a way to do this with hdWGCNA functions.

**Comment by DelongZHOU** [comment]
OK thanks!
