### ISSUE TITLE
Errors with Metacells Construction

### ISSUE THREAD

**Issue by MattGoulty** [smorabit/scWGCNA#26]
Hello

I have tried to construct metacells using both ConstructMetacells and MetacellsByGroups commands as below: 

Spur_hdWGCNA <- ConstructMetacells(Spur_hdWGCNA, name = "agg", ident.group = "seurat_clusters", k = 20, reduction = "pca", assay = "RNA", slot = "counts", wgcna_name = "Spur_hdWGCNA")

Spur_hdWGCNA <- MetacellsByGroups(Spur_hdWGCNA, k = 20, assay = "RNA", reduction = "pca",  wgcna_name = "Spur_hdWGCNA", group.by = c("orig.ident","seurat_clusters"), ident.group = "seurat_cluster")

With MetacellsByGroups it fails giving the following:
Error in rep_len(x = value, length.out = length(x = cells)) : 
  cannot replicate NULL to a non-zero length

With ConstructMetacells it finished but when I try to transpose the matrix with SetDatExpr I receive this error?
Spur_hdWGCNA <- SetDatExpr(Spur_hdWGCNA, use_metacells=TRUE, wgcna_name = "Spur_hdWGCNA", slot = "counts",  group.by = "seurat_clusters")

Error in SetDatExpr(Spur_hdWGCNA, use_metacells = TRUE, wgcna_name = "Spur_hdWGCNA",  : 
  seurat_clusters not found in the meta data of the metacell Seurat object

Is there a more simple way of constructing the metacells? The dataset I am using only has one sample so I am not wanting to group by anything to account for metadata.
Also is there a way to form metacells without even restricting to cells from the same seurat cluster? Just basing it on nearest neighbour cells?

Also, I am interested in the gene modules across the whole dataset - not any specific cell type/seurat cluster within it

Any help is much appreciated
Thank you

Matthew

**Comment by smorabit** [comment]
Hi, first of all I appreciate your interest in using hdWGCNA for your research.

So it sounds like you are trying to run hdWGCNA without any grouping by sample ID or cell type/cluster etc. You can essentially tell it to "group by" a metadata column where all of the values are the same, so there actually won't be any grouping going on. This needs to be referred to in both the `ConstructMetacells` function and `SetDatExpr`. Try the following code:

```

# set a metadata column in the seurat object with the same value for every cell:
seurat_obj$orig.ident <- 'SeuratProject'

seurat_obj <- ConstructMetacells(
  seurat_obj, 
  name = 'all',
  ident.group = 'orig.ident', 
  k = 20, 
  reduction = "pca",
  assay = "RNA", 
  slot = "counts", 
  wgcna_name = "Spur_hdWGCNA"
)

seurat_obj <- NormalizeMetacells(seurat_obj)

seurat_obj <- SetDatExpr(
  seurat_obj,
  group_name = 'all', # should be the same as name in ConstructMetacells
  group.by = 'orig.ident', # should be the same as ident.group in ConstructMetacells
  use_metacells=TRUE,
  slot = 'data',
  wgcna_name = "Spur_hdWGCNA"
)

```

Please let me know if this fixes your issue.
