### ISSUE TITLE
Error in UseMethod(generic = "JoinLayers", object = object) :    no applicable method for 'JoinLayers' applied to an object of class "c('Assay', 'KeyMixin')"

### ISSUE THREAD

**Issue by Jxuanrui** [smorabit/scWGCNA#261]
hdWGCNA is a great job and I'm learning it, but I'm having some problems running the sample processes:seurat_obj <- MetacellsByGroups(
+   seurat_obj = seurat_obj,
+   group.by = c("cell_type", "Sample"), # specify the columns in seurat_obj@meta.data to group by
+   reduction = 'harmony', # select the dimensionality reduction to perform KNN on
+   k = 25, # nearest-neighbors parameter
+   max_shared = 10, # maximum number of shared cells between two metacells
+   ident.group = 'cell_type' # set the Idents of the metacell seurat object
+ )
Error in UseMethod(generic = "JoinLayers", object = object) : 
  no applicable method for 'JoinLayers' applied to an object of class "c('Assay', 'KeyMixin')"
In addition: Warning message:
In MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("cell_type",  :
  Removing the following groups that did not meet min_cells: ASC#C4, MG#C2, MG#C3, MG#C4, ODC#C4, OPC#C12, OPC#C4, OPC#C9
The code part is exactly the code of the sample flow, I didn't make any modification, and my Seurat version is also 5.0, how should I solve this problem?

**Comment by Jxuanrui** [comment]
Thank you I solve it

**Comment by ehughes1994** [comment]
Hi Jxuanrui,

I am getting the exact same error message (but I am using Seurat v4). Could you share how you solved the problem?

**Comment by CWYuan08** [comment]
Dear @smorabit @Jxuanrui @ehughes1994 @samuel-marsh @rootze,
is there an solution to this issue? I have encountered the same issue.

Many thanks!
CW

**Comment by DLY-2021** [comment]
Hi Jxuanrui,

I'm encountering the same error message with Seurat v5. Could you please share how you resolved this issue? Thank you very much!
