### ISSUE TITLE
Error in SetModules(seurat_obj, mod_df = data.frame(gene_name = names(mods),

### ISSUE THREAD

**Issue by zxyEmily** [smorabit/scWGCNA#267]
Thank you very much for developing the hdWGCNA package. However, I have encountered an issue in "Construct co-expression network"

The detals as follow:
seurat_obj <- ConstructNetwork(seurat_obj, tom_name = 'INH' # name of the topoligical overlap matrix written to disk)

 Calculating consensus modules and module eigengenes block-wise from all genes
 Calculating topological overlaps block-wise from all genes
   Flagging genes and samples with too many missing values...
    ..step 1
    TOM calculation: adjacency..
    ..will use 8 parallel threads.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
 ..Working on block 1 .
 ..Working on block 1 .
 ..merging consensus modules that are too close..
Error in SetModules(seurat_obj, mod_df = data.frame(gene_name = names(mods),  : 
  parameter useless(mod_df = data.frame(gene_name = names(mods), module = factor(mods, levels = unique(mods)), color = mods))

packageVersion('hdWGCNA')
[1] ‘0.3.2’

I just want to repeat the hdWGCNA use the data 'Zhou_2020.rd's , The rest of the all the orders are from https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html

I hope you can provide a solution and thank you for your time and attention.

**Comment by smorabit** [comment]
Hi,

Can you please try re-installing hdWGCNA and running it again? I found the same error, and it was just a small typo that I had made in the 0.3.2 update but it should be fixed now.

**Comment by zxyEmily** [comment]
> Hi,
> 
> Can you please try re-installing hdWGCNA and running it again? I found the same error, and it was just a small typo that I had made in the 0.3.2 update but it should be fixed now.

ok ,thank  you

**Comment by ydluo96** [comment]
Last week , it came out the same error. 
But Today I have  re-installed hdWGCNA package, and it doesn't work.
<img width="1032" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/76644172/6ef80603-5251-4369-ae5c-c146c1a1d3dd">

**Comment by ydluo96** [comment]
Thanks to author. I solved it by re-installing hdWGCNA

**Comment by ydluo96** [comment]
Hello!
While  I use ModuleUMAPPlot to plot , the genes in picture are to close to each other.
Could u add a para like repel=T to avoid this issue.
<img width="499" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/76644172/b392b90d-0d41-43e4-a2fe-786b623fad9a">
I hope you can provide a solution and thank you for your time and attention.

**Comment by smorabit** [comment]
> While I use ModuleUMAPPlot to plot , the genes in picture are to close to each other.
Could u add a para like repel=T to avoid this issue.

Please see my response to this question in #18 . In the future it is best to have GitHub issue for a single topic, and you can search to see if your question has already been asked.
