### ISSUE TITLE
Analyzing co-expression of specific genes of interest using hdWGCNA

### ISSUE THREAD

**Issue by sandcell10** [smorabit/scWGCNA#270]
Hi @smorabit 

Thank you for developing such an awesome package! I have really enjoyed using hdWGCNA to analyze some datasets I have been working with. I would like to characterize the co-expression of a specific set of genes of interest (about 7 genes total) within my data sets. 

One way I have done this is to see which genes of interest end up in the same modules. However, I would like to characterize the co-expression of the gene set overall. Is there a way to do this and visualize it with hdWGCNA? The goal would be to create something like the hub gene network plot (pictured below) from the network visualization vignette, but only include my genes of interest. 

<img width="528" alt="image" src="https://github.com/smorabit/hdWGCNA/assets/171267106/6499d202-f309-4ea3-89f0-06fe666a1f1d">

I would also like to characterize pair-wise co-expression between genes in my gene set. I understand you cannot always do a simple correlation between genes in single cell data due to sparsity. Would the corresponding gene-gene values in the topoligcal overlap matrix be a valid way to characterize gene-pair correlations? 

Lastly, any other suggestions you have for analyzing specific gene sets using hdWGCNA would be appreciated! Cheers and thank you for your consideration!

**Comment by sandcell10** [comment]
Hi @smorabit 

Luckily, I found your excellent vignette on creating customized network plots! However, I would still like to be able to use these methods to visualize networks based on custom lists of genes and have the following questions:

- If I have a single gene of interest, would I be able to use the TOM to select the top n co-expressed genes and create a network related to that gene? I would guess this would be possible by filtering the TOM on the gene of interest and selecting the top n genes with the highest values in the TOM, but want to make sure this is valid.

- Would I be able to do the same thing with multiple genes of interest? For example, if I had two genes of interest would I be able to select a group of top n genes that are jointly co-expressed with both? Could I do this with three or four genes etc?

- Is there any p-value associated with the values in the TOM? If not, is there a way to use hdWGCNA to quantify the co-expression of two genes with a significance level? 

Any help you could provide would be incredibly appreciated and thank you again!

**Comment by smorabit** [comment]
> If I have a single gene of interest, would I be able to use the TOM to select the top n co-expressed genes and create a network related to that gene? I would guess this would be possible by filtering the TOM on the gene of interest and selecting the top n genes with the highest values in the TOM, but want to make sure this is valid.

Yes this is possible.

> Would I be able to do the same thing with multiple genes of interest? For example, if I had two genes of interest would I be able to select a group of top n genes that are jointly co-expressed with both? Could I do this with three or four genes etc?

Yes this is also possible.

> Is there any p-value associated with the values in the TOM? If not, is there a way to use hdWGCNA to quantify the co-expression of two genes with a significance level?

hdWGCNA does not calculate p-values for the TOM. hdWGCNA focuses on network analysis rather than co-expression of specific pairs of genes. In principle you could perform a permutation test to compute p-vals, but it would require a lot of compute resources.

**Comment by sandcell10** [comment]
Hi @smorabit 

Thank you so much for your reply! As a follow up:

- For the first question about the top n co-expressed genes with a single gene of interest, I just want to confirm that the way I would do this would be by filtering the TOM on my gene and selecting the highest n values in the TOM.

- For the second question with multiple genes of interest, how would I go about determining the top jointly co-expressed genes for multiple genes of interest? For example, if I had two genes of interest, would it be valid to filter the TOM on the two genes, add the rows together, and then select the genes that have the highest summed values in the TOM? 

- For the third question, if I identified the top co-expressed genes with my gene of interest with the TOM and then did a pearson correlation using meta cells to see if there is a significant relationship, would that make sense as a way to test for significance?

Thank you again for your helpful information and cheers!

**Comment by smorabit** [comment]
Hi @sandcell10 

> For the first question about the top n co-expressed genes with a single gene of interest, I just want to confirm that the way I would do this would be by filtering the TOM on my gene and selecting the highest n values in the TOM.

Yes you can do this, I recommend looking at the [customized network plots](https://smorabit.github.io/hdWGCNA/articles/network_visualizations.html#customized-network-plots) tutorial.

> For the second question with multiple genes of interest, how would I go about determining the top jointly co-expressed genes for multiple genes of interest? For example, if I had two genes of interest, would it be valid to filter the TOM on the two genes, add the rows together, and then select the genes that have the highest summed values in the TOM?

I have not personally tried doing this so I don't have a specific recommendation.

> For the third question, if I identified the top co-expressed genes with my gene of interest with the TOM and then did a pearson correlation using meta cells to see if there is a significant relationship, would that make sense as a way to test for significance?

Pearson correlation will give you a p-value. However as you might know, p-values are very tricky in the single-cell field, and people generally don't agree on how we should calculate or interpret p-values. Since your goal is to interpret the p-values, I recommend computing pearson correlations at the pseudo-bulk level rather than at the meta-cell or single-cell level, to avoid the pseudoreplication bias (p-val deflation, false discovery, etc).

Hope this helps and happy to answer any more questions.
