### ISSUE TITLE
Best way to skip Metacell construction

### ISSUE THREAD

**Issue by austinschubert** [smorabit/scWGCNA#273]
Hi Sam,

I am attempting to use your package on a dataset from a recent snRNA-seq atlas paper (Langlieb et. al 2023). The investigators sequenced millions of nuclei and then assigned them to ~5k "meta classes". Since I am using those meta classes as my "single cells", it seems like I should not collapse them any further through your MetacellsByGroups function. I can't seem to successfully bypass this step in the tutorial.

I see that the next step, setting up the expression matrix, has the option of  "use_metacells = FALSE" to use the full expression matrix instead. When I run the code this way, things appear to work out.

However, when I move on to the TestSoftPowers function, I get the error message "Error in if "nGenes < 3) { :argument is of length zero". I am interpreting this as me not supplying the proper input for the function. I assume this is a result of skipping the metacell construction, but I am not sure.

Do you have any suggestions?

**Comment by smorabit** [comment]
Hi, I think that this should be feasible. You are basically just trying to replace the metacells with your "meta classes". I am wondering, do you already have a genes by meta-classes matrix, or do you just have the "meta class" assignment for each cell in the Seurat meta-data? Or are you trying to completely avoid using the single-cell dataset?

I just tried running `SetDatExpr` with `use_metacells=FALSE`, and the downstream steps like `TestSoftPowers`are not giving me any errors at this time.

**Comment by austinschubert** [comment]
I was able to figure it out! However, I have run into a new issue. I will send in that question in a new thread so that you can close this one. Thanks!

**Comment by austinschubert** [comment]
I was able to figure it out! However, I have run into a new issue. I will send in that question in a new thread so that you can close this one. Thanks!
