### ISSUE TITLE
dplyr error in PlotModuleTraitCorrelation()

### ISSUE THREAD

**Issue by jhb1980** [smorabit/scWGCNA#276]
Hi -- 

I am encountering an error relating to #268 , but in the default function call `PlotModuleTraitCorrelation()`:

```
> PlotModuleTraitCorrelation(s)
Error in `::`(., dplyr, distinct) : 
  3 arguments passed to '::' which requires 2
```

I checked my hdWGCNA installation, this is up to date (package version: ‘0.3.2’, SHA1: 69110d0a)

**Comment by smorabit** [comment]
Can you update to the latest version and try again?

**Comment by jhb1980** [comment]
The new version fixes the problem -- thank you very much for the fast resolution!
