### ISSUE TITLE
Error in `::`(., dplyr, distinct) :    3 arguments passed to '::' which requires 2

### ISSUE THREAD

**Issue by Xiaojingzhe** [smorabit/scWGCNA#277]
I failed in the last process in polt correlation fig. Lots of thanks for answer
> # Convert intervention_group to factor
> seurat_ref@meta.data$exercise <- as.factor(seurat_ref@meta.data$exercise)
> seurat_ref@meta.data$nCount_RNA <- as.numeric(seurat_ref@meta.data$nCount_RNA)
> seurat_ref@meta.data$nFeature_RNA <- as.numeric(seurat_ref@meta.data$nFeature_RNA)
> cur_traits <- c('exercise','nCount_RNA','nFeature_RNA')
> # Run ModuleTraitCorrelation function
> seurat_ref <- ModuleTraitCorrelation(
+   seurat_ref,
+   traits = cur_traits,
+   group.by='cell_type'
+ )
Warning message:
In ModuleTraitCorrelation(seurat_ref, traits = cur_traits, group.by = "cell_type") :
  Trait exercise is a factor with levels 0, 1. Levels will be converted to numeric IN THIS ORDER for the correlation, is this the expected order?
> # get the mt-correlation results
> mt_cor <- GetModuleTraitCorrelation(seurat_ref)
> head(mt_cor$cor$ASC[,1:5])
                 ASC-M1     ASC-M2      ASC-M3     ASC-M4       ASC-M5
exercise     -0.2249507 -0.1121954 0.002279645 0.04527195  0.003865915
nCount_RNA    0.6800566  0.5046643 0.167160503 0.12609812 -0.042001810
nFeature_RNA  0.7493652  0.5373116 0.251622679 0.08354029 -0.043556864
> names(mt_cor)
[1] "cor"  "pval" "fdr" 
> names(mt_cor$cor)
 [1] "all_cells"     "ASC"           "B"             "DC"            "EC"            "Epi"          
 [7] "Fibroblast"    "Glial"         "ILC"           "Macrophage"    "Mast"          "Monocyte"     
[13] "Neutrophil"    "NK"            "Smooth_Muscle" "T"            
> PlotModuleTraitCorrelation(
+   seurat_ref,
+   label = 'fdr',
+   label_symbol = 'stars',
+   text_size = 2,
+   text_digits = 2,
+   text_color = 'white',
+   high_color = 'yellow',
+   mid_color = 'black',
+   low_color = 'purple',
+   plot_max = 0.2,
+   combine=TRUE
+ )
Error in `::`(., dplyr, distinct) : 
  3 arguments passed to '::' which requires 2

**Comment by Xiaojingzhe** [comment]
I ran the code step by step without any errors, but I still don't know why

# 确保加载必要的包
library(Seurat)
library(dplyr)
library(hdWGCNA)
library(reshape2)
library(ggplot2)

# 假设seurat_ref是你的Seurat对象
# 将exercise转换为因子
seurat_ref@meta.data$exercise <- as.factor(seurat_ref@meta.data$exercise)
seurat_ref@meta.data$nCount_RNA <- as.numeric(seurat_ref@meta.data$nCount_RNA)

# 定义性状
cur_traits <- c('exercise', 'nCount_RNA')

# 运行 ModuleTraitCorrelation 函数
seurat_ref <- ModuleTraitCorrelation(
  seurat_ref,
  traits = cur_traits,
  group.by = 'cell_type'
)

# 获取 mt-correlation 结果
mt_cor <- GetModuleTraitCorrelation(seurat_ref)

# 检查 mt_cor 对象的名称
print(names(mt_cor))

# 手动运行 PlotModuleTraitCorrelation 函数内部的各个部分
cor_list <- mt_cor$cor
pval_list <- mt_cor$pval
fdr_list <- mt_cor$fdr

modules <- GetModules(seurat_ref)
module_colors <- modules %>%
  dplyr::select(c(module, color)) %>%
  dplyr::distinct() %>%
  subset(module != "grey") %>%
  dplyr::arrange(module)
mod_colors <- module_colors$color
module_colors$var <- 1

module_colorbar <- module_colors %>%
  ggplot(aes(x = module, y = var, fill = module)) +
  geom_tile() +
  scale_fill_manual(values = mod_colors) +
  NoLegend() +
  RotatedAxis() +
  theme(
    plot.title = element_blank(),
    axis.line = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title = element_blank(),
    plot.margin = margin(0, 0, 0, 0)
  )

# 定义 label 和 combine 变量
label <- 'fdr'
label_symbol <- 'stars'
text_size <- 2
text_digits <- 2
text_color <- 'white'
high_color <- 'yellow'
mid_color <- 'black'
low_color <- 'purple'
plot_max <- 0.2
combine <- TRUE

plot_list <- list()
for (i in names(cor_list)) {
  cor_mat <- as.matrix(cor_list[[i]])
  pval_mat <- as.matrix(pval_list[[i]])
  fdr_mat <- as.matrix(fdr_list[[i]])
  
  plot_df <- melt(cor_mat)
  colnames(plot_df) <- c("Trait", "Module", "cor")
  
  if (!is.null(label)) {
    if (label == "fdr") {
      p_df <- melt(fdr_mat)
    } else if (label == "pval") {
      p_df <- melt(pval_mat)
    }
    colnames(p_df) <- c("Trait", "Module", "pval")
    plot_df$pval <- p_df$pval
    if (label_symbol == "stars") {
      plot_df$significance <- gtools::stars.pval(plot_df$pval)
    } else if (label_symbol == "numeric") {
      plot_df$significance <- ifelse(plot_df$pval <= 0.05, formatC(plot_df$pval, digits = text_digits), "")
    } else {
      stop("Invalid input for label_symbol. Valid choices are stars or numeric.")
    }
  }
  
  if (is.null(plot_max)) {
    max_plot <- max(abs(range(plot_df$cor)))
  } else {
    max_plot <- plot_max
    plot_df$cor <- ifelse(abs(plot_df$cor) >= plot_max, plot_max * sign(plot_df$cor), plot_df$cor)
  }
  
  p <- ggplot(plot_df, aes(x = Module, y = as.numeric(Trait), fill = cor)) +
    geom_tile() +
    scale_fill_gradient2(
      limits = c(-1 * max_plot, max_plot),
      high = high_color,
      mid = mid_color,
      low = low_color,
      guide = guide_colorbar(ticks = FALSE, barwidth = 16, barheight = 0.5)
    ) +
    scale_y_continuous(
      breaks = 1:length(levels(plot_df$Trait)),
      labels = levels(plot_df$Trait),
      sec.axis = sec_axis(~., breaks = 1:length(levels(plot_df$Trait)), labels = levels(plot_df$Trait))
    ) +
    RotatedAxis() +
    ylab("") +
    xlab("") +
    ggtitle(i) +
    theme(
      plot.title = element_text(hjust = 0.5),
      axis.line = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.y.left = element_blank(),
      axis.title.y = element_text(angle = 0, vjust = 0.5),
      legend.title = element_blank(),
      legend.position = "bottom"
    )
  
  if (!is.null(label)) {
    p <- p + geom_text(label = plot_df$significance, color = text_color, size = text_size)
  }
  
  plot_list[[i]] <- p
}

if (combine) {
  for (i in 1:length(plot_list)) {
    plot_list[[i]] <- plot_list[[i]] +
      ylab(names(plot_list)[i]) +
      theme(
        plot.margin = margin(t = 0, r = 0, b = 0, l = 0),
        axis.title.x = element_blank(),
        plot.title = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y = element_text(angle = 0, vjust = 0.5)
      )
  }
  plot_list[["module"]] <- module_colorbar
  out <- wrap_plots(plot_list, ncol = 1) +
    plot_layout(guides = "collect", heights = c(rep(1, length(plot_list) - 1), 0.15)) +
    plot_annotation(
      theme = theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        legend.justification = 0.5
      )
    )
  print(out)
} else {
  print(plot_list)
}

**Comment by smorabit** [comment]
Hi, thanks for using hdWGCNA. Your issue seems to be the same as #276. Please update to the latest version of hdWGCNA and run your code again, it should now be working.

```
devtools::install_github('smorabit/hdWGCNA', ref='dev')
```

**Comment by Xiaojingzhe** [comment]
Thanks a lot problem solved.
