### ISSUE TITLE
DME vs module trait correlation?

### ISSUE THREAD

**Issue by Paria06** [smorabit/scWGCNA#279]
Hello dear @smorabit,
Sorry for my late response. I will make my question short. I am not sure what is the difference between DME analysis and module trait correlation. For example if I have two variables: group_id (two levels) and region (4 levels) how can I use this tests to know the effect of ALS and how this effect is different in each region. 
Your input would really help me!
Paria

**Comment by smorabit** [comment]
Hi, it appears that there is no text in your GitHub issue, can you please fill in the necessary info for me to understand your problem?

**Comment by Paria06** [comment]
I updated my post.
Many thanks,
Paria
