### ISSUE TITLE
metacells by grouping with two variables (cell type and sample) is not working

### ISSUE THREAD

**Issue by Ruth-hals** [smorabit/scWGCNA#28]
Hi!
Thanks for the great tool! I was trying to construct the metacells by grouping by both 'sample' and 'cell type' using this command;

`brain <- MetacellsByGroups(
  brain,
  group.by = c("celltype","sample"), # specify the columns in seurat_obj@meta.data to group by
  k = 20, # nearest-neighbors parameter
  ident.group = 'celltype' # set the Idents of the metacell seurat object
)`

But I keep getting the following error; do you have an idea of what is going on? If I only group by "celltype" or "sample" than it works perfectly... 

`Error in rownames<-(*tmp*, value = paste0(name, "_", 1:ncol(new_exprs))) : 
  attempt to set 'rownames' on an object with no dimensions`

Thanks!

**Comment by smorabit** [comment]
Hi, thank you for your interest in hdWGCNA!

I am pretty sure I know what's going on. The metacell construction tends to fail when you have a very small number of input cells. I have a feeling that one of your cell type + sample combinations is a very low number of cells. Could you try running this and showing me the result just to see how many cells you have:

```
table(brain$sample, brain$celltype)
```

I will start working on a solution to prevent this issue in the future where the user can tune the minimum number of cells, and groups that are too small will just be skipped.

**Comment by smorabit** [comment]
Hi again,

I added a new parameter to `MeacellsByGroups` called `min_cells` which allows you to exclude very small groupings and should hopefully circumvent your issue. Please install the latest version of hdWGCNA to try out this new parameter. The default value for `min_cells` is 100, and you may wish to increase or decrease this depending on your input data.

**Comment by Ruth-hals** [comment]
Hi,
Thanks for your quick feedback! Indeed, some of the cell type + sample combinations had very low to zero number of cells. By including the min_cells parameter the issue was fixed!
Thank you!
Best,
Ruth
