### ISSUE TITLE
Removing the following groups that did not meet min_cells

### ISSUE THREAD

**Issue by seasonzhao** [smorabit/scWGCNA#281]
Hi,

When I use `MetacellsByGroups` function, I meet this warning message, should I change the threshold of min_cells to keep these groups or just ignore it?

Thank you.

`seurat_obj <- MetacellsByGroups(
   seurat_obj = seurat_obj,
   group.by = c("RNA_snn_res.0.5", "sample"), # specify the columns in seurat_obj@meta.data to group by
   k = 25, # nearest-neighbors parameter
   max_shared = 10, # maximum number of shared cells between two metacells
   ident.group = 'RNA_snn_res.0.5' # set the Idents of the metacell seurat object
 )`

Warning message:
In MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("RNA_snn_res.0.5",  :
  Removing the following groups that did not meet min_cells: 2#WT_untx, 3#WT_untx, 5#Het_12, 5#WT_12, 5#WT_untx, 6#Het_12, 6#KO_12, 6#WT_12, 6#WT_untx, 7#Het_12, 7#KO_12, 7#WT_12, 7#WT_untx

**Comment by smorabit** [comment]
> When I use MetacellsByGroups function, I meet this warning message, should I change the threshold of min_cells to keep these groups or just ignore it?

We don't want to make metacells for very small groups, and that is why they are excluded. If you change the threshold of `min_cells` too low, then the function will likely throw an error. I recommend proceeding from here or removing very small cell clusters before starting hdWGCNA.

**Comment by seasonzhao** [comment]
Thank you so much
