### ISSUE TITLE
Module Correlogram

### ISSUE THREAD

**Issue by Rahul1711arora** [smorabit/scWGCNA#283]
Hi, 

I wanted to ask about the interpretation and the correlation values from the Correlogram plot. 
As I understand, the direction and colour strength is related to the correlation value and the size of the ellipse is bnased on the hME scores as I used that to plot the Correlogram. 
I also understand that these hMEs were calculated on Sample IDs, as I used that argument for grouping by. 

My questions are: 
1. Is the above explanation correct with respect to interpreting the plot?
2.  How can I extract the correlation values for this plot?

I also wanted to ask if it's advisable to run Co-expression networks at the sample level? For example, using the dataset with 4 samples, I found that 4/7 modules have opposite trends in 2 samples and I want to compare these. Would it make sense to generate co-expression networks from these two samples for let's say Inhibitory neurons to compare them? I want to understand the statistical limitations associated with this approach. 

Best,
Rahul

**Comment by smorabit** [comment]
Hi Rahul,

> Is the above explanation correct with respect to interpreting the plot?

This plot just shows correlation, not hME values. This function calls the R package `corrplot`, which you can read about [here](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html).


> How can I extract the correlation values for this plot?

We don't provide a way to extract the correlation values for the plot.

> I also wanted to ask if it's advisable to run Co-expression networks at the sample level? 

This is possible but I can't give specific advice about your project, since I don't know the relevant details. By design hdWGCNA and WGCNA in general are extremely flexible, and it is up to you to choose how you analyze your dataset.

**Comment by Rahul1711arora** [comment]
Hi Sam, 

Thanks for your response. I'll look into the `corrplot`, thanks. Regarding this, when I want to calculate the correlation between the modules, do I use their hME scores to run the calculations? 

> This is possible but I can't give specific advice about your project, since I don't know the relevant details. By design hdWGCNA and WGCNA in general are extremely flexible, and it is up to you to choose how you analyze your dataset.

For this, I meant for example I have a dataset and I think 2 out of 8 samples show interesting pattern of module expression and I would want to compare these two samples wrt how does these two samples differ. So, it should be okay to run hdWGCNA on these two samples independently and extract the relevant modules from both to compare further?

**Comment by smorabit** [comment]
> Regarding this, when I want to calculate the correlation between the modules, do I use their hME scores to run the calculations?

Yes, you can use `GetModuleEigengenes()` to extract the module eigengene values from the seurat object and then you can run the correlations.

> So, it should be okay to run hdWGCNA on these two samples independently and extract the relevant modules from both to compare further?

Yes this seems reasonable.

**Comment by Rahul1711arora** [comment]
Amazing, thank you for your assistance.
