### ISSUE TITLE
scale-free topology and metacells

### ISSUE THREAD

**Issue by Brawni** [smorabit/scWGCNA#29]
Hello again,

This is just an observation rather than a bug but unsure where to post it. I have run two iterations of wgcna on the same dataset using non-overlapping metacells of 50 cells leading to 116 metacells and with 10 cells overlap leading to 1400 metacells. When generating plots to assess the scale-free topology of the first iteration the plot shows a lower highest score compared to the second one (it doens pass the threshold either). This dramatically affect also the number of modules identified with 60+ modules identified in the first case and less than 10 in the second one. When i run pathway enrichment on the module sets I get more meaningful results for the second iteration (almost all of the 60+ modules are not significantly enriched in any pathway). 
I guess my question is how can non-overlapping metacells lead to lower scale-free topology compared to the overlapping ones? Or its just that 116 metacells is not enough data points to construct a robust network?
[Second_iteration_Power_threshold_plots.pdf](https://github.com/smorabit/hdWGCNA/files/8961239/Second_iteration_Power_threshold_plots.pdf)
[First_iteration_Power_threshold_plots.pdf](https://github.com/smorabit/hdWGCNA/files/8961240/First_iteration_Power_threshold_plots.pdf)

Thanks a lot!

**Comment by smorabit** [comment]
Interesting observations! I personally haven't tried running hdWGCNA with 0 overlap in any of my datasets. It could be that 116 metacells isn't enough to construct the network but I would need to do some actual comparisons to try to understand what is going on.
