### ISSUE TITLE
Error in motifscan hdwgcna

### ISSUE THREAD

**Issue by nitinsai1** [smorabit/scWGCNA#291]
Hello,

I used seurat pipeline to analyze single cell RNA-seq dataset. Recently I sarted working on hdWGCNA specific TF Motif analysis. I followed motif analysis tutorial from hdWGCNA. Unfortunately I encountered an error.

I loaded hdwgcna output file .rds for TF analysis
When I executed the following command

seurat_obj <- MotifScan(
  m,
  species_genome = 'mm10',
  pfm = pfm_core,
  EnsDb = EnsDb.Mmusculus.v79
)

It showed an error as follows
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments

Could any one help to solve this error.

Thank you,
Sai

**Comment by smorabit** [comment]
Hi,

Please follow our [new tutorial](https://smorabit.github.io/hdWGCNA/articles/tf_network.html) for motif and transcription factor network analysis. If you have any issues from this, please open a new issue.
