### ISSUE TITLE
HdWGCNA for single Cell ATACseq

### ISSUE THREAD

**Issue by feanaros** [smorabit/scWGCNA#292]
Hi @smorabit,

I would like to know if it is possible to use hdwgcna with single Cell ATAC coverage data instead of the SC RNA-seq expression matrix. How should the metacells function be handled? What do you suggest? I would create peak's modules instead of genes.

Thank you.

**Comment by smorabit** [comment]
Hi @feanaros,

In theory it should be possible to use hdWGCNA with scATAC coverage data. However I have not actually done this before, so I don't have a specific recommendation. You should be able to use the metacell function how we suggest in the scRNA tutorial for hdWGCNA. I think there will be some issues regarding the sparsity of the data, so I worry that you might end up with very few modules detected. However this is just speculation sihnce I haven't done this analysis before. Let me know if you have any specific questions regarding this analysis, and good luck.
