### ISSUE TITLE
Annotations for Visium 10x data in spatial vignette 

### ISSUE THREAD

**Issue by sandcell10** [smorabit/scWGCNA#297]
Hi @smorabit 

I was wondering how you determined the cluster annotations for the Visium 10x data in the spatial hdWGCNA vignette. I understand this data can be downloaded from the 10x genomics website, but I did not see a publication associated with it. 

I was wondering if you obtained these annotations from an outside source or if you determined them yourself. If you did annotate the clusters yourself, how did you go about doing this? Any insight you could provide would be greatly appreciated and thank you for your help!

Cheers

**Comment by smorabit** [comment]
Hi,

For this I did the annotations myself by clustering the dataset with the typical Seurat pipeline, and then I annotated the clusters manually by comparing to the Allen Institute mouse brain atlas.
