### ISSUE TITLE
ModuleNetworkPlot

### ISSUE THREAD

**Issue by dorothyzh** [smorabit/scWGCNA#299]
But when dealing with the bulk RNAseq data, how to use the ModuleNetworkPlot on the objects from WGCNA package? Rather than the seurat object I mean.

**Comment by smorabit** [comment]
Hi,

hdWGCNA is not compatible bulk RNA-seq, you should try using [WGCNA](https://cran.r-project.org/web/packages/WGCNA/index.html) instead.
