### ISSUE TITLE
Error in Tutorial Test

### ISSUE THREAD

**Issue by YunzeZhang19** [smorabit/scWGCNA#303]
I encountered an error while trying to run the basic_tutorial. I used the test data provided by the tutorial and followed the exact instructions. Unfortunately, the program crashed at the step # Test different soft powers:

seurat_obj <- TestSoftPowers(
  seurat_obj,
  networkType = 'signed' # you can also use "unsigned" or "signed hybrid"
)

The message is:
pickSoftThreshold: will use block size 3539.
 pickSoftThreshold: calculating connectivity for given powers...
   ..working on genes 1 through 3539 of 12639

Warning message:
In asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.7 GiB

My memory is 64GB. Should I need to provide additional memory? Thank you for your help.

**Comment by smorabit** [comment]
Hi,

This is a warning message just letting you know how much memory is used, this not an error.
