### ISSUE TITLE
undefined arguments in blockwiseConsensusModules

### ISSUE THREAD

**Issue by Bisho2122** [smorabit/scWGCNA#305]
I don't see the arguments `scaleTOMs`, `scaleQuantile`, and `sampleForScaling` in `WGCNA::blockwiseConsensusModules`. Don't you mean the following params : 

     networkCalibration = c("single quantile", "full quantile", "none"),

     # Simple quantile calibration options

     calibrationQuantile = 0.95,
     sampleForCalibration = TRUE, sampleForCalibrationFactor = 1000,
     getNetworkCalibrationSamples = FALSE`

It seems to be working fine, but I don't see these arguments are being used while debugging `WGCNA::blockwiseConsensusModules`. 

https://github.com/smorabit/hdWGCNA/blob/6cc1546c37e1ae1ed3798ae90b0d75a425aa74b3/R/ConstructNetwork.R#L39

**Comment by smorabit** [comment]
Thanks for pointing this out. It looks like these arguments are used in older versions of WGCNA. For example see the [documentation of this function in version 1.2](https://www.rdocumentation.org/packages/WGCNA/versions/1.20/topics/blockwiseConsensusModules). I am not sure exactly when it changed. 

Later this week I will update `ConstructNetwork` with the correct parameter names, and enforce the appropriate version of WGCNA as a dependency.

**Comment by Bisho2122** [comment]
Thanks for the clarification and sharing the older version. I didn't see this one. 

Feel free to close the issue whenever you update it. I think I made it work internally by providing the updated arguments and it worked. 

Thanks again for providing the package, I am having a lot of fun with it :)

**Comment by smorabit** [comment]
These parameters have been fixed in the newest version of hdWGCNA.
