### ISSUE TITLE
apply for Integrated single-nucleus RNA sequencing

### ISSUE THREAD

**Issue by XiaoyanWang11** [smorabit/scWGCNA#307]
Hi,
I have several samples and integrated them after dimensional reduction(I followed the workflow of https://satijalab.org/seurat/articles/seurat5_integration.html in seurat v4).

Can I apply this hdWGCNA workflow to my dataset directly?

Thank you!

**Comment by smorabit** [comment]
Yes you can apply hdWGCNA to intetgrated datasets.

**Comment by XiaoyanWang11** [comment]
> Yes you can apply hdWGCNA to intetgrated datasets.

Ok. Thank you.
