### ISSUE TITLE
"Error in if (!check) { : argument is of length zero" for metacell construction

### ISSUE THREAD

**Issue by shiave** [smorabit/scWGCNA#313]
I keep receiving "Error in if (!check) { : argument is of length zero" for metacell construction" when I run the code below:
seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("CellType","sample"), # specify the columns in seurat_obj@meta.data to group by
  reduction = 'harmony', # select the dimensionality reduction to perform KNN on
  k = 25, # nearest-neighbors parameter
  max_shared = 10, # maximum number of shared cells between two metacells
  ident.group = 'orig.ident', # set the Idents of the metacell seurat object
)

I ran this code before to set up seurat_obj (and got no errors):
seurat_obj <- SetupForWGCNA(
  rds,
  wgcna_name = "tutorial" # the name of the hdWGCNA experiment
)

For reference, rds is my rds file,  "sample" is the condition group and "orig.ident" is the sample name. I've checked that those are all valid columns in the rds file and harmony is showing up as a reduction option when I run Reductions(seurat_obj).  Any idea why I might be getting this error?

@smorabit

**Comment by smorabit** [comment]
Hi, 

Unfortunately, I am not exactly sure what is going on here to cause this error message. One potential problem that I see, is that `ident.group` should be one of the same groups used for `group.by`. The function `MetacellsByGroups` includes a check for this, so I am surprised that it doesn't get caught when you run it. For example I ran this:

```

seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("cell_type", "Sample"),
  reduction = 'harmony', 
  k = 25, 
  max_shared = 10, 
  ident.group = 'orig.ident' 
)
```

```
Error in MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("cell_type",  : 
  ident.group must be in group.by
```

In my case, the correct way to run this is to change `ident.group="orig.ident"` to `"cell_type"` or `"sample"`.

Can you please try this? I am also curious, what version of hdWGCNA are you using?

**Comment by shiave** [comment]
Hi, 

Thank you for your response! You're right, when I switched ident.group to CellType, I got the error you mentioned above. I was finally able to get this step to work by running the code below:

seurat_obj <- RunHarmony(
  object = seurat_obj,
  group.by.vars = "sample"  
)
seurat_obj <- SCTransform(seurat_obj)

data_sct <- seurat_obj[["SCT"]]@data

seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("CellType", "sample"),
  reduction = 'harmony', 
  k = 25, 
  max_shared = 10, 
  assay = 'SCT',  # Using the SCT assay
  slot = 'data',  # Accessing the data slot
  ident.group = 'CellType'
