### ISSUE TITLE
How to separately produce the Correlation Heatmap?

### ISSUE THREAD

**Issue by levinhein** [smorabit/scWGCNA#32]
Hello! May I kindly ask how to separately produce the correlation heatmap found at the end of this tutorial? https://smorabit.github.io/hdWGCNA/articles/module_trait_correlation.html 

The issue is, I have a number of `cur_traits`, so it got so messy when all the plots are simultaneously created. Maybe, plotting each cell types (e.g. all_cells, INH, OPC, EX, etc) will solve this issue.

**PLOT CORRELATION HEATMAP**

```
PlotModuleTraitCorrelation(
  seurat_obj,
  label = 'fdr',
  label_symbol = 'stars',
  text_size = 2,
  text_digits = 2,
  text_color = 'white',
  high_color = 'yellow',
  mid_color = 'black',
  low_color = 'purple',
  plot_max = 0.2,
  combine=TRUE
)
```

**Tutorial's plot with 8 cur_traits:** 
![image](https://user-images.githubusercontent.com/68268222/179396572-43c52989-f6fc-48f9-83ca-bacebd8a7801.png)

**My data with 20 cur_traits:**
![image](https://user-images.githubusercontent.com/68268222/179396540-b3c34189-69f8-4a87-8cbf-b6d7c400668e.png)

**Comment by smorabit** [comment]
I think you want to use `combine=FALSE` in your call to `PlotModuleTraitCorrelation`, or you can just increase the height of your plot.

**Comment by Xiaojingzhe** [comment]
hello, I don't know why encountered this error, a lot thanks for an answer
> PlotModuleTraitCorrelation(
+   seurat_ref,
+   label = 'fdr',
+   label_symbol = 'stars',
+   text_size = 2,
+   text_digits = 2,
+   text_color = 'white',
+   high_color = 'yellow',
+   mid_color = 'black',
+   low_color = 'purple',
+   plot_max = 0.2,
+   combine=TRUE
+ )
Error in `::`(., dplyr, distinct) : 
  3 arguments passed to '::' which requires 2

**Comment by smorabit** [comment]
Hi @Xiaojingzhe, I replied to your other issue #277 with the solution. In general, we want to organize GitHub issues so they are very specific, so in the future please write a new issue instead of commenting on an unrelated issue. Also, please use the search function to see if anybody else had the same issue as you, becasue there might already be a solution.
