### ISSUE TITLE
Could not find function ConstructPseudobulk: has it been removed?

### ISSUE THREAD

**Issue by ExctOcean** [smorabit/scWGCNA#320]
**ERROR When Running ConstructPseudobulk()**
I'm trying to use hdWGCNA on Psuedobulk for Co-expression network analysis.

**When i tried to use ConstructPseudobulk, i got an ERROR**
![image](https://github.com/user-attachments/assets/9196ac11-ed0f-444f-b227-faf0fcc5f6c1)

**I have confirmed that my package is updated to the latest version (hdWGCNA-0.300, which updated in 2024.2.28).**

```
library(hdWGCNA)
> packageVersion('hdWGCNA')
[1] ‘0.4.0’
> ConstructPseudobulk(
+   seurat_obj,
+   group.by = 'cell_type',
+   replicate_col = 'DataSet',
+   assay = 'RNA',
+   slot = 'counts', # this should always be counts!
+   min_reps = 10
+ )
Error in ConstructPseudobulk(seurat_obj, group.by = "cell_type", replicate_col = "DataSet",  : 
  could not find function "ConstructPseudobulk"
```

why do I have this error? What could be the issue? 
![image](https://github.com/user-attachments/assets/2f2f274a-28eb-450c-8bf0-889c2b8e14eb)
Has this function been removed in the latest version? If so, how can I replace this function?

**Comment by smorabit** [comment]
Somehow this function wasn't being properly exported. I just fixed it, so please re-install hdWGCNA and try it again. It worked for me when I tested it just now after re-installing.

**Comment by ExctOcean** [comment]
> Somehow this function wasn't being properly exported. I just fixed it, so please re-install hdWGCNA and try it again. It worked for me when I tested it just now after re-installing.不知何故，这个函数没有被正确导出。我刚刚修复了它，所以请重新安装 hdWGCNA 并重试。当我重新安装后刚刚测试它时，它对我有用。

My problem has been resolved, thank you!
