### ISSUE TITLE
Error in ConstructTFNetwork(seurat_obj) :    argument "model_params" is missing, with no default

### ISSUE THREAD

**Issue by come-on-j** [smorabit/scWGCNA#321]
When I run the script: seurat_obj <- ConstructTFNetwork(seurat_obj),  an error was displayed:  argument "model_params" is missing, with no default. Model_paramis a list of model parameters to pass to xgboost.  But I cann't find the model_params in Data.

**Comment by smorabit** [comment]
`ConstructTFNetwork` requires you to pass the `model_params`, so there is not necessarily a default. I updated the tutorial so that this is more clear.

```
# define model params:
model_params <- list(
    objective = 'reg:squarederror',
    max_depth = 1,
    eta = 0.1,
    nthread=16,
    alpha=0.5
)

# construct the TF network
seurat_obj <- ConstructTFNetwork(seurat_obj, model_params)
```
