### ISSUE TITLE
PlotModuleTraitCorrelation for one trait

### ISSUE THREAD

**Issue by shiave** [smorabit/scWGCNA#322]
Hi, I'm trying to check one trait (treatment vs control) against the MEs to figure out which modules show strong correlation with the trait. When I try this code:

seurat_obj$group1 <- factor(seurat_obj$group1, levels = c("AV", "MV"))

cur_traits <- c('group1')

seurat_obj <- ModuleTraitCorrelation(
  seurat_obj,
  traits = cur_traits 
)

PlotModuleTraitCorrelation(
  seurat_obj,
  label = 'fdr',
  label_symbol = 'stars',
  text_size = 2,
  text_digits = 2,
  text_color = 'white',
  high_color = 'yellow',
  mid_color = 'black',
  low_color = 'purple',
  plot_max = 0.2,
  combine=TRUE
)

I get this error:
Error in PlotModuleTraitCorrelation(seurat_obj, label = "fdr", label_symbol = "stars",  : 
  ModuleTraitCorrelation was run only for one trait. Heatmaps are not suggested for visualizing only one variable!

**So what is another method I could use to check the correlation?**

Some background: We have a treatment group and control group and the seurat object has many brain cell clusters (group column). We only want to look into the microglia group so I ran the following functions on just microglia earlier in my code:

seurat_obj <- SetDatExpr(
  seurat_obj,
  group_name = "Microglia", # the name of the group of interest in the group.by column
  group.by='cluster_id', # the metadata column containing the cell type info. 
  assay = 'RNA', # using RNA assay
  slot = 'counts' # using normalized data
)

# compute eigengene-based connectivity (kME):
seurat_obj <- ModuleConnectivity(
  seurat_obj,
  group.by = 'cluster_id', group_name = 'Microglia'
)

I'm confused about whether this impacts my final correlations when I look at traits versus module eigengene (I don't think it does but I want to make sure).

**Comment by smorabit** [comment]
Hi,

Based on what you are saying:

> Some background: We have a treatment group and control group and the seurat object has many brain cell clusters (group column). We only want to look into the microglia group so I ran the following functions on just microglia earlier in my code:

Instead of module trait correlation I suggest that you run [differential module eigengene analysis](https://smorabit.github.io/hdWGCNA/articles/differential_MEs.html) to compare treatment vs control.
