### ISSUE TITLE
Error in if (!(multi.group.by %in% names(seurat_obj@meta.data))) { :    argument is of length zero

### ISSUE THREAD

**Issue by xiaoli-gg** [smorabit/scWGCNA#328]
When I try to construct metacells  in each group, I meet the error below.

```
> unique(seurat_obj@misc[["tutorial"]][["wgcna_metacell_obj"]]@meta.data$cell_type)
 [1] "0" "1" "2" "3" "4" "5" "6" "7" "8" "9"
> seurat_obj <- SetDatExpr(
+   seurat_obj,
+   group_name = c("4"), # the name of the group of interest in the group.by column
+   group.by='cell_type', # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups
+   assay = 'RNA', # using RNA assay
+   slot = 'data' # using normalized data
+ )
Error in if (!(multi.group.by %in% names(seurat_obj@meta.data))) { : 
  argument is of length zero
```
I don't know how to solve this error, I will be grateful if someone tell me how to solve this issue.

**Comment by smorabit** [comment]
Can you please show the other code that you ran before this?

**Comment by NWU-psp** [comment]
hello hello这个问题解决了吗

**Comment by xiaoli-gg** [comment]
```
# 用seurat4版本就不会报错
# remotes::install_version("SeuratObject", "4.1.4", lib="/home/gg/rpackage", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
# remotes::install_version("Seurat", "4.4.0", lib="/home/gg/rpackage", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
.libPaths(c("/home/gg/rpackage",.libPaths()))
unloadNamespace('infercnv')
library(hdWGCNA)
```

**Comment by NWU-psp** [comment]
我的seurat是4.4.0，seuratobject是4.1.4，可还是报一样的错。。。。快疯了

**Comment by smorabit** [comment]
I can try to help if you show the code that you are running.

**Comment by NWU-psp** [comment]
> I can try to help if you show the code that you are running.
  
The following is my code, all from the WGCNA official website, and scRNA.cd8 is the seurat object of the cd8 T cell that I want to analyze

library(WGCNA)
#devtools::install_github('smorabit/hdWGCNA'ref='dev')、
library(hdWGCNA)

  theme_set(theme_cowplot()) 
  set.seed(12345) #set random seed for reproducibility
  enableWGCNAThreads(nThreads = 8) #optionally enable multithreading
  
  seurat.object <- SetupForWGCNA(
    scRNA.cd8,
    gene_select = "fraction", # the gene selection approach
    fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
    wgcna_name = "tutorial" # the name of the hdWGCNA experiment
  )
  
# construct metacells  in each group
  seurat.object <- MetacellsByGroups(
    seurat_obj = seurat.object,
    group.by = c("celltype", "Sample"), # specify the columns in seurat_obj@meta.data to group by
    reduction = 'harmony', # select the dimensionality reduction to perform KNN on
    k = 25, # nearest-neighbors parameter
    max_shared = 10, # maximum number of shared cells between two metacells
    ident.group = 'celltype' # set the Idents of the metacell seurat object
  )
  
  # normalize metacell expression matrix:
  seurat.object <- NormalizeMetacells(seurat.object)

  ##共表达网络分析#构建表达矩阵
  seurat_obj <- SetDatExpr(
    seurat.object,
    group_name = "CD8_Teff_GZMK", # the name of the group of interest in the group.by column
    group.by='celltype', # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups
    assay = 'RNA', # using RNA assay
    slot = 'data' # using normalized data
  )

Error in if (!(multi.group.by %in% names(seurat_obj@meta.data))) { : 
  argument is of length zero

Here is my version of the R package： Seurat 4.3.0  ，SeuratObject 4.1.4 , SeuratData 0.2.2

I read a lot of tutorials but it doesn't work. If you can give me some help, I would be very grateful. By the way, Barcelona is really beautiful and Barca is my favorite team  hahaha

**Comment by smorabit** [comment]
Thank you for sending the code. One more question, what version of hdWGCNA are you running? I went to look at the sourcecode to find the line of code that is causing the error

`if (!(multi.group.by %in% names([seurat_obj@meta.data](mailto:seurat_obj@meta.data))))`

however it does not seem to be in the current version of hdWGCNA, it was probably changed.

**Comment by NWU-psp** [comment]
Thank you for your reply. The hgwgcna version I use is 0.2.22

**Comment by NWU-psp** [comment]
I know what the problem is, I updated my R package version 0.4.00, this problem has been solved, thank you very much！！！！！
