### ISSUE TITLE
github installation broken?

### ISSUE THREAD

**Issue by philippstb** [smorabit/scWGCNA#329]
Hi could it be that the github download is somehow broken? 

```
> devtools::install_github('smorabit/hdWGCNA', ref='dev')
Downloading GitHub repo smorabit/hdWGCNA@dev
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/smorabit/hdWGCNA/tarball/dev' failed
```

**Comment by smorabit** [comment]
Hi,

I just tested this and it works on my end, so it seems unlikely that this is a problem with hdWGCNA. It seems like a problem with devtools or maybe your installation of R.

**Comment by philippstb** [comment]
thank you, I will try to figure it out!

**Comment by smorabit** [comment]
Another user had a similar issue and it seems like there is a workaround, please check #335
