### ISSUE TITLE
Error in...    p <- DotPlot(seurat_obj, mods, group.by = 'cell_type')

### ISSUE THREAD

**Issue by levinhein** [smorabit/scWGCNA#33]
Hello. I got an error on making this dotplot. Do you have any suggestion on how to solve this? My `cell_type` label is `cellstates`. Thank you! 

**TUTORIAL SAMPLE:**
![image](https://user-images.githubusercontent.com/68268222/179399112-a6c1eec0-0aae-4751-a226-b376b110e8fc.png)

**MY RUN**
![image](https://user-images.githubusercontent.com/68268222/179399261-caae0065-f6e3-4478-8153-42eea79a8fff.png)

![image](https://user-images.githubusercontent.com/68268222/179399142-0495ec0c-73d8-49e9-a8b5-85ba5d2dacc1.png)
**Error in if (!value %in% names(x = slot(object = object, name = "assays"))) { : 
  the condition has length > 1**

**Comment by smorabit** [comment]
DId you add the MEs to the `@meta.data` slot for the Seurat object?

```
# get hMEs from seurat object
MEs <- GetMEs(seurat_obj, harmonized=TRUE)
mods <- colnames(MEs); mods <- mods[mods != 'grey']

# add hMEs to Seurat meta-data:
seurat_obj@meta.data <- cbind(seurat_obj@meta.data, MEs)
```

Ultimately this is an issue arising from with Seurat function `DotPlot`, which is not part of the hdWGCNA pacakge, so you might have better luck opening an issue on the Seurat github..
