### ISSUE TITLE
Analysis of changes in co-expression patterns

### ISSUE THREAD

**Issue by amingson** [smorabit/scWGCNA#330]
Dear Authors,
I hope this email finds you well. I would like to express my sincere gratitude to your team for developing the tool that has been of great assistance to me.
Currently, I'm facing an issue. I aim to extract the co-expressed genes on malignant cells from the single-cell data of tumor samples. However, these genes should not be co-expressed on normal cells such as immune cells and stromal cells. I'm wondering how I can conduct the analysis to achieve this goal.
I really hope to receive your kind help.

Best regards,
Anler

**Comment by smorabit** [comment]
Hi Anler, thank you for your interest in hdWGCNA. It seems like you are asking for advice on the best way to run hdWGCNA for your dataset, is this correct?

> I aim to extract the co-expressed genes on malignant cells from the single-cell data of tumor samples. However, these genes should not be co-expressed on normal cells such as immune cells and stromal cells.

There are multiple ways that you could achieve this goal, and I will suggest one. First I suggest running the [hdWGCNA pipeline](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html) on the malignant cell fraction of your dataset. After you construct the network, you can check the expression level of these co-expression modules in the other cell populations (immune, stromal, etc) to identify which modules are exclusive to the malignant. Typically in this analysis you will identify modules that may be expressed across multiple cell types.

**Comment by amingson** [comment]
> Hi Anler, thank you for your interest in hdWGCNA. It seems like you are asking for advice on the best way to run hdWGCNA for your dataset, is this correct?
> 
> > I aim to extract the co-expressed genes on malignant cells from the single-cell data of tumor samples. However, these genes should not be co-expressed on normal cells such as immune cells and stromal cells.
> 
> There are multiple ways that you could achieve this goal, and I will suggest one. First I suggest running the [hdWGCNA pipeline](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html) on the malignant cell fraction of your dataset. After you construct the network, you can check the expression level of these co-expression modules in the other cell populations (immune, stromal, etc) to identify which modules are exclusive to the malignant. Typically in this analysis you will identify modules that may be expressed across multiple cell types.


Thank you very much for your quick reply, I will try it according to your suggestion. I wish you a happy life.

Best,
Anler
