### ISSUE TITLE
Question about dendrogram plot

### ISSUE THREAD

**Issue by laterz-f** [smorabit/scWGCNA#332]
Hi there,
Thanks for developing this fantastic tool.
I have a general question on the interpretation of the dendrogram plot showing co-expression modules. Can the dendrogram give information on relationships between modules? In other words, is there a way to establish whether two gene modules could be part of the same “bigger” module if cutting the tree differently?

**Comment by smorabit** [comment]
Hi,

Yes the dendrogram does show some relationships between modules. You can mess around with the tree cutting parameters to achieve different results in terms of how the dendrogram results in the final modules.
