### ISSUE TITLE
Error in utils::download.file(url, path, method = method, quiet = quiet,  :    download from 'https://api.github.com/repos/smorabit/hdWGCNA/tarball/dev' failed

### ISSUE THREAD

**Issue by Sara-Tavallaei** [smorabit/scWGCNA#335]
Hi,

I need to update my hdWGCNA package to the version 0.4.00 immediately to do Transcription factor regulatory network analysis;
but after using both of the two following codes I got this error:

`devtools::install_github('smorabit/hdWGCNA', ref='dev')`
> Downloading GitHub repo smorabit/hdWGCNA@dev
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/smorabit/hdWGCNA/tarball/dev' failed

`remotes::install_github("smorabit/hdWGCNA")`
> Downloading GitHub repo smorabit/hdWGCNA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/smorabit/hdWGCNA/tarball/HEAD' failed

it's 3 days I'm trying these codes on both mac & linux and don't work.

Would you please share the 0.4.00 hdWGCNA package tar.gz file via your github repository ?

Thanks for any help!!

**Comment by smorabit** [comment]
Hi,

Sorry that you are having trouble with downloading the package. It seems like this is likely a problem with devtools, or maybe a problem with github itself. I am not sure if this will work, but you can try to clone the hdWGCNA repository and then run `devtools::install_local`.

**Comment by Sara-Tavallaei** [comment]
> Hi,
> 
> Sorry that you are having trouble with downloading the package. It seems like this is likely a problem with devtools, or maybe a problem with github itself. I am not sure if this will work, but you can try to clone the hdWGCNA repository and then run `devtools::install_local`.

Thanks!
It worked.
