### ISSUE TITLE
hdWGCNA (found a mistake in this code)

### ISSUE THREAD

**Issue by GudaLab** [smorabit/scWGCNA#336]
Hi Dr. Swarup,
I am Sankarasubramanian Jagadesan,  Bioinformatics scientist at UNMC. While working with your code, [https://smorabit.github.io/hdWGCNA/index.html](https://urldefense.com/v3/__https:/smorabit.github.io/hdWGCNA/index.html__;!!CzAuKJ42GuquVTTmVmPViYEvSg!OZKBAvH5dGV9lQJvpScqo3KJB4anAXK_w-PIBcyXM8KqAEQFWd0J6ujxxg7QGixHR-0A47VUyiItJN9dRsI2uA$), I found a mistake on this page, and I plan to notify you, which will help other researchers. 
 
# access the results:
pos_regulon_scores <- [GetRegulonScores](https://urldefense.com/v3/__https:/smorabit.github.io/hdWGCNA/reference/GetRegulonScores.html__;!!CzAuKJ42GuquVTTmVmPViYEvSg!OZKBAvH5dGV9lQJvpScqo3KJB4anAXK_w-PIBcyXM8KqAEQFWd0J6ujxxg7QGixHR-0A47VUyiItJN9h95KROw$)(seurat_obj, target_type='positive')
neg_regulon_scores <- [GetRegulonScores](https://urldefense.com/v3/__https:/smorabit.github.io/hdWGCNA/reference/GetRegulonScores.html__;!!CzAuKJ42GuquVTTmVmPViYEvSg!OZKBAvH5dGV9lQJvpScqo3KJB4anAXK_w-PIBcyXM8KqAEQFWd0J6ujxxg7QGixHR-0A47VUyiItJN9h95KROw$)(seurat_obj, target_type='negative')
 
# select a TF of interest
cur_tf <- 'RUNX2'
 
# add the regulon scores to the Seurat metadata
seurat_obj$pos_regulon_score <- pos_regulon_scores[,cur_tf]
seurat_obj$neg_regulon_score <- pos_regulon_scores[,cur_tf]
 
Need to be changed as
seurat_obj$neg_regulon_score <- neg_regulon_scores[,cur_tf]
Thanks,
Subu

**Comment by smorabit** [comment]
Thank you I will edit the tutorial to fix this in the next update.
