### ISSUE TITLE
WGCNA modules and Seurat cluster association 

### ISSUE THREAD

**Issue by joe-jhou2** [smorabit/scWGCNA#36]
When I focus on a few seurat clusters, the intuitive question I want to address through WGCNA is, how modules explain the seurat clusters, otherwise. Is there possible that plot the correlation heatmap to display the module-cluster relationship (similar to the module-trait correlation in the original WGCNA tutorial)? Thanks.

**Comment by smorabit** [comment]
To associate co-expression modules with certain cell populations, you can inspect the activity of co-expresison modules in different cell populations using `ModuleFeaturePlot`, or you can visualize as a dot plot or violin plot using the Seurat functions `DotPlot` and `VlnPlot` as shown in the [hdWGCNA basics tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html#basic-visualization). Beyond that, you are free to take advantage of the rich plotting ecosystem within R to make a custom visualization.

**Comment by joe-jhou2** [comment]
In DotPlot, I got this on my data. It looks so bizarre, as I included all sub-clusters for WGCNA, but only "Proliferating T" is highly expressed across all modules. is that indicating some technical mistake I've made? 
![plot_zoom_png](https://user-images.githubusercontent.com/4881411/180492835-1ae3b59b-38de-480f-a7c1-86134302d91e.jpg)

**Comment by smorabit** [comment]
There could be a technical mistake, not sure just from looking at this plot. Please make a new issue with a more specific inquiry and the relevant code if you would like to discuss further.
