### ISSUE TITLE
error in metacell construction

### ISSUE THREAD

**Issue by nfancy** [smorabit/scWGCNA#37]
Hi, 

Thanks you very much for this nice package. I am trying to run the following on my dataset, however I get the following error:
```
seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("manifest", "monocle_clusters"), # specify the columns in seurat_obj@meta.data to group by
  k = 20, # nearest-neighbors parameter
  max_shared = 10, # maximum number of shared cells between two metacells
  ident.group = "monocle_clusters", # set the Idents of the metacell seurat object
  min_cells = 100
)
```

```
Error in strsplit(run_stats$name, "#") : non-character argument
```

I converted both my manifest and monocle_clusters column into `character`, still not working. I think it's perhaps coming from this bit of code from `metacells.R` function line 327-329 but can't debug anymore.

```
for(i in 1:length(group.by)){
    run_stats[[group.by[i]]] <- do.call(rbind, strsplit(run_stats$name, '#'))[,i]
  }
```

Any help is highly appreciated. 

Thanks
Nurun

**Comment by nfancy** [comment]
Hi solved it by adding `as.character` in the line

```
for(i in 1:length(group.by)){
    run_stats[[group.by[i]]] <- do.call(rbind, strsplit(as.character(run_stats$name), '#'))[,i]
  }
```

**Comment by smorabit** [comment]
Thank you for catching this, I added this line in the most recent version.
