### ISSUE TITLE
error in ModuleEigengenes function

### ISSUE THREAD

**Issue by nfancy** [smorabit/scWGCNA#39]
Hi,

Thank you for this great package, I could successfully build the network but is getting an error at this stage.

```
seurat_obj <- ModuleEigengenes(
  seurat_obj,
  group.by.vars="manifest"
  #modules = seurat_obj@misc$enriched_micro$wgcna_modules,
  #vars.to.regress = c("nCount_RNA", "pc_mito", "sex", "PMI", "age"),
  #assay = "RNA"
 )
[1] "grey"
Centering and scaling data matrix
 |===========================================================================================| 100%
Error in data.use[features, ] : subscript out of bounds
```

I checked the code and tried to execute the individual commands an it seems all the genes are present, not sure, why it's giving the subscript out of bounds error. Any help is appreciated.

Best wishes
Nurun

**Comment by smorabit** [comment]
Can you update to the most recent version of hdWGCNA and try again?

```
devtools::install_github('smorabit/hdWGCNA', ref='dev')
```

**Comment by nfancy** [comment]
thanks, I'll try.

**Comment by nfancy** [comment]
Hi, sorry to reopen, the issue still persists.

**Comment by nfancy** [comment]
Hi, I believe, I've debugged the issue. You will need `as.character` at line 520 in this https://github.com/smorabit/hdWGCNA/blob/dev/R/WGCNA_functions.R function. As when the gene names as factor this creates the issue.

```
 cur_genes <- modules %>% subset(module == cur_mod) %>% .$gene_name
```

```
 cur_genes <- as.character(modules %>% subset(module == cur_mod) %>% .$gene_name)
```

**Comment by smorabit** [comment]
I added `as.character` as you suggested in the latest version.
