### ISSUE TITLE
Module Trait Correlation

### ISSUE THREAD

**Issue by xiang-cy** [smorabit/scWGCNA#40]
Hello,

Thank you for this wonderful package!
I wanna do a correlation between cell clusters and modules, should I add cell clusters into metadata? And what data should I add into?

Best wishes!

**Comment by smorabit** [comment]
So I am guessing you want to identify which module is expressed in each cluster? It doesn't really make sense to do a correlation in that case. You just want to inspect the module eigengene in each cluster. You can do this using `DotPlot` or `VlnPlot` with Seurat or you can use `ModuleFeaturePlot`. Examples of how to do that are in the [basics tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html).

**Comment by xiang-cy** [comment]
> So I am guessing you want to identify which module is expressed in each cluster? It doesn't really make sense to do a correlation in that case. You just want to inspect the module eigengene in each cluster. You can do this using `DotPlot` or `VlnPlot` with Seurat or you can use `ModuleFeaturePlot`. Examples of how to do that are in the [basics tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html).

**Comment by xiang-cy** [comment]
Thanks for your reply, help me a lot! And there is another double that ModuleFeaturePlot or DotPlot in the basics tutorial plot using hME, which can represent the real expression of module genes in samples?  
Best wishes!

**Comment by xiang-cy** [comment]
> So I am guessing you want to identify which module is expressed in each cluster? It doesn't really make sense to do a correlation in that case. You just want to inspect the module eigengene in each cluster. You can do this using `DotPlot` or `VlnPlot` with Seurat or you can use `ModuleFeaturePlot`. Examples of how to do that are in the [basics tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html).

Thanks for your reply, help me a lot! And there is another double that ModuleFeaturePlot or DotPlot in the basics tutorial plot using hME, which can represent the real expression of module genes in samples?
Best wishes!
