### ISSUE TITLE
error while running MetacellsByGroups

### ISSUE THREAD

**Issue by HJ234** [smorabit/scWGCNA#42]
Hi! Thank you for the great package. 

I got an error while running MetacellsByGroups:
```
> Pilot <- MetacellsByGroups(seurat_obj=Pilot, group.by=c("Celltype","Pool"), k = 25, ident.group="Celltype", max_shared=10, min_cells=50)
Error in if (sparse && !sM) data <- as(data, "sparseMatrix") else if (!sparse) { : 
  missing value where TRUE/FALSE needed
```

Would you know why this error occurs? My dataset includes some cell types with very low cell counts, so I also tried this with only a few cell types with sufficient cell counts (>100), but the same error occurred.

**Comment by smorabit** [comment]
Can you replicate the error on the tutorial dataset?

**Comment by HJ234** [comment]
Hi, Thank you for the quick reply.

I ran the tutorial with the given data set after FindVariableFeatures(seurat_obj), ScaleData(seurat_obj) and RunPCA(seurat_obj), and MetacellsByGroups ran without an error.

The initial error seems to occur because I'm using a list of genes for the features in SetupForWGCNA. Instead of 'gene_select=fraction', I used 'features=genes' with a custom list of 3000 genes like the following.

`pilot4 <- SetupForWGCNA(pilot4, features=genes, wgcna_name="test3000")`

**Comment by HJ234** [comment]
I figured out the problem. The active.assay was not RNA and it was a smaller set of genes.
When I changed the active.assay to RNA, and ran SetupForWGCNA with my list of genes, it worked. 
Thank you for the quick reply and sorry if you spent time on it.
