### ISSUE TITLE
kME calculating issue

### ISSUE THREAD

**Issue by Dimmiso** [smorabit/scWGCNA#44]
Hi,
I started looking to individual genes within individual modules and seem to bump on counterintuitive outcome. Below I put a series of UMAP plots showing profile of module ”black” as well as some genes which are included in this module. This module has absolutely dominating signal in one of the clusters. Since it is my domain knowledge, I know that gene PVALB is strong canonical marker of this cluster. In agreement with this PVALB profile looks almost identical to module ”black” profile on the same UMAP. Now if I look on genes contributing black modules (by kEM), PVALB is indeed among them but has rank as "low" as 17 with kEM value 0.13058. It seems on the other hand that pattern of some genes from the top of black module list, like EDIL3 and REEP5 (ranked 1 and 8) has very little to do with black module profile. On the contrary PVALB and GPRC5B seem to have pattern almost identical to black module pattern, but they have ranks 17 and 20 in this list.

![This is an image](https://drive.google.com/file/d/1bAEGXxqFCbm15aGlN2qRt73gJmqLvOGO/view?usp=sharing)

I assume that top genes (with high kEM) in each module list should be the ones with have strong correlation with the eigengene corresponding module? Either I miss something, or things do not fit. Can you, please, check? 
Under this link https://drive.google.com/drive/folders/1MNI5Oq946HfZm23MoFE3wu-JfH0YMkQU?usp=sharing
you will find four files: the R code, input workspace, output workspace and sysinfo.
Thank you very much for your support!
Best
Dmitry

**Comment by Dimmiso** [comment]
HI, sorry, it did not work to attach the plot, it is now in the same google drive folder. Thanks!

**Comment by smorabit** [comment]
Hi Dmitry,

The kMEs are computed using [biweight mid-correlation](https://en.wikipedia.org/wiki/Biweight_midcorrelation), whereas you may have been expecting Pearson or something else. So for PVALB, it's essentially computed like this:

```
cur_exp <- GetAssayData(seurat_obj, slot='data')['PVALB',]
MEs <- GetMEs(seurat_obj)

# this is the kME value for PVALB and the black module
bicor(cur_exp, MEs$black)
```

The bicor results for this are `0.1305` while the pearson correlation computed as `cor(cur_exp, MEs$black)` results in `0.8115`, so that may be more along the line of what you expected?

I added new options to `ModuleConnectivity` to allow for different correlations if you choose. For pearson correlation:

```
# kME plot /histogram of individual gene correlation to module eigengenes (?)
seurat_obj <- ModuleConnectivity(
  seurat_obj,
  group.by='clust.real',
  group_name = names(table(seurat_obj$clust.real)),
  corFnc = 'cor'
)
```

For spearman:

```
seurat_obj <- ModuleConnectivity(
  seurat_obj,
  group.by='clust.real',
  group_name = names(table(seurat_obj$clust.real)),
  corFnc = 'cor',
  corOptions = "use = 'p', method = 'spearman'"
)
```

Hope this makes sense. Please update to the latest version of hdWGCNA if you want to use the new correlation options.

**Comment by Dimmiso** [comment]
Hi Sam, 
thanks a lot for fixing it, it works very well! I compared now different ways to calculate genes kME and based on visual comparison of module pattern and individual gene patterns on UMAP, Pearson correlation outperforms spearman, at least for my dataset. Bircor is worst. I agrees that it is counter intuitive.  Thanks a lot! Dmitry
