### ISSUE TITLE
Minimum number of sample sizes for hdWGCNA?

### ISSUE THREAD

**Issue by Sudolin** [smorabit/scWGCNA#49]
Hi, thank you very much for such a great  tool.
I am wondering if there is any requirment for hdWGCNA in terms of the minimum number of sample sizes.
Thanks in advance.

**Comment by smorabit** [comment]
Hi,

To clarify, hdWGCNA does not require a minimum sample size. However, hdWGCNA will not provide good results if there are too few cells in your dataset. Unfortunately, I am not sure exactly what the minimum number of cells should be. I typically will try for at least 500 cells, but that number is completely arbitrary and I haven't done any thorough testing to figure out a minimum.

**Comment by Sudolin** [comment]
Thank you for your response.
