### ISSUE TITLE
Question regarding versions

### ISSUE THREAD

**Issue by JoyOtten** [smorabit/scWGCNA#5]
Dear scWGCNA developer,

I've been looking into on how to use this package and saw that there is a version issue. If I install the package in R I'm obtaining version 0.0.09000. However on the website there is already stating something of version 0.0.1. I can't get this version to install somehow. Can you put me in the right direction? 

Kind regards,
Joy

**Comment by smorabit** [comment]
Hi Joy,

Don't worry too much about the version number... Right now there's two "versions" of scWGCNA, the original (old, outdated, and now un-supported) which is located on the `master` branch, and the new version on the `dev` branch. Note that scWGCNA is under active development, so you will likely run into errors if you choose to use the new version of scWGCNA before it has a stable release.

Follow the instructions on [this page](https://smorabit.github.io/scWGCNA/) to install the new version. At this point I would not recommend trying to use the original version.

**Comment by JoyOtten** [comment]
Hi Sam,

Thanks I installed it already and I need to tweak the code anyway a bit due to that I want to use it on spatial transcriptome data. Thanks for your work that you put into this!
