### ISSUE TITLE
no slot of name "assay.used" for this object 

### ISSUE THREAD

**Issue by SCQUchenyang** [smorabit/scWGCNA#50]
Hi,
smorebit,thanks for developing this tool. And I met  an error ——"no slot of name "assay.used" for this object of class "SeuratCommand”" when I run ModuleEigengenes. I don't know what that means. This is my code:
`load("combined.RData")
combined <- SetupForWGCNA(combined,gene_select = "fraction",fraction = 0.05,wgcna_name = 'test')
combined <- MetacellsByGroups(seurat_obj = combined,group.by = c("seurat_clusters"),ident.group = 'seurat_clusters',k = 25,max_shared = 12,min_cells = 50,target_metacells = 250,reduction = 'pca')
combined <- NormalizeMetacells(combined)
combined <- SetDatExpr(
  combined,
  group_name = c("7","8","9"),
  group.by='seurat_clusters',assay="RNA"
)
combined <- TestSoftPowers(
  combined,
  setDatExpr = FALSE,
)
plot_list <- PlotSoftPowers(combined)
pdf("test.pdf",width=4,height=4)
print(plot_list)
dev.off()

combined <- ConstructNetwork(
  combined, soft_power=12,
  setDatExpr=FALSE,
  tom_name = 'combined_789' 
)

combined <- ScaleData(combined, features=VariableFeatures(combined))
combined <- ModuleEigengenes(
 combined,
 group.by.vars="seurat_clusters"
)`

Could you help me?

**Comment by SCQUchenyang** [comment]
Hi，
smorebit，it seems I have soloved this error——the seurat object were saved using Seurat v3.0. 
hdWGCNA works when I load a seurat (v 4.0) object.
But I have another question——How can I obtain coexpression between genes inside the module? For this figure (first figure in https://smorabit.github.io/hdWGCNA/articles/network_visualizations.html), how did I know the relationship between those genes?

**Comment by smorabit** [comment]
Hi, I am glad that you were able to resolve your issue using a Seurat 4 object rather than Seurat 3.

For your other point, I refer you to the [hdWGCNA basics tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html#optional-inspect-the-topoligcal-overlap-matrix-tom):

> hdWGCNA represents the co-expression network as a topoligcal overlap matrix (TOM). This is a square matrix of genes by genes, where each value is the topoligcal overlap between the genes. The TOM is written to the disk when running ConstructNetwork, and we can load it into R using the GetTOM function. Advanced users may wish to inspect the TOM for custom downstream analyses.

```
TOM <- GetTOM(seurat_obj)
```

I suggest looking at this previous issue #30 for more information. Hope this clarifies how to get the relationship between two genes based on the topological overlap matrix.
