### ISSUE TITLE
motifscan function error

### ISSUE THREAD

**Issue by yansongtongji** [smorabit/scWGCNA#53]
seurat_obj <- MotifScan(seurat_obj, species_genome = 'hg38', pfm = pfm_core,EnsDb = EnsDb.Hsapiens.v86)
Error in match(x, table, nomatch = 0L) : 'match' requires vector arguments

**Comment by smorabit** [comment]
This issue is lacking sufficient information for me to understand your problem or to help you resolve it. [This article ](https://wiredcraft.com/blog/how-we-write-our-github-issues/)may help you.

Furthermore, the motif analysis part of hdWGCNA is undergoing development and is not complete, so I do not recommend running any of this code for now.

**Comment by RajneeshSrivastava** [comment]
@smorabit  @yansongtongji Any luck resolving this issue?

**Comment by RajneeshSrivastava** [comment]
In addition to the issue raised by @yansongtongji,
Here I am adding the script from where i got the same error for reference.

```
library(Seurat)
library(tidyverse)
library(cowplot)
library(patchwork)
library(WGCNA)
library(hdWGCNA)
library(igraph)
library(JASPAR2020)
library(motifmatchr)
library(TFBSTools)
library(EnsDb.Hsapiens.v86)
library(GenomicRanges)

# using the cowplot theme for ggplot
theme_set(theme_cowplot())
# set random seed for reproducibility
set.seed(12345)

seurat_obj <- readRDS("path/seurat_obj.rds') 
#This object contains all the modules detected using hdWGCNA at seurat_obj@misc$SCT!
(Thanks @smorabit for hdWGCNA)

pfm_core <- TFBSTools::getMatrixSet( x = JASPAR2020, opts = list(collection = "CORE", 
                                                                               tax_group = 'vertebrates', 
                                                                               all_versions = FALSE)
                                                                 )

# run the motif scan with these settings for the mouse dataset

 seurat_obj <- MotifScan(seurat_obj, 
                         species_genome = 'hg38', 
                         pfm = pfm_core, 
                         EnsDb = EnsDb.Hsapiens.v86) #,wgcna_name = seurat_obj@misc$SCT)

Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```
Any idea or suggestion as from where this formatting error is coming from

Thank you!
Rajneesh

**Comment by TangentDeng** [comment]
@smorabit @RajneeshSrivastava @yansongtongji @rootze Did some one fix it?
