### ISSUE TITLE
Error when specifying SCT assay in SetDatExpr

### ISSUE THREAD

**Issue by ChristinaSteyn** [smorabit/scWGCNA#54]
Hi there Sam, thank you very much for developing such an awesome tool! I wanted to try using the SCT assay when running hdWGCNA but I got this error when I tried **Error in WGCNA::goodGenes(datExpr, ...) : unused argument (assay = "SCT")
Calls: SetDatExpr
Execution halted**

Could you please advise me?

**Comment by smorabit** [comment]
Hi Christina,

Were you following along with [this SCT tutorial](https://smorabit.github.io/hdWGCNA/articles/sctransform.html)? Not sure from your message what line of code is triggering the error, more context would be helpful.

**Comment by ChristinaSteyn** [comment]
Thank you very much for your rapid response! My apologies, I didn't actually realise there was a tutorial specifically for using SCTransformed counts so thanks for drawing my attention to that. I will try it now but just wanted to clarify from the tutorial the following: for "Option 1: SCTransform on single-cell data", must I use the scale.data slot of the SCT assay or is it alright to use the data slot? Thank you very much in advance.

**Comment by smorabit** [comment]
I haven't tried it myself but I think you should be able to use `counts` or `data` or `scale.data` with the SCT assay since [`SCTransform` ](https://satijalab.org/seurat/reference/sctransform)should fill all of those slots.

**Comment by ChristinaSteyn** [comment]
Okay great thanks very much!
