### ISSUE TITLE
Error in HubGeneNetworkPlot

### ISSUE THREAD

**Issue by meaksu** [smorabit/scWGCNA#56]
Hi,
I'm trying out the package and am getting this error using the hub gene network plot function. Do you know what could be causing this?

```
> HubGeneNetworkPlot(PTSD_meta, n_hubs = 3, n_other=5, edge_prop = 0.75, mods = 'all')
Selecting by kME_L1-M1
Selecting by kME_L1-M2
Selecting by kME_L1-M3

 grey L1-M1 L1-M2 L1-M3 
    5     8     8     8 
[1] "turquoise" "grey90"    "blue"      "brown"    
[1] "here"
[1] 285   4
Error in E(g) : could not find function "E"
```

Thanks!

**Comment by smorabit** [comment]
Hi,

I think that you forgot to load `igraph`. Please check the [tutorial](https://smorabit.github.io/hdWGCNA/articles/network_visualizations.html) to see which packages you need to load before running the code.
