### ISSUE TITLE
Choose networkType in TestSoftPowers()

### ISSUE THREAD

**Issue by SL1993** [smorabit/scWGCNA#57]
Hi, @smorabit . Thanks for your excellent job of hdWGCNA.
When using `hdWGCNA::TestSoftPowers()` to explore soft threshold, I found no such parameter like `networkType` to be set. 
While in `WGCNA::pickSoftThreshold()`, one can choose `networkType` among "unsigned", "signed" and "signed hybrid". Is it possible to add this function for `hdWGCNA::TestSoftPowers()` in the future?

**Comment by smorabit** [comment]
Hi,

Thanks for the suggestion. I added the `networkType` option to `TestSoftPowers`, please update to the newest version of hdWGCNA to use this option.

**Comment by SL1993** [comment]
It really helps to custom my network, Thanks! 
Also noticed in Closed Issues #47 `using hdWGCNA with SCT assay`, a new tutorial was provided, in which you mentioned only 3,000 genes are stored in the `scale.data` slot after `SCTransform`. In fact, `SCTransform` has this parameter ,`return.only.var.genes`, which will return all the normalized genes if set to `FALSE`.  Therefore no need to select only top 3000 variable genes with SCT assay when using hdWGCNA. Hope this will be helpful.

**Comment by smorabit** [comment]
Thanks for the comment about SCT. Seems like a bunch of people want to use it for hdWGCNA, but I have almost no experience using it myself so this is very useful information. I will make this more clear in the SCTransform tutorial in a future update.
