### ISSUE TITLE
change number of top genes in ModuleNetworkPlot

### ISSUE THREAD

**Issue by Brawni** [smorabit/scWGCNA#58]
Hello!
Great package again! I was wondering if it's possible to add an argument in the `ModuleNetworkPlot` function to specify the number of genes to show in the network plots.

Thanks!

**Comment by smorabit** [comment]
Definitely something that will be done in a future update, but I don't have a plan to do it immediately.

**Comment by smorabit** [comment]
Finally have updated this function to be able to specify the number of genes in the inner circle and in the outer circle. Please refer to the [network visualization tutorial](https://smorabit.github.io/hdWGCNA/articles/network_visualizations.html#individual-module-network-plots).

```
ModuleNetworkPlot(
    seurat_obj, 
    outdir='ModuleNetworks', 
    n_inner = 20, # number of genes in inner ring
    n_outer = 30, # number of genes in outer ring
    n_conns = Inf, # show all of the connections
    plot_size=c(10,10), # larger plotting area
    vertex.label.cex=1 # font size
)
```
