### ISSUE TITLE
Subset cell types before SetupForWGCNA or no ?

### ISSUE THREAD

**Issue by AKypR99** [smorabit/scWGCNA#68]
Hello,

Thank you for this very promising package.

I currently have at my disposal a scRNAseq containing cancer cells at different stages (Early & Advanced stage) that I would like to compare with gene coexpression network. However the beginning of the following documentation https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html leaves me a little doubt. Since i have different cell types in my seurat object, should I separate these two cell types with a subset of the SeuratObject in order to separate each cell type before running the "SetupForWGCNA" or should I leave the scRNAseq complete with the two advanced stages?

So in case, I leave the complete two cell types of my scRNAseq in "SetupForWGCNA", will the "MetacellsByGroups" function identify each of these two cell types if I give the information in the _group.by_ parameter?

Thanks,
Anthony

**Comment by smorabit** [comment]
HI Anthony, if I understand correctly you have a dataset contianing many different cell types but you are only interested in doing network analysis on two of them? In that case you can subset the dataset for the cell types of interest before running `SetupForWGCNA`, and provide the cell type information to the `group.by` parameter in `MetacellsByGroups`.

**Comment by AKypR99** [comment]
Hi Sam,

Thank you for your quick answer.

Indeed, I have a dataset containing only leukemic cells in 2 states of advancement in the pathology (let's say Stage 1 and Stage 2). They are the same type of cells and the difference is only in the stage of advancement of the cancer.

The idea would be to see what can differentiate them from each other. So, if I understood your answer correctly, I can put directly the dataset containing all the leukemic cells of Stage 1 and Stage 2 in SetupForWGCNA and then I would pass one by one in the parameter group.by of MetacellsByGroups the different cells of each Stage?

Thanks,
Anthony

**Comment by smorabit** [comment]
Sounds like in your case you want to subset the seurat object to just contain leukemic cells before starting the hdWGCNA pipeline. Make sure you pass the Stage1 vs Stage2 metadata in the `group.by` parameter in `MetacellsByGroups`. After you run the basics vignette on your data, you can take a look at [this tutorial](https://smorabit.github.io/hdWGCNA/articles/differential_MEs.html) to run differential module eigengene analysis to see which modules are up/down regualted in the different stages.

**Comment by AKypR99** [comment]
Hi Sam,

Thank you very much for your help, it is clearer for me now!

Anthony
