### ISSUE TITLE
Error in MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("cell_type",  :   Invalid reduction (pca). Reductions in Seurat object: harmony, umap

### ISSUE THREAD

**Issue by Tycooner** [smorabit/scWGCNA#69]
Using the data Zhou et al snRNA-seq dataset named `Zhou_2020.rds` when run the step, it get errors:

seurat_obj <- MetacellsByGroups(
+   seurat_obj = seurat_obj,
+   group.by = c("cell_type", "Sample"), # specify the columns in seurat_obj@meta.data to group by
+   k = 25, # nearest-neighbors parameter
+   max_shared = 10, # maximum number of shared cells between two metacells
+   ident.group = 'cell_type' # set the Idents of the metacell seurat object
+ )

Error in MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("cell_type",  :
  Invalid reduction (pca). Reductions in Seurat object: harmony, umap

Why?

**Comment by smorabit** [comment]
The error message is telling you that you need to pick a valid reduction. By default, hdWGCNA tries to use pca. When pca isn't present in the dataset, it will throw this error so you need to tell it to use a different reduction. You should re-run the code and set `reduction = "harmony"` in the call to `MetacellsByGroups`
