### ISSUE TITLE
how to choose groups when SetDatExpr ?

### ISSUE THREAD

**Issue by jisnoalia** [smorabit/scWGCNA#71]
Thanks for u software, I have a  confusion. When I focus on all cell types, how do I choose `group_name`  in SetDatExpr.

**Comment by smorabit** [comment]
Hi,

To select all cell types with `SetDatExpr`, you just need to set `group_name = NULL`:

```
seurat_obj  <- SetDatExpr(
  seurat_obj,
  group.by=NULL,
  group_name = NULL
)
```
