### ISSUE TITLE
Tutorial Spatial WGCNA

### ISSUE THREAD

**Issue by MUIphysiologie** [smorabit/scWGCNA#72]
Hey, maybe one suggestions from my side, the merge in your tutorial might not be row.names but rather 0 at least for me I don't have any column named row.names.

`new_meta <- [merge](https://rdrr.io/r/base/merge.html)(seurat_obj@meta.data, image_df, by='row.names')`

**Comment by smorabit** [comment]
Seems to be working fine for me. Looking at the [documentation for the merge function](https://rdrr.io/r/base/merge.html):

> Columns to merge on can be specified by name, number or by a logical vector: the name "row.names" or the number 0 specifies the row names. If specified by name it must correspond uniquely to a named column in the input.

So using 0 as you suggested would probably also work.
