### ISSUE TITLE
Projecting Module DotPlot Average Expression / Percent Expressed meaning

### ISSUE THREAD

**Issue by AKypR99** [smorabit/scWGCNA#74]
Hello,

I have a question maybe a bit simple about the different data represented on the dotplot for the projection of different modules of a dataset A on another dataset B.

Indeed, in the tutorial [Projecting Module section Visualization](https://smorabit.github.io/hdWGCNA/articles/projecting_modules.html#visualization),  we find a [DotPlot](https://smorabit.github.io/hdWGCNA/articles/figures/projection/projected_dotplot.png) having for legend the "Average Expression" and the "Percent Expressed". 

My question is about these two names and their meaning.

1. Does the Average Expression represent the average hMEs of each module of all the cells of the different cell types (or other group.by parameter)?

2. As for the "Percent Expressed" how is it determined for the hMEs (in the sense that the Average Expression represents the hMES)? Is it the proportion of cells with an hME different from 0?

Thanks again for this package!
Anthony

**Comment by smorabit** [comment]
Hi,

I think that this is essentially a question of how to interpret the output of the Seurat function `DotPlot`. Just a reminder that this function is not actually part of hdWGCNA, so you may wish to consult the [`DotPlot` documentation](https://satijalab.org/seurat/reference/dotplot) for more details. `DotPlot` generates a grid of spots for a list of features and a list of groups noted by the `features` and the `group.by` parameters respectively. The color of each spot corresponds to the average expression of the feature in a particular group, and the size of the dot corresponds to the percentage of cells with greater than zero expression of that feature in a particular group. By default, the `DotPlot` parameter `scale` is set to `TRUE`, which means that each feature is scaled across the different groups, and this is why you will see negative expression values if you are plotting gene expression.
