### ISSUE TITLE
group.by same biological sample of origin

### ISSUE THREAD

**Issue by joe-jhou2** [smorabit/scWGCNA#78]
Could you please clarify the "same biological sample of origin"? the sample from one type of specimen (like blood) in one subject?
Can I group them by sample category? e.g. disease status A, B, et.al from different patients.

**Comment by smorabit** [comment]
I am not sure if I can really answer your question without further details about what kind of data you're working with or your experimental setup. You can essentially group by whatever you want as long as you can justify it.

**Comment by joe-jhou2** [comment]
Thanks. I have 10x scRNAseq data from 12 samples, 5 are controls and 7 are in the experiment group. After seurat clustering, 20 clusters in total are identified. I'm interested in 5 clusters out of them. Therefore, I subset the dataset, only focusing on these 5 clusters. So far, when I made metacells, I set up the group.by = cell type and sample id. I wonder if I should group by sample id or group id (aka, cells aggregate by control and experiment groups instead of by each sample). Which approach is making sense? Thanks.

**Comment by smorabit** [comment]
You can use either the group id or the sample id, both are reasonable choices. I would generally advise you to use the group id instead of the sample id if your cell type / cluster of interest is rare in a given sample in order to  have a reasonable number of metacells for network analysis.
