### ISSUE TITLE
Hub gene selection (kME vs abs(kME))

### ISSUE THREAD

**Issue by hongsilv** [smorabit/scWGCNA#8]
Dear scWGCNA developers,

I first want to appreciate for the wonderful R library. 
I want to ask about how scWGCNA selects **hub genes**. 
Is it genes with high kME value itself? or high abs(kME)?

Based on my data and the network plots, I inferred that scWGCNA selects top hub genes by kME values itself (no abs()).
Also, according to the Examples section in "ModuleNetworkPlot" function page (https://smorabit.github.io/scWGCNA/reference/ModuleNetworkPlot.html),
it seems to select hub genes by "top_n" function on kME values.
` hub_list <- lapply(mods, function(cur_mod) {
         cur <- subset(modules, module == cur_mod)
         cur <- cur[, c("gene_name", paste0("kME_", cur_mod))] %>% 
             **top_n(n_hubs)**
         colnames(cur)[2] <- "var"
         cur %>% arrange(desc(var)) %>% .$gene_name
     })`
However, for some modules, all genes in that modules have negative kME values , and by "ModuleNetworkPlot" function, genes with low abs(kME) but high kME are selected.

As long as I know, kME values can have values from -1 to +1, and if kME is close to +1 or -1, it means that the gene is highly connected to the module. Regarding this, I think hub genes should be selected by abs(kME).

What do you think about this?

Thank you,
Best regards, SungEun

**Comment by smorabit** [comment]
HI SungEun,

Thanks for the insightful comment. You are correct that we currently select hub genes by the top kME values in each module. The kME is essentially the correlation of a gene with the module eigengene. Figure 5 from [this paper](https://pubmed.ncbi.nlm.nih.gov/18704157/) may help you to understand. If a gene is anti-correlated with the module eigengene, we would have a negative kME value. If you selected an "unsigned" network, the direction of the correlation does not matter, only the strength of the correlation, so you would be correct that we should select hub genes by absolute value of kME for an unsigned network only. On the other hand, for signed networks, the direction of the correlation does matter, so we would only take positively correlated genes as the hub genes. Currently a signed network is the deafault behavior, and is generally advisable for expression datasets. However, I will add an update soon that will check if it is a signed or unsigned network and then select hub genes accordingly.

**Comment by hongsilv** [comment]
Hi, 
Thank you for the clarification and quick reply.

singed network = use kME
unsigned network = use abs(kME)

Fully understood :) Thank you!
