### ISSUE TITLE
argument is not a matrix

### ISSUE THREAD

**Issue by Tian3333** [smorabit/scWGCNA#80]
seurat_obj <- ModuleConnectivity(seurat_obj,   group.by = 'subgroup', group_name = 'XXXX' )

Error in t.default(exp_mat) : argument is not a matrix

When come to this line, it stop me and I don't know how to solve it. Please help me!

**Comment by Tian3333** [comment]
However, when I add ,sparse = F and it can run. I don't know whether it is a good way to solve this issue

**Comment by espre-zzo** [comment]
I have the same issue.
Setting sparse =FALSE could run the code, but shows warning message such as
`In bicor(datExpr, datME, , use = "p") :
  bicor: zero MAD in variable 'x'. Pearson correlation was used for individual columns with zero (or missing) MAD.`

**Comment by smorabit** [comment]
Hi, there was a bug in the `ModuleConnectivity` function after re-working some of the code. The `sparse=TRUE` option should run this function a lot faster and with less memory, but `sparse=FALSE` runs the old code. No need to worry about the warning message. 

Please install the newest version of hdWGCNA and run again to resolve the error.
