### ISSUE TITLE
 SetDatExpr reported an error

### ISSUE THREAD

**Issue by maqingyue** [smorabit/scWGCNA#84]
Hi!
In the space transcriptome, hdWGCNA analysis was performed, and SetDatExpr reported the following error：

seurat_obj  <- SetDatExpr(
  seurat_obj,
  group.by=NULL,
  group_name = NULL
)
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index

or

seurat_obj  <- SetDatExpr(
  seurat_obj,
  group.by="seurat_clusters",
  group_name = NULL
)
Error in WGCNA::goodGenes(datExpr, ...) : 
  datExpr must contain numeric data.

When I use my own data or the data in your tutorial, I will get this error. 
The following is the complete code, which is almost the same as in the tutorial. It only skips "seurat_mouse_vis $region<- factor (as. character (seurat_mouse_vis $region), levels=c ('Antiior ',' Posterior '))".

# single-cell analysis package
library(Seurat)
# package to install the mouse brain dataset
library(SeuratData)
# plotting and data science packages
library(tidyverse)
library(cowplot)
library(patchwork)
# co-expression network analysis packages:
library(WGCNA)
library(hdWGCNA)
# install this package, which allows us to compute distance between the spots
#install.packages('proxy')
library(proxy)
# enable parallel processing for network analysis (optional)
enableWGCNAThreads(nThreads = 8)
# using the cowplot theme for ggplot
theme_set(theme_cowplot())
# set random seed for reproducibility
set.seed(12345)

# download the mouse brain ST dataset (stxBrain)
SeuratData::InstallData("stxBrain")#This step failed. Install the package manually

# load the anterior and posterior samples
brain <- LoadData("stxBrain", type = "anterior1")
brain$region <- 'anterior'
brain2 <- LoadData("stxBrain", type = "posterior1")
brain2$region <- 'posterior'

# merge into one seurat object
seurat_obj <- merge(brain, brain2)
seurat_obj$region <- factor(as.character(seurat_obj$region), levels=c('anterior', 'posterior'))

# make a dataframe containing the image coordinates for each sample
image_df <- do.call(rbind, lapply(names(seurat_obj@images), function(x){
  seurat_obj@images[[x]]@coordinates
}))

# merge the image_df with the Seurat metadata
new_meta <- merge(seurat_obj@meta.data, image_df, by='row.names')

# fix the row ordering to match the original seurat object
rownames(new_meta) <- new_meta$Row.names
ix <- match(as.character(colnames(seurat_obj)), as.character(rownames(new_meta)))
new_meta <- new_meta[ix,]

# add the new metadata to the seurat object
seurat_obj@meta.data <- new_meta
head(image_df)

# normalization, feature selection, scaling, and PCA
seurat_obj <- seurat_obj %>%
  NormalizeData() %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA()

# Louvain clustering and umap
seurat_obj <- FindNeighbors(seurat_obj, dims = 1:30)
seurat_obj <- FindClusters(seurat_obj,verbose = TRUE)
seurat_obj <- RunUMAP(seurat_obj, dims = 1:30)

# set factor level for anterior / posterior
seurat_mouse_vis$region <- factor(as.character(seurat_mouse_vis$region), levels=c('anterior', 'posterior')) #Error reported in this step, skip

# show the UMAP
p1 <- DimPlot(seurat_obj, label=TRUE, reduction = "umap", group.by = "seurat_clusters") + NoLegend()
p1

p2 <- SpatialDimPlot(seurat_obj, label = TRUE, label.size = 3)
p2

seurat_obj <- SetupForWGCNA(
  seurat_obj,
  gene_select = "fraction",
  fraction = 0.05,
  wgcna_name = "vis"
)

seurat_obj <- MetaspotsByGroups(
  seurat_obj,
  group.by = c("region"),
  ident.group = "region",
  assay = 'Spatial',
  slot = 'counts'
)
seurat_obj  <- NormalizeMetacells(seurat_obj)

m_obj <- GetMetacellObject(seurat_obj)
m_obj

# set up the expression matrix, set group.by and group_name to NULL to include all spots
seurat_obj  <- SetDatExpr(
  seurat_obj,
  group.by="seurat_clusters",
  group_name = NULL
)

I'm looking forward to your answer, thank you!

**Comment by smorabit** [comment]
Hi, 

Could you please try to re-install the package and run it again with the newest version? I was able to reproduce your error and I believe that I fixed it in the newest version.

**Comment by maqingyue** [comment]
Thank you for your answer. The problem has been well solved.

**Comment by maqingyue** [comment]
Hi,
    when I analyze my data and select the soft threshold, the figure is like this. Why does the following value fluctuate so much? Does this affect the soft threshold I choose?

[soft-power-thresholds.pdf](https://github.com/smorabit/hdWGCNA/files/10778962/soft-power-thresholds.pdf)

Besides，my data is the spatial transcriptome integration data of three young mice and three old mice, I don't know whether so many samples are enough for hdWGCNA.

I'm looking forward to your reply, thank you！
