### ISSUE TITLE
Module and trait

### ISSUE THREAD

**Issue by maqingyue** [smorabit/scWGCNA#87]
Hi,
can the hdWGCNA package directly link modules and traits? For example, I used the integrated data of young and old samples at the beginning. I want to know the relationship between the modules and aging. Similar to the picture below, this is the picture I found online.

![example](https://user-images.githubusercontent.com/113956599/220286820-2ef46e55-e609-44a8-b668-dc9fdc0deb2d.png)

I look forward to receiving your reply.

**Comment by smorabit** [comment]
You should follow [this tutorial](https://smorabit.github.io/hdWGCNA/articles/module_trait_correlation.html) to investigate module-trait relationships.

**Comment by maqingyue** [comment]
Hi,
I have learned this tutorial, but it is not completely consistent with my needs. I want the relationship between modules and features, as you said in the tutorial: Categorical variables with only 2 categories, such as "control" and "condition" (as shown in Figure 1), but the relationship between modules and cell types is finally shown in the tutorial (as shown in Figure 2). I got Figure 3 according to the tutorial. In fact, the parameter on the right is useless to me, and this parameter cannot be empty. I have tried a lot and failed to get the desired results. I hope you can give me some suggestions. Thank you!
fig.1
![fig1](https://user-images.githubusercontent.com/113956599/220510893-e7e94db7-d770-4e00-9d31-a9f5548a4c65.png)

fig.2
![fig2](https://user-images.githubusercontent.com/113956599/220510953-41d30d75-bca6-4c6c-89b6-037850298f87.png)

fig.3
![fig3](https://user-images.githubusercontent.com/113956599/220510986-14933b93-9b85-4b36-9d83-5224981fb4f4.png)
