### ISSUE TITLE
Module and trait 

### ISSUE THREAD

**Issue by maqingyue** [smorabit/scWGCNA#89]
Hi,
I have learned this tutorial (https://smorabit.github.io/hdWGCNA/articles/module_trait_correlation.html), but it is not completely consistent with my needs. I want the relationship between modules and features, as you said in the tutorial: Categorical variables with only 2 categories, such as "control" and "condition" (as shown in Figure 1), but the relationship between modules and cell types is finally shown in the tutorial (as shown in Figure 2). I got Figure 3 according to the tutorial. In fact, the parameter on the right is useless to me, and this parameter cannot be empty. I have tried a lot and failed to get the desired results. I hope you can give me some suggestions. Thank you!
Fig1.
![fig1](https://user-images.githubusercontent.com/113956599/220807582-d7b63901-9b62-4209-92ee-d2c2e11df3f9.png)

Fig2.
![fig2](https://user-images.githubusercontent.com/113956599/220807606-742968c7-d239-42df-a343-23760be13551.png)

Fig3.
![fig3](https://user-images.githubusercontent.com/113956599/220807627-67e99e6e-5ea4-4ce3-be13-f7a124fe78b8.png)

**Comment by smorabit** [comment]
Hi,

Can you please include the code that you ran? Could you also clarify what is the trait that you are interested in?

**Comment by maqingyue** [comment]
Hi,
My sample is three young samples and three old samples. I used the six integrated samples to do the HDEGCNA analysis, and now I have four modules. I want to know how the gene correlation of the module characteristics changes compared with the young.

This is my code about module trait correlation. cur_traits  is a parameter that cannot be empty. 

sample$orig.ident <- as.factor(sample$orig.ident)
cur_traits <- c("percent.mt","nFeature_Spatial","nCount_Spatial") 
sample <- ModuleTraitCorrelation(
  sample,
  traits = cur_traits,
  group.by = 'orig.ident'
)

mt_cor <- GetModuleTraitCorrelation(sample)
names(mt_cor)
names(mt_cor$cor)

pdf("D:/BGI_learning/select-samples/results/brain/six samples/hippocampus/WGCNA/module-sample.pdf")
PlotModuleTraitCorrelation(
  sample,
  label = 'fdr',
  label_symbol = 'numeric',
  text_size = 2,
  text_digits = 2,
  text_color = 'blue',
  high_color = 'yellow',
  mid_color = 'black',
  low_color = 'purple',
  plot_max = 0.2,
  combine=TRUE
)
dev.off()

**Comment by smorabit** [comment]
It looks like you never included the young/old as a trait, you are only using `cur_traits <- c("percent.mt","nFeature_Spatial","nCount_Spatial")` to run `ModuleTraitCorrelation`, that's why you don't have any information about the relationship between module and age.

**Comment by maqingyue** [comment]
Can I calculate the correlation between modules and samples? This module is divided by the integrated data of six samples.

**Comment by smorabit** [comment]
No it is not recommended to correlate module with sample ID. From the tutorial page:

> Variables that can not be used: 
>
> Categorical variables with more than two categories that are not sequentially linked. For example, suppose you have a dataset consiting of three strains of transgenic mice and one control. Categorical variables must be converted to numeric before running the correlation, so you will end up with a correlation that is not at all biologically meaningful since there’s not a way to order the three different strains in a way that makes sense as a numeric variable. In this case, you should just set up a pairwise correlation between control and each strain separately. We often have a “Sample ID” variable indicating which cell came from which sample, and this is a variable that does not necessarily make sense to order in any particular way, so a variable like this would not be suitable for module-trait correlation analysis.

**Comment by maqingyue** [comment]
My six samples are three young and three old, which is equivalent to three biological duplicates in each category. Can't we count two categories? Then can I choose a young sample and an old sample for correlation analysis?

**Comment by smorabit** [comment]
Why don't you just include age as the trait?

**Comment by maqingyue** [comment]
I want to take age as a trait. It is divided into young and old, and then explores the correlation with the module to find out what changes have taken place in the aging process. But I don't know how to program. Can you give some suggestions.

**Comment by smorabit** [comment]
Sounds like you want to correlate the module with age, so you need to include age in your list of traits in the `ModuleTraitCorrelation` function. [In the example tutorial](https://smorabit.github.io/hdWGCNA/articles/module_trait_correlation.html), we actually did use age as one of the example traits, so it may help you to look at what was done in the tutorial.
