### ISSUE TITLE
error when calculating metacell

### ISSUE THREAD

**Issue by yamihn** [smorabit/scWGCNA#92]
I'm wondering why this errors appears everytime I try to calculate metacells.

DefaultAssay(obj) <- "RNA"
obj@assays$ATAC <- NULL
obj <- MetacellsByGroups( seurat_obj = obj, assay = "RNA", 
   group.by = c("seurat_clusters", "treatment_timepoint"),
   k = 10, 
   min_cells = 10,
   max_shared = 10, 
   ident.group = 'seurat_clusters'
 )
Error: Cannot find assay 'ATAC' in this Seurat object

**Comment by smorabit** [comment]
Hi,

Is this RNA + ATAC multi-ome data? 

Unfortunately I am not able to reproduce this error. Can you provide a reproducible example on a publicly available dataset?
