### ISSUE TITLE
Related DME analysis 

### ISSUE THREAD

**Issue by mybioinformatics** [smorabit/scWGCNA#93]
Dear Developers

Hello, thank you for developing such a cool algorithm.

I followed the tutorial and followed various analyzes, but I have one question.

When analyzing DME (Differential Module expression), what should be the standard for the foldchange threshold??

Normally, avg_log2FC is set to 0.2(+,-) when analyzing DEG of scRNA, so would it be okay to set the analysis to between 0.1 and 0.2 to draw conclusions??

**Comment by smorabit** [comment]
Hi,

We don't have a "standard" fold-change threshold for differential module eigengene analysis, and I also don't think there is such a thing as a "standard" fold-change threshold for differential gene expression analysis for scRNA-seq. Thresholds typically vary depending on the comparison as well as other factors. 

> would it be okay to set the analysis to between 0.1 and 0.2 to draw conclusions??

You probably also want to consider modules with negative fold-change.

**Comment by TK-Lab-Vanderbilt-University** [comment]
Dear Developers

Thank you for your kind reply :) 

I just want to identify network modules with statistically significant (p.adj < 0.05) up- or down-regulation through differential module eigengene analysis of your algorithm.

Then what would be the criterion of fold-change to identify it??

thank you

**Comment by smorabit** [comment]
Ultimately it's up to you to determine a threshold. I have used a threshold of 0.25 in the past but that is not a "standard" or a "rule" to be used with every dataset.
