### ISSUE TITLE
Error in ModuleNetworkPlot

### ISSUE THREAD

**Issue by socialhang** [smorabit/scWGCNA#96]
Hi！

here are some problems when I use ModuleNetworkPlot.

```r
Error in h(simpleError(msg, call)) : 
  在为'as.matrix'函数选择方法时评估'x'参数出了错: subscript out of bounds
``` 

What should I do?

**Comment by smorabit** [comment]
Hi, I am happy to help you solve the issue but first it would help me if you could show the error message in English, and if you can show me the code that you ran.

**Comment by socialhang** [comment]
Hi，I am so sorry about the language.

It is the error.

```r
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': subscript out of bounds
``` 

It is the code.

```r
ModuleNetworkPlot(
  seurat_obj,
  outdir = paste0(dir0,"/ModuleNetworks"),
  mods = "anther2"
 )
``` 

I think it's because there are too few genes in “anther2”. In other mods, Images can be output normally.

**Comment by smorabit** [comment]
How many genes are in that module? The function `ModuleNetworkPlot` tries to plot the top 25 hub genes for the module, so it may have a problem if the module has less than 25 genes. I don't recommend setting the minimum module size to be that low when running `ConstructNetwork`.

**Comment by socialhang** [comment]
OK，Thanks. I only have 14 genes.
