### ISSUE TITLE
How to visualize a specific gene in modules

### ISSUE THREAD

**Issue by yamihn** [smorabit/scWGCNA#97]
Hi, I'm studying a particular gene, and instead of seeing the hub genes of the various modules I'd like to understand how to visualize within the module, if present, the gene that interests me and the nodes to which it is connected. There is a way to plot the network of my gene of interest?

**Comment by smorabit** [comment]
Hi, there is currently not a built-in way to make this kind of visualization in hdWGCNA, but I think you could accomplish this using [igraph](https://r.igraph.org/) or some other network plotting package.

**Comment by yamihn** [comment]
Thank you! Could you suggest me a way to extract the data I Need to generate the network?

**Comment by smorabit** [comment]
You can run the hdWGCNA function `ConstructNetwork` to generate a co-expression network, and then you can extract the network using `GetTOM`. You can then subset the network for the connections to your gene of interest. 

```
# get the topological overlap matrix from the seurat object
net <- GetTOM(seurat_obj)

# get the co-expression weights for your gene of interest:
my_gene <- 'GFAP'
my_conns <- net[my_gene,]

# get the top 25 connections to this gene:
my_conns <- my_conns[rev(order(my_conns))]
my_conns[1:25]

```
Note that hdWGCNA (and WGCNA in general) has continuous values for edge weights, it's not just a binary value for connected or not connected, so you might have to threshold to only keep the strongest connections (as shown above).

You could then go on to make a plot using [igraph](https://igraph.org/r/doc/plot.common.html).

**Comment by yamihn** [comment]
thank you very much for your help
