### ISSUE TITLE
Issue in following "hdWGCNA in single-cell data" tutorial

### ISSUE THREAD

**Issue by bykovam** [smorabit/scWGCNA#98]
Dear Swarup lab,

There is an issue when following the tutorial "hdWGCNA in single-cell data". Everything works fine until I reach this step:

# construct metacells  in each group
seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("cell_type", "Sample"), # specify the columns in seurat_obj@meta.data to group by
  k = 25, # nearest-neighbors parameter
  max_shared = 10, # maximum number of shared cells between two metacells
  ident.group = 'cell_type' # set the Idents of the metacell seurat object
)

I receive an error message:
Error in MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("cell_type",  : 
  Invalid reduction (pca). Reductions in Seurat object: harmony, umap

When looking at the MetacellsByGroups reference page, the default reduction is pca. The two reductions in the dowloaded Zhou et al. dataset are these:

> seurat_obj@reductions
$harmony
A dimensional reduction object with key PC_ 
 Number of dimensions: 50 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: RNA 

$umap
A dimensional reduction object with key UMAP_ 
 Number of dimensions: 2 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: RNA

This doesn't seem like a big issue, but it might be something to note within the tutorial

**Comment by smorabit** [comment]
Thanks for pointing this out, the tutorial has been updated to use explicitly use the harmony reduction.
