### ISSUE TITLE
Export the gene network within the module

### ISSUE THREAD

**Issue by Bioinformatics-rookie** [smorabit/scWGCNA#99]
I successfully ran Vignettes' Network Visualization，and got the ndividual module network plots，But I would like to know more about the correlation between genes and genes, like the table in the  below, how it should work 
![微信截图_20230321165948](https://user-images.githubusercontent.com/67935442/226558953-124f073d-4c90-454b-b9ed-69f33e0d6b07.png)

**Comment by smorabit** [comment]
From the [hdWGCNA tutorial](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html):

> hdWGCNA represents the co-expression network as a topoligcal overlap matrix (TOM). This is a square matrix of genes by genes, where each value is the topoligcal overlap between the genes. The TOM is written to the disk when running ConstructNetwork, and we can load it into R using the GetTOM function. Advanced users may wish to inspect the TOM for custom downstream analyses.

```
TOM <- GetTOM(seurat_obj)
```
